### ISSUE TITLE
IOS XE: show spanning-tree vlan not catching port-fast interface

### ISSUE THREAD

**Issue by lzuzcak** [CiscoTestAutomation/genieparser#105]
Hello team

Command "show spanning-tree vlan <>" will not parse interface information in case that interface is configured as portfast (spanning-tree portfast). Issue is in STP parser line 928, parser do not expect "Edge" keyword in string - it expects only P2p Peer(STP) / P2p Bound(RSTP).

//Working output 

Gi0/1               Root FWD 4         128.2    P2p Peer(STP)

//Non-working output

Gi0/2               Desg FWD 4         128.3    P2p Edge

I would suggest to add there another variable, which would catch edge and other interface types.

//Non-working parser
`'( +(Bound\((?P<bound>\w+)\)|Peer\((?P<peer>\w+)\)))?'`

//Working parser
`( +(Bound\((?P<bound>\w+)\)|Peer\((?P<peer>\w+)\))| (?P<edge>\w+))?`

I would like this to be fixed in future releases.

Thank you

Lubos Zuzcak

**Comment by xiaoxinz-cisco** [comment]
Hello @lzuzcak  ,

Thank you for reporting. We will look into the issue and get back to you.

Thanks,
Irene

**Comment by xiaoxinz-cisco** [comment]
Hi @lzuzcak ,

Just want to check is it addressed in your pull request: https://github.com/CiscoTestAutomation/genieparser/pull/109 ?

Thanks,
Irene

**Comment by lzuzcak** [comment]
Hello @xiaoxinz-cisco / Irene

Yes, I have just submitted pull request for this issue.

Lubos

**Comment by xiaoxinz-cisco** [comment]
Hi @lzuzcak ,

Thanks for your contribution! Our support team is reviewing the pull request now.

Thanks,
Irene
