### ISSUE TITLE
Failed to parse subslot 0/0 of 'show inventory'

### ISSUE THREAD

**Issue by vskyman** [CiscoTestAutomation/genieparser#107]
NAME: "NIM subslot 0/0", DESCR: "Front Panel 4 ports Gigabitethernet Module"
PID: ISR4451-X-4x1GE   , VID: V01  , SN:            

The subslot 0/0 will be parsed as type 'lc' because of its prefix 'ISR'.

**Comment by kamyarz1991** [comment]
Hi,

What do you expect to see as output. Can you provide me with that, and a the output that you extracted this block from?
Thank you

**Comment by vskyman** [comment]
This should be subslot 0/0, the output is from Overlord platform.
More logs:
[2020-03-18 18:38:27,346] +++ overlord-19: executing command 'show platform' +++
show platform
Chassis type: ISR4451-X/K9

Slot      Type                State                 Insert time (ago) 
--------- ------------------- --------------------- ----------------- 
0         ISR4451-X/K9        ok                    00:13:25      
 0/0      ISR4451-X-4x1GE     ok                    00:11:56      
 0/1      NIM-ES2-4           ok                    00:11:56      
 0/2      NIM-24A             ok                    00:11:56      
 0/3      NIM-SSD             ok                    00:11:56      
 0/4      PVDM4-32            ok                    00:11:56      
1         ISR4451-X/K9        ok                    00:13:25      
2         ISR4451-X/K9        ok                    00:13:25      
R0        ISR4451-X/K9        ok, active            00:13:25      
F0        ISR4451-X/K9        ok, active            00:13:25      
P0        PWR-4450-AC         ok                    00:12:51      
P1        Unknown             empty                 never         
P2        ACS-4450-FANASSY    ok                    00:12:51      

Slot      CPLD Version        Firmware Version                        
--------- ------------------- --------------------------------------- 
0         13061029            16.12(2r)                           
1         13061029            16.12(2r)                           
2         13061029            16.12(2r)                           
R0        13061029            16.12(2r)                           
F0        13061029            16.12(2r)                           

[2020-03-18 18:38:27,503] +++ overlord-19: executing command 'show inventory' +++
show inventory

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO: Please use "show license UDI" to get serial number for licensing.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

NAME: "Chassis", DESCR: "Cisco ISR4451 Chassis"
PID: ISR4451-X/K9      , VID: V01  , SN: FGL172511Q5

NAME: "Power Supply Module 0", DESCR: "450W AC Power Supply for Cisco ISR4450, ISR4350"
PID: PWR-4450-AC       , VID: V01  , SN: DCA1645X0EK

NAME: "Fan Tray", DESCR: "Cisco ISR4450, ISR4350 Fan Assembly"
PID: ACS-4450-FANASSY  , VID:      , SN:            

NAME: "module 0", DESCR: "Cisco ISR4451 Built-In NIM controller"
PID: ISR4451-X/K9      , VID:      , SN:            

NAME: "NIM subslot 0/1", DESCR: "NIM-ES2-4"
PID: NIM-ES2-4         , VID: V01  , SN: FOC1831B0TS

NAME: "NIM subslot 0/2", DESCR: "24 ports Async Serial NIM"
PID: NIM-24A           , VID: V01  , SN: DNI2047033J

NAME: "NIM subslot 0/3", DESCR: "NIM SSD Module"
PID: NIM-SSD           , VID: V01  , SN: FOC17356NWR

NAME: "subslot 0/3 disk1", DESCR: "harddisk"
PID: Samsung SSD 860 EVO 250GB               , VID: RVT03B6Q, SN: S3Y9NX0M604745D     

NAME: "PVDM subslot 0/4", DESCR: "PVDM4-32 Voice DSP Module"
PID: PVDM4-32          , VID: V01  , SN: FOC17176BKC

NAME: "NIM subslot 0/0", DESCR: "Front Panel 4 ports Gigabitethernet Module"
PID: ISR4451-X-4x1GE   , VID: V01  , SN:            

NAME: "module 1", DESCR: "Cisco ISR4451 Built-In SM controller"
PID: ISR4451-X/K9      , VID:      , SN:            

NAME: "module 2", DESCR: "Cisco ISR4451 Built-In SM controller"
PID: ISR4451-X/K9      , VID:      , SN:            

NAME: "module R0", DESCR: "Cisco ISR4451 Route Processor"
PID: ISR4451-X/K9      , VID: V01  , SN: FOC17042FN5

NAME: "module F0", DESCR: "Cisco ISR4451 Forwarding Processor"
PID: ISR4451-X/K9      , VID:      , SN:

**Comment by xiaoxinz-cisco** [comment]
Hello @vskyman 

This issue is the same as #106 

We fixed the issue and genie package **20.2.1b4** has been released with the fix.
Could you please run the following command and try again to see if it works?

**pip install genie.libs.parser --upgrade --pre**

Please try and let's know if there is an issue.

Thanks,
Irene
