### ISSUE TITLE
Failed to parse NXOS ACL with "show access-lists"

### ISSUE THREAD

**Issue by ogratwicklcs** [CiscoTestAutomation/genieparser#115]
Hi,

I am attempting to use [parse genie](https://github.com/clay584/parse_genie) with Ansible Tower to run "show access-lists {{ acl_name }}" but get the message below for this specific command.  

FAILED! => {"msg": "parse_genie: local variable 'acl_dict' referenced before assignment - Failed to parse command output."}

- name: show acl list
  nxos_command:
    commands: 
      - show ip access-lists {{ acl_name }}
  register: acl_output

- name: run command for show
  debug:
    msg: "{{ acl_output['stdout'][0] | parse_genie(command='show ip access-lists IPV4 ACL 1', os='nxos') }}"
  delegate_to: localhost
  register: genie_acl_output

**Comment by xiaoxinz-cisco** [comment]
Hi @ogratwicklcs ,

Could you please send us the device output regarding the show command that causes the error?

Thanks,
Irene

**Comment by ogratwicklcs** [comment]
Ansible stdout variable the values are below:
IPV4 ACL 1\n        10 remark NTP Access\n        20 permit ip 10.1.1.39/32 any \n        30 permit ip 165.231.11.23/32 any

Output from Nexus switch
IPV4 ACL 1
        10 remark NTP Access
        20 permit ip 10.1.1.39/32 any
        30 permit ip 165.231.11.23/32 any

**Comment by xiaoxinz-cisco** [comment]
Hello @ogratwicklcs 
We fixed the issue and genie package **20.2.1b6** has been released with the fix.
Could you please run the following command and try again to see if it works?

**pip install genie.libs.parser --upgrade --pre**

Please try and let's know if there is an issue.

Thanks,
Irene
