### ISSUE TITLE
parse('show version') results in SyntaxError exception

### ISSUE THREAD

**Issue by fwclements** [CiscoTestAutomation/genieparser#117]
Running through some coding exercises and found a syntax error in the module: genie/libs/parser/iosxe/show_lldp.py on line 490.  Here's the diff for a fix:

```
--- genie/libs/parser/iosxe/show_lldp.py.orig	2020-04-17 10:05:24.228531837 -0400
+++ genie/libs/parser/iosxe/show_lldp.py	2020-04-17 10:06:09.832337131 -0400
@@ -487,7 +487,7 @@
             # Serial number: FCH1610A5S5
             m = med_p9.match(line)
             if m:
-                med_dict['serial_number']: m.groupdict()['serial_number']
+                med_dict['serial_number'] = m.groupdict()['serial_number']
                 continue

         return ret_dict
```

Reproduced by:
```
from genie.testbed import load
from genie.conf.base import Device

testbed = load('yaml/default.yml')
dev = Device('myDevice',
                 os='iosxr', type='router',
                 custom={'abstraction': {'order': ['os']}},
                 connections={'default': {'ip': '127.0.0.1', 'protocol': 'ssh'}})
dev.connect(log_stdout=False)
dev.parse('show version')
```

Genie module version: 20.2
pyATS module version: 20.2.1

pip freeze from venv in testing:
aiohttp==2.3.10
async-timeout==2.0.1
backcall==0.1.0
certifi==2020.4.5.1
chardet==3.0.4
decorator==4.4.2
dill==0.3.1.1
distro==1.5.0
genie==20.2
genie.libs.conf==20.2
genie.libs.filetransferutils==20.2
genie.libs.ops==20.2
genie.libs.parser==20.2
genie.libs.sdk==20.2.2
idna==2.9
idna-ssl==1.1.0
ipython==7.9.0
ipython-genutils==0.2.0
jedi==0.16.0
Jinja2==2.11.1
jsonpickle==1.3
junit-xml==1.9
MarkupSafe==1.1.1
multidict==4.7.5
netaddr==0.7.19
parso==0.6.2
pathspec==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
prettytable==0.7.2
prompt-toolkit==2.0.10
psutil==5.7.0
ptyprocess==0.6.0
pyats==20.2.1
pyats.aereport==20.2
pyats.aetest==20.2
pyats.async==20.2
pyats.connections==20.2
pyats.datastructures==20.2
pyats.easypy==20.2
pyats.kleenex==20.2
pyats.log==20.2
pyats.reporter==20.2.2
pyats.results==20.2
pyats.tcl==20.2
pyats.topology==20.2
pyats.utils==20.2
Pygments==2.6.1
PyYAML==5.3.1
requests==2.23.0
six==1.14.0
tqdm==4.45.0
traitlets==4.3.3
unicon==20.2
unicon.plugins==20.2
urllib3==1.25.8
wcwidth==0.1.9
xlrd==1.2.0
XlsxWriter==1.2.8
xlwt==1.3.0
xmltodict==0.12.0
yamllint==1.21.0
yarl==1.4.2

**Comment by xiaoxinz-cisco** [comment]
Hi @fwclements ,

Thanks for pointing out. We've already fixed this issue in a beta package. Here is the latest code 
https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/iosxe/show_lldp.py#L491

Could you please update the genieparser and test it?

***pip install genie.libs.parser --upgrade --pre**

Thanks,
Irene

**Comment by fwclements** [comment]
This worked, thanks!
