### ISSUE TITLE
NX-OS Interface MTU not parsed

### ISSUE THREAD

**Issue by dan-md** [CiscoTestAutomation/genieparser#120]
Hello team,

While using module "interface" for NX-OS N9K, MTU of interface is not parsed/extracted.

Ethernet1/20 is up
admin state is up, Dedicated Interface
  Hardware: 100/1000/10000/25000 Ethernet, address: 00ee.ab29.7c51 (bia 00ee.ab29.7c65)
  Internet Address is 192.168.0.1/24
  **MTU** 600 bytes, BW 10000000 Kbit , DLY 10 usec

Parsed:

 "Ethernet1/20": {
      "counters": {
        "in_broadcast_pkts": 6,
        "in_crc_errors": 0,
        "in_errors": 0,
        "in_mac_pause_frames": 0,
        "in_multicast_pkts": 207864,
        "in_octets": 58149250,
        "in_pkts": 211587,
        "in_unicast_pkts": 3717,
        "in_unknown_protos": 0,
        "last_clear": "never",
        "out_broadcast_pkts": 6,
        "out_discard": 0,
        "out_errors": 0,
        "out_mac_pause_frames": 0,
        "out_multicast_pkts": 207794,
        "out_octets": 55372975,
        "out_pkts": 211519,
        "out_unicast_pkts": 3719,
        "rate": {
          "in_rate": 104,
          "in_rate_pkts": 0,
          "load_interval": 300,
          "out_rate": 104,
          "out_rate_pkts": 0
        }
      },
      "duplex_mode": "full",
      "enabled": true,
      "encapsulation": {
        "encapsulation": "arpa"
      },
      "flow_control": {
        "receive": false,
        "send": false
      },
      "ipv4": {
        "192.168.0.1/24": {
          "ip": "192.168.0.1",
          "prefix_length": "24"
        }
      },
      "mac_address": "00ee.ab29.7c51",
      "medium": "broadcast",
      "oper_status": "up",
      "phys_address": "00ee.ab29.7c65",
      "port_channel": {
        "port_channel_member": false
      },
      "port_speed": "10",
      "type": "100/1000/10000/25000 Ethernet",
      "vrf": "default"
    },

**Comment by xiaoxinz-cisco** [comment]
Hi @dan-md ,

Thank you for reporting. We will look into the issue and get back to you.

Thanks,
Irene

**Comment by xiaoxinz-cisco** [comment]
Hi @dan-md ,

We found the issue was caused by a regular expression pattern:
```
        # MTU 1600 bytes, BW 768 Kbit, DLY 3330 usec
        # MTU 1500 bytes, BW 1000000 Kbit, DLY 10 usec,
        # MTU 1500 bytes, BW 1000000 Kbit
        p6 = re.compile(r'^MTU *(?P<mtu>[0-9]+) *bytes, *BW'
                            ' *(?P<bandwidth>[0-9]+) *Kbit(, *DLY'
                            ' *(?P<delay>[0-9]+) *usec)?,?$') 
```
It means *p6* matches the sample outputs like those in the comments. You might notice *p6* does not allow space between `Kbit` and `,`, so it misses your output: `MTU 600 bytes, BW 10000000 Kbit , DLY 10 usec`, which has space between `Kbit` and `,`.

A tiny update should work:
```
        p6 = re.compile(r'^MTU *(?P<mtu>[0-9]+) *bytes, *BW'
                            ' *(?P<bandwidth>[0-9]+) *Kbit( *, *DLY'
                            ' *(?P<delay>[0-9]+) *usec)?,?$') 
```
We will include this fix in the next release and will let you know. If you meet similar issues in the future, and you're comfortable with Python and regular expression, we encourage you to create a pull request here, our team will review and merge your contribution! :D 

Thanks,
Irene

Reference: https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/nxos/show_interface.py#L250

**Comment by dan-md** [comment]
Great Irene and thank you a lot!

>> If you meet similar issues in the future, and you're comfortable with
Python and regular expression, we encourage you to create a pull request
here, our team will review and merge your contribution! :D
*Noted!*

Kind regards,
Dan

**Comment by xiaoxinz-cisco** [comment]
Hi @dan-md ,

We released this fix:
https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/nxos/show_interface.py#L251

Could you please upgrade using the following command and see if it works?
- `pip install --upgrade pyats[full]`

Let me know if there is any question.

Thanks,
Irene
