### ISSUE TITLE
Could not find parser for 'my_parser'

### ISSUE THREAD

**Issue by clickheretoday** [CiscoTestAutomation/genieparser#127]
Hi there,

I wrote a simple parser that parses the output of linux command 'route'. I run my parser like this:

from genie.libs.parser.linux.route import Route

genie_testbed = Genie.init(testbed='/home/clickheretoday/devPyATS/pyats/testbed.yaml') 
dev = genie_testbed.devices['linux-1'] 
dev.connect() 
parser = Route(dev).parse()

and get the right result.

I wonder, is there any chance to use the parser as in the example below, instead of using the import statement and instantiate the object?

If I run the parser as mentioned in examples:

genie_testbed = Genie.init(testbed='/home/clickheretoday/devPyATS/pyats/testbed.yaml') 
dev = genie_testbed.devices['linux-1'] 
dev.connect() 
dev.parse('route')

I get: 
Exception: Could not find parser for 'route'

**Comment by xiaoxinz-cisco** [comment]
Hi @clickheretoday ,

Did you run `make json` after creating the new parser?

[Readme](https://github.com/CiscoTestAutomation/genieparser/blob/master/README.md) outlines the necessary steps while creating a new parser.

Let me know if there is any question.

Thanks,
Irene

**Comment by clickheretoday** [comment]
Thanks a lot. It works!

All the best
