### ISSUE TITLE
Error to parsing "show interfaces switchport" on C6807-XL

### ISSUE THREAD

**Issue by gerardocastaldo** [CiscoTestAutomation/genieparser#128]
Hi at all,
I experienced problem for the parsing of the "show interfaces switchport" for the C6807-XL device.

Below, the show version and the exception. 

BS-SEAT--1-1#sh version
Cisco IOS Software, s6t64 Software (s6t64-IPSERVICESK9_NPE-M), Version 15.5(1)SY4, RELEASE SOFTWARE (fc4)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2019 by Cisco Systems, Inc.
Compiled Mon 02-Sep-19 08:47 by prod_rel_team

ROM: System Bootstrap, Version 15.3(04r)SYS, RELEASE SOFTWARE

BS-SEAT--1-1 uptime is 23 weeks, 21 hours, 39 minutes
Uptime for this control processor is 23 weeks, 21 hours, 32 minutes
System returned to ROM by power-on
System restarted at 15:42:36 CET Mon Nov 18 2019
System image file is "bootdisk:s6t64-ipservicesk9_npe-mz.SPA.155-1.SY4.bin"
Last reload reason: power-on

This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

Cisco C6807-XL ( Intel(R) Core(TM) i3-3227U CPU @ 2.50GHz ) processor (revision ) with 2879470K/524288K bytes of memory.
Processor board ID FGE23105KD4
Processor signature 0xA9060300
Last reset from power-on
63 Virtual Ethernet interfaces
97 Gigabit Ethernet interfaces
144 Ten Gigabit Ethernet interfaces
4 Forty Gigabit Ethernet interfaces
3735536K bytes of USB Flash bootdisk (Read/Write)

Configuration register is 0x2102

Exception

Issue with the parser show interfaces switchport

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 303, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 548, in genie.conf.base.device.Device.parse
  File "src/genie/metaparser/_metaparser.py", line 271, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/castage/projects/venv/lib64/python3.6/site-packages/genie/libs/parser/iosxe/show_interface.py", line 1661, in cli
    ret_dict[intf]['trunk_vlans'] += m.groupdict()['trunk_vlans'].lower()
KeyError: 'trunk_vlans'

Thank you
Gerardo

**Comment by xiaoxinz-cisco** [comment]
Hi Gerardo, 

From the exception:

> File "/home/castage/projects/venv/lib64/python3.6/site-packages/genie/libs/parser/iosxe/show_interface.py", line 1661, in cli
> ret_dict[intf]['trunk_vlans'] += m.groupdict()['trunk_vlans'].lower()

seems the error occurs in `iosxe/show_interface.py`, I ran the `show version` using your output and didn't see the error.

May I know the reason that you said `show interfaces switchport` causes the error? (by the way, it should be `show interface switchport` with no `s` after `interface`)

Thanks,
Irene

**Comment by gerardocastaldo** [comment]
Hi Irene,
I attached the outputs file. 

[show-interfaces-switchport_console.txt](https://github.com/CiscoTestAutomation/genieparser/files/4550591/show-interfaces-switchport_console.txt)

[show-interfaces-switchport_exception.txt](https://github.com/CiscoTestAutomation/genieparser/files/4550592/show-interfaces-switchport_exception.txt)

**Comment by xiaoxinz-cisco** [comment]
Hello @gerardocastaldo 

We fixed the issue and genie package **v20.4.1b2** has been released with the fix.
Could you please run the following command and try again to see if it works?

- **pip install genie.libs.parser --upgrade --pre**

Please try and let's know if there is an issue.

Thanks,
Irene

**Comment by gerardocastaldo** [comment]
Hello Irene, sorry for delay. I confirm you that now it works well.

Thanks
Gerardo
