### ISSUE TITLE
Issue parser the "show inventory" on C9200

### ISSUE THREAD

**Issue by gerardocastaldo** [CiscoTestAutomation/genieparser#129]
Hi at all,

I experienced issue to parsing the command "show inventory" on C9200.

Below the content of the output files. 

(venv) [castage@prdnetbastian genie_inventory]$ more DS-SEAT--1-5_*
::::::::::::::
DS-SEAT--1-5_show-inventory_console.txt
::::::::::::::
+++ DS-SEAT--1-5: executing command 'show inventory' +++
show inventory
NAME: "c93xxL Stack", DESCR: "c93xxL Stack"
PID: C9300L-48T-4X     , VID: V01  , SN: FOC2329L07F

NAME: "Switch 1", DESCR: "C9300L-48T-4X"
PID: C9300L-48T-4X     , VID: V01  , SN: FOC2329L06L

NAME: "StackPort1/1", DESCR: "StackPort1/1"
PID: STACK-T3-1M       , VID: V01  , SN: LCC2311GH0V

NAME: "StackPort1/2", DESCR: "StackPort1/2"
PID: STACK-T3-3M       , VID: V01  , SN: LCC2310G51V

NAME: "StackAdapter1/1", DESCR: "StackAdapter1/1"
PID: C9300L-STACK      , VID: V01  , SN: FOC231966ZU

NAME: "StackAdapter1/2", DESCR: "StackAdapter1/2"
PID: C9300L-STACK      , VID: V01  , SN: FOC231965M4

NAME: "Switch 1 - Power Supply A", DESCR: "Switch 1 - Power Supply A"
PID: PWR-C1-350WAC-P   , VID: V01  , SN: DCC2327B0X6

NAME: "Switch 1 - Power Supply B", DESCR: "Switch 1 - Power Supply B"
PID: PWR-C1-350WAC-P   , VID: V01  , SN: DCC2327B0X8

NAME: "Te1/1/1", DESCR: "SFP-10GBase-SR"
PID: SFP-10G-SR          , VID: V03  , SN: AVD2323976E

NAME: "Switch 2", DESCR: "C9300L-48T-4X"
PID: C9300L-48T-4X     , VID: V01  , SN: FOC2329L018

NAME: "StackPort2/1", DESCR: "StackPort2/1"
PID: STACK-T3-3M       , VID: V01  , SN: LCC2311GU07

NAME: "StackPort2/2", DESCR: "StackPort2/2"
PID: STACK-T3-1M       , VID: V01  , SN: LCC2311GH0V

NAME: "StackAdapter2/1", DESCR: "StackAdapter2/1"
PID: C9300L-STACK      , VID: V01  , SN: FOC231965LB

NAME: "StackAdapter2/2", DESCR: "StackAdapter2/2"
PID: C9300L-STACK      , VID: V01  , SN: FOC231965L1

NAME: "Switch 2 - Power Supply A", DESCR: "Switch 2 - Power Supply A"
PID: PWR-C1-350WAC-P   , VID: V01  , SN: DCC2327B0YS

NAME: "Switch 2 - Power Supply B", DESCR: "Switch 2 - Power Supply B"
PID: PWR-C1-350WAC-P   , VID: V01  , SN: DCC2327B0Z2

NAME: "Te2/1/1", DESCR: "SFP-10GBase-SR"
PID: SFP-10G-SR          , VID: V03  , SN: AVD232298UX

NAME: "Te2/1/2", DESCR: "SFP-10GBase-SR"
PID: SFP-10G-SR          , VID: V03  , SN: AVD232298Y1

NAME: "Switch 3", DESCR: "C9300L-48T-4X"
PID: C9300L-48T-4X     , VID: V01  , SN: FOC2329L060

NAME: "StackPort3/1", DESCR: "StackPort3/1"
PID: STACK-T3-3M       , VID: V01  , SN: LCC2311GU07

NAME: "StackPort3/2", DESCR: "StackPort3/2"
PID: STACK-T3-1M       , VID: V01  , SN: LCC2311GT00

NAME: "StackAdapter3/1", DESCR: "StackAdapter3/1"
PID: C9300L-STACK      , VID: V01  , SN: FOC231965L4

NAME: "StackAdapter3/2", DESCR: "StackAdapter3/2"
PID: C9300L-STACK      , VID: V01  , SN: FOC231965LK

NAME: "Switch 3 - Power Supply A", DESCR: "Switch 3 - Power Supply A"
PID: PWR-C1-350WAC-P   , VID: V01  , SN: DCC2327B12V

NAME: "Switch 3 - Power Supply B", DESCR: "Switch 3 - Power Supply B"
PID: PWR-C1-350WAC-P   , VID: V01  , SN: DCC2327B0YC

NAME: "Te3/1/1", DESCR: "SFP-10GBase-SR"
PID: SFP-10G-SR          , VID: V03  , SN: AVD232298Y0

NAME: "Te3/1/2", DESCR: "SFP-10GBase-SR"
PID: SFP-10G-SR          , VID: V03  , SN: AVD232298V6

NAME: "Switch 4", DESCR: "C9300L-48T-4X"
PID: C9300L-48T-4X     , VID: V01  , SN: FOC2329L07F

NAME: "StackPort4/1", DESCR: "StackPort4/1"
PID: STACK-T3-1M       , VID: V01  , SN: LCC2311GT00

NAME: "StackPort4/2", DESCR: "StackPort4/2"
PID: STACK-T3-3M       , VID: V01  , SN: LCC2310G51V

NAME: "StackAdapter4/1", DESCR: "StackAdapter4/1"
PID: C9300L-STACK      , VID: V01  , SN: FOC231965XE

NAME: "StackAdapter4/2", DESCR: "StackAdapter4/2"
PID: C9300L-STACK      , VID: V01  , SN: FOC231966MB

NAME: "Switch 4 - Power Supply A", DESCR: "Switch 4 - Power Supply A"
PID: PWR-C1-350WAC-P   , VID: V01  , SN: DCC2327B0YH

NAME: "Te4/1/1", DESCR: "SFP-10GBase-SR"
PID: SFP-10G-SR          , VID: V03  , SN: AVD232292HX

NAME: "Te4/1/2", DESCR: "SFP-10GBase-SR"
PID: SFP-10G-SR          , VID: V03  , SN: AVD2322939N

DS-SEAT--1-5#
::::::::::::::
DS-SEAT--1-5_show-inventory_exception.txt
::::::::::::::
Issue with the parser show inventory

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 303, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 548, in genie.conf.base.device.Device.parse
  File "src/genie/metaparser/_metaparser.py", line 271, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/castage/projects/venv/lib64/python3.6/site-packages/genie/libs/parser/iosxe/show_platform.py", line 1938, in cli
    subslot_dict = rp_dict.setdefault('subslot', {}).\
UnboundLocalError: local variable 'rp_dict' referenced before assignment

**Comment by xiaoxinz-cisco** [comment]
Hi @gerardocastaldo ,

We have a simiilar unit test for "show inventory" on C9300: https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/iosxe/tests/c9300/test_show_platform.py#L19

Could you please check the versions of the packages? 

- `pip list | grep genie`

They should be v20.4:
```
[genie] server:117> pip list | grep genie
genie                         20.4.1      
genie.libs.clean              20.4        
genie.libs.conf               20.4        
genie.libs.filetransferutils  20.4        
genie.libs.ops                20.4        
genie.libs.parser             20.4                    
genie.libs.robot              20.2         
genie.libs.sdk                20.4           
genie.telemetry               20.2        
genie.trafficgen              20.2  
```

If you don't use the latest version, please update packages using:

- pip install --upgrade pyats[full]

Let me know if you have any questions. 

Thanks,
Irene

**Comment by gerardocastaldo** [comment]
Hi @xiaoxinz-cisco, 

I updated the pyats modules. Previously, my version was the 20.2.

Now

```
> (venv) [castage@prdnetbastian genie_inventory]$ pip list | grep genie
> genie                        20.4.1
> genie.libs.clean             20.4
> genie.libs.conf              20.4
> genie.libs.filetransferutils 20.4
> genie.libs.ops               20.4
> genie.libs.parser            20.4
> genie.libs.robot             20.4
> genie.libs.sdk               20.4
> genie.telemetry              20.4
> genie.trafficgen             20.4
```

I continue to have the same error. I attached the output files for three different devices.

[genie_inventory.zip](https://github.com/CiscoTestAutomation/genieparser/files/4580980/genie_inventory.zip)


Thank you,
Gerardo

**Comment by xiaoxinz-cisco** [comment]
Hi @gerardocastaldo ,

Do you use Anisible, if so, could you please check if you passed `platform = 'c9300'` in the testbed?

Let me know if it works.

Thanks,
Irene

**Comment by gerardocastaldo** [comment]
Hi @xiaoxinz-cisco ,

I am using pyats command line. I added the platform field in the testbed but the output is always the same.
```

(venv) [castage@prdnetbastian EFSA]$ pyats parse "show inventory" --testbed-file my_testbed.yaml --output inventory --devices DS-SEAT--1-5
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.07s/it]
+==============================================================================+
| Genie Parse Summary for DS-SEAT--1-5                                         |
+==============================================================================+
|  Connected to DS-SEAT--1-5                                                   |
|  -  Log: inventory/connection_DS-SEAT--1-5.txt                               |
|------------------------------------------------------------------------------|
|  Could not parse 'show inventory'                                            |
|  -  Exception:      inventory/DS-SEAT--1-5_show-inventory_exception.txt      |
|  -  Device Console: inventory/DS-SEAT--1-5_show-inventory_console.txt        |
|------------------------------------------------------------------------------|
```

The testbed for the DS-SEAT--1-5 is

```
  DS-SEAT--1-5:
    connections:
      cli:
        ip: '<ip address>'
        protocol: ssh
    credentials:
      default:
        password: '<password>'
        username: '<username>'
      enable:
        password: ''
    os: iosxe
    type: iosxe
    platform: 'c9300'
```

Is it correct ?

Thanks
Gerardo

**Comment by xiaoxinz-cisco** [comment]
Hi @gerardocastaldo ,

Can you try the following testbed? I added a `custom` section:

```
  DS-SEAT--1-5:
    connections:
      cli:
        ip: '<ip address>'
        protocol: ssh
    credentials:
      default:
        password: '<password>'
        username: '<username>'
      enable:
        password: ''
    custom:
      abstraction:
        order:
        - os
        - platform
    os: iosxe
    type: iosxe
    platform: 'c9300'
```

Let me know if it works.

Thanks,
Irene

**Comment by gerardocastaldo** [comment]
Hi @xiaoxinz-cisco ,

adding to the testbed the custom field it's ok. 


```
(venv) [castage@prdnetbastian EFSA]$ pyats parse "show inventory" --testbed-file my_testbed.yaml --output genie_inventory --devices DS-SEAT--1-5
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.10s/it]
+==============================================================================+
| Genie Parse Summary for DS-SEAT--1-5                                         |
+==============================================================================+
|  Connected to DS-SEAT--1-5                                                   |
|  -  Log: genie_inventory/connection_DS-SEAT--1-5.txt                         |
|------------------------------------------------------------------------------|
|  Parsed command 'show inventory'                                             |
|  -  Parsed structure: genie_inventory/DS-SEAT--1-5_show-inventory_parsed.txt |
|  -  Device Console:   genie_inventory/DS-SEAT--1-5_show-inventory_console.txt |
|------------------------------------------------------------------------------|

```

Thanks
Gerardo

**Comment by ecchong** [comment]
> Hi @gerardocastaldo ,
> 
> Do you use Anisible, if so, could you please check if you passed `platform = 'c9300'` in the testbed?
> 
> Let me know if it works.
> 
> Thanks,
> Irene

Hi, 

Just stumbled upon this old post with the similar error message when running via Ansible.  How can I specify the `platform = 'c9300'`?  As a host variables?

Thanks
