### ISSUE TITLE
Issue with 'show ip route vrf' parser

### ISSUE THREAD

**Issue by leoanez** [CiscoTestAutomation/genieparser#130]
Hi,

The parser for 'show ip route vrf' is having an issue if the name of the vrf have a '-' character. If the name have a '-' it just set the vrf to 'default'. For example:

If I parse the command: `show ip route vrf TEST-intra`
The result is this (I will omit most of the output cause is very long, the interesting part is at the beginning.
`{'vrf': {'default': {'address_family': {'ipv4': {'routes': {'0.0.0.0/0'......}`

**Comment by leoanez** [comment]
Hey xiaoxinz,

I think the modification that needs to be done is this: Just add '?-' to the regex for VRF in line 264:

`p1 = re.compile(r'^Routing Table: +(?P<vrf>[\w?-]+)$')`

Should I open a pull request?

**Comment by xiaoxinz-cisco** [comment]
Hi @leoanez ,

Sounds great! Yes, you could open a pull request, and don't forget to `python -m unittest` and update the [changelog](https://github.com/CiscoTestAutomation/genieparser/blob/master/changelog/undistributed.rst)

We'll review your pull request and merge it.

Thanks,
Irene

**Comment by xiaoxinz-cisco** [comment]
just for record purpose: This issue is resolved by PR #131
