### ISSUE TITLE
NXOS show running-config interface {interface} missing fields

### ISSUE THREAD

**Issue by alurmtr** [CiscoTestAutomation/genieparser#133]
Can these two fields be added to the parsed output?
interface description
interface native vlan

Also the mode=access and vlan is missing when configured for switchport access. 

TASK [] ****************************************************************************************************
ok: [deviceA] => {
    "output_run_int_output['stdout'][0]": "!Command: show running-config interface Eth1/4
    \n!Time: ...\n\nversion ...\n
    \ninterface Ethernet1/4
    \n  description DeviceA-description
    \n  switchport access vlan x
    \n  speed 1000
    \n  duplex full"
}

TASK [Set Fact Genie] ************************************************************************************************
ok: [deviceA]

TASK [Debug] ************************************************************************************************
ok: [deviceA] => {
    "output_sh_run_int": {
        "interface": {
            "Ethernet1/4": {}
        }
    }
}

**Comment by xiaoxinz-cisco** [comment]
Hi @alurmtr ,

We fixed the issue and genie package **v20.4.1b1** has been released with the fix.

We added the missing keys into the schema: https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/nxos/show_interface.py#L2887

If you're interested in developing parsers, here is our guide: 
https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/writeparser/writeparser.html#

Could you please run the following command and try again to see if it works?

- `pip install genie.libs.parser --upgrade --pre`

Please try and let's know if there is an issue.

Thanks,
Irene

**Comment by alurmtr** [comment]
Thanks for the prompt response. 

May i also suggest adding the following:

           # switchport trunk native vlan xxx
            p10_2 = re.compile(r'^switchport +trunk +native +vlan +(?P<native_vlan>\S+)$')
            m = p10_2.match(line)
            if m:
                group = m.groupdict()
                interface_dict.update({'native_vlan': group['native_vlan']})
                continue

And for your block  "# switchport access vlan x",  specify the mode as below
            p10_1 = re.compile(r'^switchport +access +vlan +(?P<access_vlan>\S+)$')
            m = p10_1.match(line)
            if m:
                group = m.groupdict()
                interface_dict.update({'access_vlan': group['access_vlan']})
                **interface_dict.update({'switchport_mode': 'access'})**
                continue

**Comment by xiaoxinz-cisco** [comment]
Hi @alurmtr ,

Of course, could you please create a pull request that involves this new regex pattern?

Checklist for creating a PR:
- update the parser class
- add a unit test (please use existing unit tests as references:
https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/nxos/tests/test_show_interface.py#L6441)
- update changelog(this file: 
https://github.com/CiscoTestAutomation/genieparser/blob/master/changelog/undistributed.rst)
- under `genieparser/tests` run `python -m unittest` ,and paste the result into the thread

We'll review your code there.

Thanks,
Irene

**Comment by xiaoxinz-cisco** [comment]
Hi @alurmtr ,

Is there any update? 

Thanks,
Irene

**Comment by alurmtr** [comment]
Hi Irene

Last week was pretty busy. i will test it out this week and provide feedback

**Comment by xiaoxinz-cisco** [comment]
Hi @alurmtr ,

We're closing this issue since not having heard from you for some time, would you mind create a new issue if needed?

Thanks,
Irene

**Comment by alurmtr** [comment]
Hi Irene.
Ok, i do have some code for a pull request. I will create a new issue to keep track of it.
Al
