### ISSUE TITLE
Nexus "show interface" missing interfaces with multiple types of down conditions

### ISSUE THREAD

**Issue by andywhitaker** [CiscoTestAutomation/genieparser#137]
On the Cisco Nexus parser for show_interface I found the p1 regex pattern not matching multiple interfaces on some devices. Interfaces with the following errors I found are missed:

Ethernet2/5 is down (SFP not inserted)
Ethernet1/6 is down (linkFlapErrDisabled)
Ethernet5/5 is down (suspended(no LACP PDUs))

I modified the regex to be the following and it works well on my side:
```
        p1 = re.compile(r'^(?P<interface>\S+)\s*is\s*(?P<link_state>(down|up))?'
                        r'(administratively\s+(?P<admin_1>(down|up)))?\s*'
                        r'(\(Administratively\s*(?P<admin_2>(down|up))\))?'
                        r'(\(VLAN\/BD\s+is+\s+(down|up)\))?'
                        r'(,\s*line\s+protocol\s+is\s+(?P<line_protocol>\w+))?'
                        r'(,\s+autostate\s+(?P<autostate>\S+))?'
                        r'(\(Link\s+not\s+connected\))?'
                        r'(\(SFP\s+not\s+inserted\))?'
                        r'(\(suspended\(.*\)\))?'
                        r'(\(\S+ErrDisabled\))?'
                        r'(\(.*ACK.*\))?$')
```

The above was a quick edit but I think ideally it would be nice to have the full reason a suspended or ErrDisabled interface is down captured and reported in the output.

Just wanted to pass this on. Thanks!!

**Comment by xiaoxinz-cisco** [comment]
Hi @andywhitaker ,

We appreciate your contribution! 

Could you please open a pull request that includes this regex fix?

Then, please run `python -m unittest` under `genieparser/tests` directory, and paste the result into the PR's thread.

Last step: please update the change log in https://github.com/CiscoTestAutomation/genieparser/blob/master/changelog/undistributed.rst

We will review your code there!

Thanks,
Irene

**Comment by xiaoxinz-cisco** [comment]
Hi @andywhitaker ,

We received your PR #140 

Thanks,
Irene
