### ISSUE TITLE
Genie Learn KeyError: 'vrf' on IOSXR

### ISSUE THREAD

**Issue by pwoconnor** [CiscoTestAutomation/genieparser#15]
Receiving KeyError when using Genie learn bgp. Genie output files will be sent to pyats-support-ext@cisco.com

**Comment by tahigash** [comment]
Hi @pwoconnor 

Thank you for reporting the issue and provided the output.
We fixed the parser and created beta package with fix.

Could you please verify if it works on your environment? 19.4.1b0 will be installed.
pip install genie.libs.parser --upgrade --pre

Regards,

**Comment by tahigash** [comment]
fix has been confirmed
