### ISSUE TITLE
ip_extended_interarea referenced before assignment

### ISSUE THREAD

**Issue by devroute11** [CiscoTestAutomation/genieparser#159]
https://github.com/CiscoTestAutomation/genieparser/blob/9d4583ea7a8e084cc1bc42af9991a4fe79d9aafb/src/genie/libs/parser/iosxr/show_isis.py#L3937

Getting error hear when trying to learn isis on fresh install:

`Issue while building the feature

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 343, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/usr/local/lib/python3.6/site-packages/genie/libs/ops/isis/iosxr/isis.py", line 752, in learn
    self.make(final_call=True)
  File "/usr/local/lib64/python3.6/site-packages/genie/ops/base/base.py", line 101, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 312, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 418, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 271, in genie.metaparser._metaparser.MetaParser.parse
  File "/usr/local/lib/python3.6/site-packages/genie/libs/parser/iosxr/show_isis.py", line 3937, in cli
    .setdefault(ip_extended_interarea, {})\
UnboundLocalError: local variable 'ip_extended_interarea' referenced before assignment`

**Comment by devroute11** [comment]
Looks like this is happening because it's a IPv6 unicast deployment only, there is no IPv4 unicast so variable isn't set on r15 match.

```
            # Metric: 40         IP-Extended-Interarea 10.7.8.0/24
            result = r15.match(line)
            if result:
                group = result.groupdict()
                metric = int(group['metric'])
                ip_extended_interarea = group['ip_interarea']
```

**Comment by LenzDong** [comment]
Hi, 
Could you provide the device's sample output to check?
Thanks

**Comment by devroute11** [comment]
Here is console output section with some routes removed to keep it short.

```
+++ lab-crs-02: executing command 'show isis database detail' +++
show isis database detail
^MSat May 23 12:25:28.168 CDT

IS-IS 100 (Level-1) Link State Database
LSPID                 LSP Seq Num  LSP Checksum  LSP Holdtime  ATT/P/OL
lab-crs-02.00-00    * 0x00000d0e   0x282a        592             0/0/0
  Area Address:   49.0000
  NLPID:          0x8e
  Hostname:       lab-crs-02
  IPv6 Address:   10:1::2
  Metric: 0          MT (IPv6 Unicast) IPv6 10:1::2/128
  Metric: 20         MT (IPv6 Unicast) IPv6-Interarea 20:1:2::2/128
  Metric: 20         MT (IPv6 Unicast) IPv6-Interarea 20:1:2::1/128
  Metric: 10         MT (IPv6 Unicast) IPv6-Interarea 20:1::2/128
  Metric: 65023      MT (IPv6 Unicast) IPv6-Interarea 90:1::2/128
  Metric: 21         MT (IPv6 Unicast) IPv6-Interarea 30:1::15/128
  Metric: 65031      MT (IPv6 Unicast) IPv6-Interarea 90:1::1/128
  Metric: 65021      MT (IPv6 Unicast) IPv6-Interarea 50:1::2/128
  Metric: 31         MT (IPv6 Unicast) IPv6-Interarea 30:1::16/128
  MT:             IPv6 Unicast                                 0/0/0
  Metric: 5          MT (IPv6 Unicast) IPv6-Interarea 10:1::1/128
  Metric: 5          MT (IPv6 Unicast) IPv6-Interarea ::/0
  Metric: 20         MT (IPv6 Unicast) IPv6-Interarea 10:1::2:3/128
  Metric: 10         MT (IPv6 Unicast) IPv6-Interarea 10:1::2:1/128
  Metric: 11         MT (IPv6 Unicast) IPv6-Interarea 20:1::1/128
  Metric: 130000     MT (IPv6 Unicast) IPv6-Interarea 40:2::11/128
  Metric: 65010      MT (IPv6 Unicast) IPv6-Interarea 40:2::10/128
  Metric: 65000      MT (IPv6 Unicast) IPv6-Interarea 40:1::2/128
  Metric: 5          MT (IPv6 Unicast) IPv6-Interarea 150::/128
  Metric: 65020      MT (IPv6 Unicast) IPv6-Interarea 40:1::1/128
  Metric: 20         MT (IPv6 Unicast) IPv6-Interarea 2::2b/128
  Metric: 20         MT (IPv6 Unicast) IPv6-Interarea 2::186/128
  Metric: 20         MT (IPv6 Unicast) IPv6-Interarea 2::185/128

 Total Level-1 LSP count: 28     Local Level-1 LSP count: 28
```

**Comment by LenzDong** [comment]
Thanks for the sample output, I will fix it and let you know when it's ready

**Comment by LenzDong** [comment]
Hi,

The parser fix is released. Please upgrade genieparser to the latest v20.6

Thanks
