### ISSUE TITLE
Add fields to NXOS show running-config interface {interface} 

### ISSUE THREAD

**Issue by alurmtr** [CiscoTestAutomation/genieparser#161]
Feature request to add fields:

trunk native vlan
vpc x
switchport_mode: access

Also the description field must handle string with spaces.

    interface port-channel5
      description Port Channel Config Tst
      switchport mode trunk
      switchport trunk native vlan 2253
      switchport trunk allowed vlan 2253
      speed 10000
      vpc 5

**Comment by alurmtr** [comment]
pull request #162  created

**Comment by karmoham** [comment]
This request has been already acknowledged by the user in https://github.com/CiscoTestAutomation/genieparser/pull/162 

Closing the case!
