### ISSUE TITLE
IOS XR parser for show controllers optics does not support QSFP28 100G LR4

### ISSUE THREAD

**Issue by Neiby** [CiscoTestAutomation/genieparser#165]
I get correctly parsed JSON for our QSFP+ 4x10G optics, but just one long unparsed string for QSFP28 100G LR4. Here is an example for reference:

"Thu Jun  4 17:08:21.749 UTC\n\n Controller State: Up \n\n Transport Admin State: In Service \n\n Laser State: On \n\n LED State: Green \n \n Optics Status \n\n\t Optics Type:  QSFP28 100G LR4\n\t Wavelength = 1302.00 nm \n\n\t Alarm Status:\n\t -------------\n\t Detected Alarms: None\n\n\n\t LOS/LOL/Fault Status:\n\n\n\t Performance Monitoring: Enable\t\n\n\t THRESHOLD VALUES\n\t ----------------\n\n\t Parameter                 High Alarm  Low Alarm  High Warning  Low Warning\n\t ------------------------  ----------  ---------  ------------  -----------\n\t Rx Power Threshold(dBm)          7.4      -14.5           4.5        -10.5\n\t Tx Power Threshold(dBm)          7.4       -8.3           4.5         -4.3\n\t LBC Threshold(mA)              60.00      20.00         56.00        24.00\n\t Temp. Threshold(celsius)       75.00      -5.00         70.00         0.00\n\t Voltage Threshold(volt)         3.63       2.97          3.46         3.13\n\n\t Polarization parameters not supported by optics\n\n\t Lane  Laser Bias    TX Power    RX Power  Output Frequency\n\t ----  ----------  ----------  ----------  ----------------\n\t   0     38.9 mA    1.42 dBm   -2.04 dBm       N/A  \n\t   1     39.0 mA    1.68 dBm   -1.71 dBm       N/A  \n\t   2     37.9 mA    1.17 dBm   -1.68 dBm       N/A  \n\t   3     38.3 mA    1.66 dBm   -1.63 dBm       N/A  \n\n\t Temperature = 39.91 Celsius \n\t Voltage = 3.22 V \n\n Transceiver Vendor Details\n\n\t Form Factor \t\t: QSFP28\n\t Optics type \t\t: QSFP28 100G LR4\n\t Name \t\t\t: CISCO-SUMITOMO\n\t OUI Number \t\t: 00.00.5f\n\t Part Number \t\t: SQF1002L4LNC101P\n\t Rev Number \t\t: A\n\t Serial Number \t\t: SPC221100FB\n\t PID \t\t\t: QSFP-100G-LR4-S\n\t VID \t\t\t: V02\n\t Date Code(yy/mm/dd) \t: 18/03/08\n"

**Comment by LenzDong** [comment]
Thanks for reporting the issue, we will fix it and let you know when it's ready

**Comment by Neiby** [comment]
Thank you! Let me know if you need more example output.

**Comment by LenzDong** [comment]
Hi,

The parser fix is released. Please upgrade genie.libs.parser to the latest v20.6

Thanks

**Comment by Neiby** [comment]
Thanks, that works. I appreciate the help!
