### ISSUE TITLE
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys 

### ISSUE THREAD

**Issue by network-dave** [CiscoTestAutomation/genieparser#166]
Hi, I get the following error when trying to parse show cdp and show lldp neighbors outputs (NXOS) :

```python
Traceback (most recent call last):
  File "cli2xls.py", line 108, in <module>
    raise e
  File "cli2xls.py", line 102, in <module>
    main()
  File "cli2xls.py", line 84, in main
    json_data = cli2json.parse_cli_to_json(device_name, args.os, parser, cli_output)
  File "/mnt/c/Users/id865890/Documents/Python/cli2xls/cli2json.py", line 116, in parse_cli_to_json
    result = device.parse(parser, output=cli_output)
  File "src/genie/conf/base/device.py", line 552, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 585, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 302, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 284, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 405, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['cdp', 'index', 6, 'port_id'], ['cdp', 'index', 11, 'port_id'], ['cdp', 'index', 31, 'hold_time'], ['cdp', 'index', 31, 'port_id'], ['cdp', 'index', 31, 'local_interface'], ['cdp', 'index', 31, 'platform']]
```

Kind regards,

David

**Comment by KamyarZiabari** [comment]
Hi David,
If you tried show cdp and show lldp neighbors. At this moment they are not supported for nxos. 
The supported commands are, show cdp neighbors, and show cdp neighbors detail, same goes to show lldp neighbors. The show lldp neighbors is not supported but show lldp neighbors detail is supported.

You can use the existing commands and see if it helps you. We also highly encourage our customers to add to our parsers repository and develop parsers. If thats interesting to you just let me know and I send you proper tutorials so you could do that. 

Last thing you can do is that, you can provide us with proper possible outputs of the abovementioned commands and let us to develop the parser for those show commands for you. However, it is likely to be available in the next pyats release for you and it wont be a available right away.

Looking forward to hearing back from you.
Kamyar

**Comment by network-dave** [comment]
Dear Kamyar,

Thank you for your reply! I actually meant "show cdp neighbors" and "show lldp neighbors", my bad. But I didn't realize the later was not supported.

I would be glad to look into contributing parsers, feel freel to send me those tutorials.


Kind regards,


David

**Comment by KamyarZiabari** [comment]
Hi David,

Glad to hear that you will be helping us with parsers. Following links are necessary information for you to develop parsers:

https://developer.cisco.com/docs/pyats-development-guide/
Please do read this link first to be able to clone a genieparser repo in your local env.

https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/writeparser/writeparser.html
Using this link you can learn how you can write a parser. 

When done with the parser you can again review the info in the first link to learn how you can test and create a pull request so we could review your code.

When received we  will review your code, and when everything seemed fine, your code will be merged in our parser repository.

Thank you for your support and contribution in advance.

Regards,
Kamyar

**Comment by network-dave** [comment]
Kamyar,

Thanks, I will look into this ASAP.

Kind regards.
