### ISSUE TITLE
parse_genie not found

### ISSUE THREAD

**Issue by JasonMongroo** [CiscoTestAutomation/genieparser#173]
I have been getting this error when trying to run a playbook:

ERROR! the role 'parse_genie' was not found in /etc/ansible/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/etc/ansible

The error appears to be in '/etc/ansible/genie-test.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - parse_genie
      ^ here

In my roles directory, I have placed a requirements.yml file.

Followed this: https://www.ansible.com/blog/ansible-servicenow-part-2-parsing-facts-from-network-devices-using-pyats/genie

The playbook looks like this:
---
- name: pyATS testing
  hosts: uwioc-switches
  gather_facts: no
  roles:
    - parse_genie

  tasks:

  - name: Run the show version command
    ios_command:
      commands:
        - show version
    register: version

  - name: Set fact with Genie filter plugin
    set_fact:
      pyats_version: "{{ version['stdout'][0] | parse_genie(command='show version', os='ios') }}"

Any assistance would be appreciated.

**Comment by clay584** [comment]
If you are using Ansible 2.9 or greater, install this...

`ansible-galaxy collection install clay584.genie`

If you are using an older Ansible version, use this...

`ansible-galaxy install clay584.parse_genie`


Then it should be properly installed on your system.

There are differences on how you have to use the parse_genie filter plugin depending on whether it is for Ansible 2.9 or a lesser version, so make sure to read the docs on these as they are different.

https://github.com/clay584/genie_collection

https://github.com/clay584/parse_genie

As a side note, it looks like you are running Ansible as root and your playbook is in /etc/ansible. You probably just want to use your standard account and keep stuff in your home directory. Ansible commands and all will work under your standard account.
