### ISSUE TITLE
iosxe - show ip interface missing parse for Helper addresses.

### ISSUE THREAD

**Issue by rara08** [CiscoTestAutomation/genieparser#175]
https://github.com/CiscoTestAutomation/genieparser/blob/c73ce4718fc50e8c3772dd68c9626c96c3af3665/src/genie/libs/parser/ios/show_interface.py#L76

It would be nice to have helper addresses added to data structure.

_Vlan10 is up, line protocol is up
  Internet address is 1.1.1.1/24
  Broadcast address is 255.255.255.255
  Address determined by non-volatile memory
  MTU is 9154 bytes
  Helper addresses are 1.2.1.1
                       1.2.1.2
                       1.2.1.3
                       1.2.1.4_
.....

**Comment by thaixuann** [comment]
Thanks for reporting the issue.
including @ahersi2-cisco to support.

Thanks,
--Thai.

**Comment by ahersi2-cisco** [comment]
Hi rara08,

Thanks for catching this issue. If you don't mind, could you please send me a log of the parsed output? If you provide the CLI output followed by the parsed output, that would be best. Thank you!

**Comment by rara08** [comment]
**Raw CLI output (truncated):**

Vlan1 is administratively down, line protocol is down
  Internet protocol processing disabled
Vlan10 is up, line protocol is up
  Internet address is 1.1.1.1/24
  Broadcast address is 255.255.255.255
  Address determined by non-volatile memory
  MTU is 9154 bytes
  Helper addresses are 10.1.1.1
                       10.2.2.2
                       10.3.3.3
                       10.4.4.4
  Directed broadcast forwarding is disabled
  Outgoing Common access list is not set 
  Outgoing access list is not set
  Inbound Common access list is not set 
  Inbound  access list is not set
  Proxy ARP is enabled
  Local Proxy ARP is disabled
  Security level is default
  Split horizon is enabled
  ICMP redirects are always sent
  ICMP unreachables are always sent
  ICMP mask replies are never sent
  IP fast switching is enabled
  IP Flow switching is disabled
  IP CEF switching is enabled
  IP CEF switching turbo vector
  IP Null turbo vector
  VPN Routing/Forwarding "user"
  Associated unicast routing topologies:
        Topology "base", operation state is UP
  IP multicast fast switching is enabled
  IP multicast distributed fast switching is disabled
  IP route-cache flags are Fast, CEF
  Router Discovery is disabled
  IP output packet accounting is disabled
  IP access violation accounting is disabled
  TCP/IP header compression is disabled
  RTP/IP header compression is disabled
  Probe proxy name replies are disabled
  Policy routing is disabled
  Network address translation is disabled
  BGP Policy Mapping is disabled
  Input features: MCI Check
  IPv4 WCCP Redirect outbound is disabled
  IPv4 WCCP Redirect inbound is disabled
  IPv4 WCCP Redirect exclude is disabled
Vlan11 is up, line protocol is up
  Internet address is 2.2.2.1/24
  Broadcast address is 255.255.255.255
  Address determined by non-volatile memory
  MTU is 9154 bytes
  Helper addresses are 10.1.1.1
                       10.2.2.2
                       10.3.3.3
                       10.4.4.4
  Directed broadcast forwarding is disabled
  Outgoing Common access list is not set 
  Outgoing access list is not set
  Inbound Common access list is not set 
  Inbound  access list is not set
  Proxy ARP is enabled
  Local Proxy ARP is disabled
  Security level is default
  Split horizon is enabled
  ICMP redirects are always sent
  ICMP unreachables are always sent
  ICMP mask replies are never sent
  IP fast switching is enabled
  IP Flow switching is disabled
  IP CEF switching is enabled
  IP CEF switching turbo vector
  IP Null turbo vector
  VPN Routing/Forwarding "user"
  Associated unicast routing topologies:
        Topology "base", operation state is UP
  IP multicast fast switching is enabled
  IP multicast distributed fast switching is disabled
  IP route-cache flags are Fast, CEF
  Router Discovery is disabled
  IP output packet accounting is disabled
  IP access violation accounting is disabled
  TCP/IP header compression is disabled
  RTP/IP header compression is disabled
  Probe proxy name replies are disabled
  Policy routing is disabled
  Network address translation is disabled
  BGP Policy Mapping is disabled
  Input features: MCI Check
  IPv4 WCCP Redirect outbound is disabled
  IPv4 WCCP Redirect inbound is disabled
  IPv4 WCCP Redirect exclude is disabled

**Parsed Output (truncated to above):**
},
        "Vlan1": {
            "enabled": false,
            "oper_status": "down"
        },
        "Vlan10": {
            "address_determined_by": "non-volatile memory",
            "bgp_policy_mapping": false,
            "directed_broadcast_forwarding": false,
            "enabled": true,
            "icmp": {
                "mask_replies": "never sent",
                "redirects": "always sent",
                "unreachables": "always sent"
            },
            "input_features": [
                "MCI Check"
            ],
            "ip_access_violation_accounting": false,
            "ip_cef_switching": true,
            "ip_cef_switching_turbo_vector": true,
            "ip_fast_switching": true,
            "ip_flow_switching": false,
            "ip_multicast_distributed_fast_switching": false,
            "ip_multicast_fast_switching": true,
            "ip_null_turbo_vector": true,
            "ip_output_packet_accounting": false,
            "ip_route_cache_flags": [
                "CEF",
                "Fast"
            ],
            "ipv4": {
                "1.1.1.1/24": {
                    "broadcast_address": "255.255.255.255",
                    "ip": "1.1.1.1",
                    "prefix_length": "24",
                    "secondary": false
                }
            },
            "local_proxy_arp": false,
            "mtu": 9154,
            "network_address_translation": false,
            "oper_status": "up",
            "policy_routing": false,
            "probe_proxy_name_replies": false,
            "proxy_arp": true,
            "router_discovery": false,
            "rtp_ip_header_compression": false,
            "security_level": "default",
            "split_horizon": true,
            "tcp_ip_header_compression": false,
            "unicast_routing_topologies": {
                "topology": {
                    "base": {
                        "status": "up"
                    }
                }
            },
            "vrf": "user",
            "wccp": {
                "redirect_exclude": false,
                "redirect_inbound": false,
                "redirect_outbound": false
            }
        },
        "Vlan11": {
            "address_determined_by": "non-volatile memory",
            "bgp_policy_mapping": false,
            "directed_broadcast_forwarding": false,
            "enabled": true,
            "icmp": {
                "mask_replies": "never sent",
                "redirects": "always sent",
                "unreachables": "always sent"
            },
            "input_features": [
                "MCI Check"
            ],
            "ip_access_violation_accounting": false,
            "ip_cef_switching": true,
            "ip_cef_switching_turbo_vector": true,
            "ip_fast_switching": true,
            "ip_flow_switching": false,
            "ip_multicast_distributed_fast_switching": false,
            "ip_multicast_fast_switching": true,
            "ip_null_turbo_vector": true,
            "ip_output_packet_accounting": false,
            "ip_route_cache_flags": [
                "CEF",
                "Fast"
            ],
            "ipv4": {
                "2.2.2.1": {
                    "broadcast_address": "255.255.255.255",
                    "ip": "2.2.2.1",
                    "prefix_length": "24",
                    "secondary": false
                }
            },
            "local_proxy_arp": false,
            "mtu": 9154,
            "network_address_translation": false,
            "oper_status": "up",
            "policy_routing": false,
            "probe_proxy_name_replies": false,
            "proxy_arp": true,
            "router_discovery": false,
            "rtp_ip_header_compression": false,
            "security_level": "default",
            "split_horizon": true,
            "tcp_ip_header_compression": false,
            "unicast_routing_topologies": {
                "topology": {
                    "base": {
                        "status": "up"
                    }
                }
            },
            "vrf": "user",
            "wccp": {
                "redirect_exclude": false,
                "redirect_inbound": false,
                "redirect_outbound": false
            }
        },

**Comment by ahersi2-cisco** [comment]
Hi rara08,

Thanks for providing the data required. I should have an answer for you very shorty. Talk to you soon!

Abdurahman

**Comment by ahersi2-cisco** [comment]
Hi rara08,

It seems capturing Helper addresses weren't added in the regex portion of the parsers. An adjustment can be made to add them to the parsed output. I can make the changes and let you know when the beta version would be released, which shouldn't be too long, or if you feel you can make the fix yourself you are free to submit a PR which can be reviewed and accepted. I can also let you know what fix needs to be made. 

Thank you,
Abdurahman

**Comment by rara08** [comment]
> Hi rara08,
> 
> It seems capturing Helper addresses weren't added in the regex portion of the parsers. An adjustment can be made to add them to the parsed output. I can make the changes and let you know when the beta version would be released, which shouldn't be too long, or if you feel you can make the fix yourself you are free to submit a PR which can be reviewed and accepted. I can also let you know what fix needs to be made.
> 
> Thank you,
> Abdurahman

I can give it a try.  Let me know what fix needs to be made.
Thanks,
R

**Comment by ahersi2-cisco** [comment]
Hi rara08,

The fix that needs to be made is the following; There currently isn't a regex that captures the line `Helper addresses are 10.1.1.1` followed by the addresses in subsequent lines. What you'll need to do is create a regex pattern in the function `ShowIpInterface` and capture that necessary data. Adding that captured data to the dictionary called `interface_dict` should work. There are multiple ways where you can handle capturing the subsequent lines, which is totally up to you. If you feel this is something you can do, you are welcome to submit a PR as well. If you need further assistance I can do it on my end, and can inform you when a release is made so the changes are available to you. Thank you!

Abdurahman

**Comment by rara08** [comment]
I took a look, but I think this is a bit above my capabilities.  
I did get a working regex:
`^( +Helper +addresses +are|\s+) (?P<address>[0-9\.]+)$`

That seems to do the trick, but the real problem is that the schema defines "helper_address" as a "str", and we need a "list".  
I think the right solution is to change helper_address to list and re-factor the current function (line 2066) to accommodate for single and multiple ip's.
Also, it needs to accommodate for the grammatically correct output versions for single and multiple IPs:  "Helper address is" && "Helper addresses are" 
I think Ill leave this to you :)
Thanks.

**Comment by ahersi2-cisco** [comment]
Hi rara08,

You're absolutely right, a list would be more appropriate so I will change the schema. When a beta is released I will update you right away. Talk to you soon.

Abdurahman

**Comment by rara08** [comment]
FYI - I took a stab at it and submitted a Pull request (#180).
Thanks,
Raul

**Comment by ahersi2-cisco** [comment]
Hi rara08,

I'll take a look at the PR. I also completed it, so in case the PR isn't immediately approved or doesn't cover your issue entirely, a beta should be released soon.

Thank you,
Abdurahman

**Comment by rara08** [comment]
Cool.. no worries. It was an educational exercise for me.

**Comment by ahersi2-cisco** [comment]
Hi rara08,

We have released a beta package with the fix included (v20.6.1b0). You can upgrade to the latest release as per the following command;

pip install --upgrade --pre genie.libs.parser

Thank you,
Abdurahman

**Comment by rara08** [comment]
> Hi rara08,
> 
> We have released a beta package with the fix included (v20.6.1b0). You can upgrade to the latest release as per the following command;
> 
> pip install --upgrade --pre genie.libs.parser
> 
> Thank you,
> Abdurahman

Seems to work fine now.  Thanks.
