### ISSUE TITLE
ios, iosxe: show mac address-table output not parsed

### ISSUE THREAD

**Issue by salvapinyol** [CiscoTestAutomation/genieparser#177]
Hi, I've some ios & ios-xe devices that produces this kind of output for show mac address-table command:

Unicast Entries
 vlan   mac address     type        protocols               port
-------+---------------+--------+---------------------+--------------------
   2    0000.0c07.ac23   dynamic ip                    Port-channel1         
   2    0002.b3ec.e8e7   dynamic ip                    Port-channel1         
   2    0003.ba0e.e151   dynamic ip                    Port-channel1         
   2    0003.ba21.b9a7   dynamic ip                    Port-channel1         
   2    0003.ba21.ba01   dynamic ip                    Port-channel1         
   2    0003.bab0.3bdf   dynamic ip                    Port-channel1         
   2    0003.bacd.15c9   dynamic ip                    Port-channel1         
   2    0008.e3ff.fea8   dynamic ip                    Port-channel1         
   2    0010.83fd.fde9   dynamic ip                    Port-channel1         
   2    0014.4f1e.4f94   dynamic ip                    Port-channel1         
   2    0014.4f3a.7af7   dynamic ip                    Port-channel1         
   2    0014.4f80.c881   dynamic ip                    Port-channel1         

(truncated output, full output attached)

So it seems that the parser is not able to deal with this output. Also I don't see any reference to protocols in the schema.

Salva.
[connection_ES1SW18AUN6.txt](https://github.com/CiscoTestAutomation/genieparser/files/4846722/connection_ES1SW18AUN6.txt)
[ES1SW18AUN6_show-mac-address-table_console.txt](https://github.com/CiscoTestAutomation/genieparser/files/4846723/ES1SW18AUN6_show-mac-address-table_console.txt)
[ES1SW18AUN6_show-mac-address-table_parsed.txt](https://github.com/CiscoTestAutomation/genieparser/files/4846725/ES1SW18AUN6_show-mac-address-table_parsed.txt)

**Comment by karmoham** [comment]
Including @danielgraziano to support!

**Comment by danielgraziano** [comment]
Hi @salvapinyol, I have found the issue and fixed it. We are releasing v20.6 tomorrow (July 7th) and this fix will be in that.

**Comment by salvapinyol** [comment]
hi @danielgraziano. Thanks for the fix. I'll check if all my output is correctly parsed now.

**Comment by salvapinyol** [comment]
It looks Ok. Thanks!
