### ISSUE TITLE
My pyATS has problem on show ip sla summary.

### ISSUE THREAD

**Issue by richyim** [CiscoTestAutomation/genieparser#178]
I had tested 'show ip int brief'. It worked. However, it did not work for 'show ip sla summary'. My program is as follow:
---
import pprint
from genie.testbed import load
tb = load('my_testbed.yaml')
dev = tb.devices['LISP-HOME-1941']
dev.connect()
#p1 = dev.parse('show ip int brief')
p1 = dev.parse('show ip sla summary')
print('out is ')
pp = pprint.PrettyPrinter(indent=4)
pp.pprint (p1)
---

It hit an error:

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    p1 = dev.parse('show ip sla summary')
  File "src/genie/conf/base/device.py", line 550, in genie.conf.base.device.Device.parse
  File "/usr/local/lib/python3.8/dist-packages/genie/libs/parser/utils/common.py", line 104, in get_parser
    raise Exception("Could not find parser for "
Exception: Could not find parser for 'show ip sla summary' under ('ios',)

**Comment by karmoham** [comment]
Hi Rich,

Thanks for reaching out! @ahersi2-cisco will help ou shortly.

Thanks,
Karim

**Comment by karmoham** [comment]
Including @Abdurahman Hersi -X (abhersi - ALBANY SERVICES  INC at Cisco)<mailto:abhersi@cisco.com> to support!

Thanks,
Karim Mohamed
2018 Pioneer Award Winner
Core Software Group(CSG) SSR | XPRESSO<https://apps.na.collabserv.com/communities/service/html/communitystart?communityUuid=c1ac02c3-4a58-4653-8baf-b8c3014c371d> | pyATS | Genie<https://apps.na.collabserv.com/communities/service/html/communityview?communityUuid=146bcff2-136d-4916-9a59-37e910c1460b>
DevX Engineering Community http://devx.cisco.com<http://devx.cisco.com/>

[signature_1880048914]

**Comment by ahersi2-cisco** [comment]
Hi Rich,

It doesn't appear we have that command as part of our parser list. Can you provide the CLI and parsed output for the command 'show ip int brief' if you don't mind. I know we have a command that uses 'interface' instead of int, but I haven't seen one that uses 'int'.

Thank you,
Abdurahman

**Comment by richyim** [comment]
Dear Abdurahman,

This is the test.py:

import pprint

from genie.testbed import load

tb = load('my_testbed.yaml')

dev = tb.devices['LISP-HOME-1941']

dev.connect()

p1 = dev.parse('show ip sla summary')

print('out is ')

pp = pprint.PrettyPrinter(indent=4)

pp.pprint (p1)


This is the my_testbed.yaml:

devices:

  LISP-HOME-1941:

    connections:

      cli:

        ip: 192.168.113.254

        protocol: ssh

    credentials:

      default:

        password: '%ENC{xxx}'

        username: admin

      enable:

        password: '%ENC{xxx}'

    os: ios

    type: ios


This is the test output:


root@NM44:~/yaml# python test.py

[2020-07-04 11:44:04,439] +++ LISP-HOME-1941 logfile /tmp/LISP-HOME-1941-cli-20200704T114404439.log +++

[2020-07-04 11:44:04,440] +++ Unicon plugin ios +++

Password:

[2020-07-04 11:44:04,829] +++ connection to spawn: ssh -l admin 192.168.113.254, id: 139997114953152 +++

[2020-07-04 11:44:04,830] connection to LISP-HOME-1941



Hi, Rich

LISP-HOME-1941#

[2020-07-04 11:44:05,131] +++ initializing handle +++

[2020-07-04 11:44:05,131] +++ LISP-HOME-1941: executing command 'term length 0' +++

term length 0

LISP-HOME-1941#

[2020-07-04 11:44:05,244] +++ LISP-HOME-1941: executing command 'term width 0' +++

term width 0

LISP-HOME-1941#

[2020-07-04 11:44:05,356] +++ LISP-HOME-1941: executing command 'show version' +++

show version

Cisco IOS Software, C1900 Software (C1900-UNIVERSALK9-M), Version 15.4(3)M3, RELEASE SOFTWARE (fc2)

Technical Support: http://www.cisco.com/techsupport

Copyright (c) 1986-2015 by Cisco Systems, Inc.

Compiled Fri 05-Jun-15 12:31 by prod_rel_team



ROM: System Bootstrap, Version 15.0(1r)M3, RELEASE SOFTWARE (fc1)



LISP-HOME-1941 uptime is 1 week, 6 days, 23 hours, 19 minutes

System returned to ROM by power-on

System restarted at 12:24:35 HKG Sat Jun 20 2020

System image file is "flash:c1900-universalk9-mz.SPA.154-3.M3.bin"

Last reload type: Normal Reload

Last reload reason: power-on







This product contains cryptographic features and is subject to United

States and local country laws governing import, export, transfer and

use. Delivery of Cisco cryptographic products does not imply

third-party authority to import, export, distribute or use encryption.

Importers, exporters, distributors and users are responsible for

compliance with U.S. and local country laws. By using this product you

agree to comply with applicable laws and regulations. If you are unable

to comply with U.S. and local laws, return this product immediately.



A summary of U.S. laws governing Cisco cryptographic products may be found at:

http://www.cisco.com/wwl/export/crypto/tool/stqrg.html



If you require further assistance please contact us by sending email to

export@cisco.com.



Cisco CISCO1941/K9 (revision 1.0) with 2559936K/61440K bytes of memory.

Processor board ID FTX1417815R

15 Gigabit Ethernet interfaces

2 terminal lines

1 Virtual Private Network (VPN) Module

1 Internal Services Module (ISM) with Services Ready Engine (SRE)

   Cisco WLAN Controller 7.4.110.0 in slot/sub-slot 0/0

DRAM configuration is 64 bits wide with parity disabled.

255K bytes of non-volatile configuration memory.

254464K bytes of ATA System CompactFlash 0 (Read/Write)





License Info:



License UDI:



-------------------------------------------------

Device#   PID                SN

-------------------------------------------------

*1       CISCO1941/K9          FTX1417815R







Technology Package License Information for Module:'c1900'



------------------------------------------------------------------------

Technology    Technology-package                  Technology-package

              Current              Type           Next reboot

------------------------------------------------------------------------

ipbase        ipbasek9             Permanent      ipbasek9

security      securityk9           Permanent      securityk9

data          datak9               Permanent      datak9

NtwkEss       None                 None           None



Configuration register is 0x2102



LISP-HOME-1941#

[2020-07-04 11:44:05,610] +++ LISP-HOME-1941: config +++

config term

Enter configuration commands, one per line.  End with CNTL/Z.

LISP-HOME-1941(config)#no logging console

LISP-HOME-1941(config)#line console 0

LISP-HOME-1941(config-line)#exec-timeout 0

LISP-HOME-1941(config-line)#end

LISP-HOME-1941#

Traceback (most recent call last):

  File "test.py", line 7, in <module>

    p1 = dev.parse('show ip sla summary')

  File "src/genie/conf/base/device.py", line 550, in genie.conf.base.device.Device.parse

  File "/usr/local/lib/python3.8/dist-packages/genie/libs/parser/utils/common.py", line 104, in get_parser

    raise Exception("Could not find parser for "

Exception: Could not find parser for 'show ip sla summary' under ('ios',)

This is the genie command output:

[cid:image001.png@01D651F9.3E1E0670]

Rich Yim
Systems Engineer
Cisco Systems (HK)
Mobile: 96422596
31/F Great Eagle Center, 23 Harbour Road, Wan Chai, HK
[A picture containing game, food  Description automatically generated][A close up of a logo  Description automatically generated]

**Comment by ahersi2-cisco** [comment]
Hi Rich,

If I'm not mistaken you provided the output for 'show ip sla summary' not 'show ip int brief'. Also if everything below `This is the test output:` what came out of parsing 'show ip sla summary'? If so, I was expecting an error similar to what you showed on the first post. I would like to see something similar to the first post but the entire log. Can you please provide output for 'show ip int brief' as well. Please let me know if I am looking at this correctly. Also, the following URL shows you the list of parsers that we have;
https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/parsers.

Thank you,
Abdurahman

**Comment by richyim** [comment]
Dear Abdurahman,

Here is the genie CLI:


root@NM44:~/yaml# genie parse "show ip int brief" --testbed-file my_testbed.yaml --device LISP-HOME-1941

  0%|                                                                                                                                                                          | 0/1 [00:00<?, ?it/s]{

  "interface": {

    "Dialer1": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "NVRAM",

      "protocol": "up",

      "status": "up"

    },

    "Embedded-Service-Engine0/0": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "NVRAM",

      "protocol": "down",

      "status": "administratively down"

    },

    "GigabitEthernet0/0": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "NVRAM",

      "protocol": "down",

      "status": "down"

    },

    "GigabitEthernet0/0/0": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "unset",

      "protocol": "up",

      "status": "up"

    },

    "GigabitEthernet0/0/1": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "unset",

      "protocol": "down",

      "status": "down"

    },

    "GigabitEthernet0/0/2": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "unset",

      "protocol": "down",

      "status": "down"

    },

    "GigabitEthernet0/0/3": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "unset",

      "protocol": "down",

      "status": "down"

    },

    "GigabitEthernet0/1": {

      "interface_is_ok": "YES",

      "ip_address": "10.74.221.254",

      "method": "NVRAM",

      "protocol": "up",

      "status": "up"

    },

    "GigabitEthernet0/1/0": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "unset",

      "protocol": "up",

      "status": "up"

    },

    "GigabitEthernet0/1/1": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "unset",

      "protocol": "down",

      "status": "down"

    },

    "GigabitEthernet0/1/2": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "unset",

      "protocol": "down",

      "status": "down"

    },

    "GigabitEthernet0/1/3": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "unset",

      "protocol": "down",

      "status": "down"

    },

    "GigabitEthernet0/1/4": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "unset",

      "protocol": "down",

      "status": "down"

    },

    "GigabitEthernet0/1/5": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "unset",

      "protocol": "up",

      "status": "up"

    },

    "GigabitEthernet0/1/6": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "unset",

      "protocol": "down",

      "status": "down"

    },

    "GigabitEthernet0/1/7": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "unset",

      "protocol": "up",

      "status": "up"

    },

    "ISM0/0": {

      "interface_is_ok": "YES",

      "ip_address": "2.2.2.254",

      "method": "NVRAM",

      "protocol": "up",

      "status": "up"

    },

    "ISM0/1": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "unset",

      "protocol": "up",

      "status": "up"

    },

    "LISP0": {

      "interface_is_ok": "YES",

      "ip_address": "2.2.2.254",

      "method": "unset",

      "protocol": "up",

      "status": "up"

    },

    "Loopback0": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "unset",

      "protocol": "up",

      "status": "up"

    },

    "Loopback1": {

      "interface_is_ok": "YES",

      "ip_address": "153.16.66.66",

      "method": "NVRAM",

      "protocol": "up",

      "status": "up"

    },

    "Loopback11": {

      "interface_is_ok": "YES",

      "ip_address": "11.11.11.11",

      "method": "NVRAM",

      "protocol": "up",

      "status": "up"

    },

    "Loopback2": {

      "interface_is_ok": "YES",

      "ip_address": "153.16.66.65",

      "method": "NVRAM",

      "protocol": "up",

      "status": "up"

    },

    "Loopback30": {

      "interface_is_ok": "YES",

      "ip_address": "192.168.130.1",

      "method": "NVRAM",

      "protocol": "up",

      "status": "up"

    },

    "Loopback55": {

      "interface_is_ok": "YES",

      "ip_address": "4.5.6.7",

      "method": "manual",

      "protocol": "up",

      "status": "up"

    },

    "NVI0": {

      "interface_is_ok": "YES",

      "ip_address": "153.16.66.66",

      "method": "unset",

      "protocol": "up",

      "status": "up"

    },

    "Tunnel0": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "unset",

      "protocol": "down",

      "status": "up"

    },

    "Tunnel1": {

      "interface_is_ok": "YES",

      "ip_address": "192.168.113.254",

      "method": "unset",

      "protocol": "up",

      "status": "up"

    },

    "Tunnel10": {

      "interface_is_ok": "YES",

      "ip_address": "172.30.151.190",

      "method": "NVRAM",

      "protocol": "up",

      "status": "up"

    },

    "Tunnel103": {

      "interface_is_ok": "YES",

      "ip_address": "192.103.1.1",

      "method": "NVRAM",

      "protocol": "down",

      "status": "up"

    },

    "Tunnel11": {

      "interface_is_ok": "YES",

      "ip_address": "10.11.100.3",

      "method": "NVRAM",

      "protocol": "down",

      "status": "administratively down"

    },

    "Tunnel171": {

      "interface_is_ok": "YES",

      "ip_address": "172.171.2.13",

      "method": "NVRAM",

      "protocol": "up",

      "status": "up"

    },

    "Tunnel172": {

      "interface_is_ok": "YES",

      "ip_address": "172.171.20.13",

      "method": "NVRAM",

      "protocol": "down",

      "status": "up"

    },

    "Tunnel181": {

      "interface_is_ok": "YES",

      "ip_address": "172.181.1.13",

      "method": "NVRAM",

      "protocol": "up",

      "status": "up"

    },

    "Tunnel2": {

      "interface_is_ok": "YES",

      "ip_address": "192.168.113.254",

      "method": "unset",

      "protocol": "up",

      "status": "up"

    },

    "Virtual-Access1": {

      "interface_is_ok": "NO",

      "ip_address": "unassigned",

      "method": "unset",

      "protocol": "up",

      "status": "up"

    },

    "Virtual-Access2": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "unset",

      "protocol": "up",

      "status": "up"

    },

    "Vlan1": {

      "interface_is_ok": "YES",

      "ip_address": "unassigned",

      "method": "unset",

      "protocol": "up",

      "status": "up"

    },

    "Vlan100": {

      "interface_is_ok": "YES",

      "ip_address": "124.244.46.157",

      "method": "DHCP",

      "protocol": "up",

      "status": "up"

    },

    "Vlan113": {

      "interface_is_ok": "YES",

      "ip_address": "192.168.113.254",

      "method": "NVRAM",

      "protocol": "up",

      "status": "up"

    },

    "Vlan114": {

      "interface_is_ok": "YES",

      "ip_address": "192.168.114.254",

      "method": "NVRAM",

      "protocol": "up",

      "status": "up"

    }

  }

}

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.14it/s]



root@NM44:~/yaml#


Here is the python output:

root@NM44:~/yaml# pico test.py

root@NM44:~/yaml# python test.py

[2020-07-05 03:26:00,084] +++ LISP-HOME-1941 logfile /tmp/LISP-HOME-1941-cli-20200705T032600083.log +++

[2020-07-05 03:26:00,085] +++ Unicon plugin ios +++

Password:

[2020-07-05 03:26:00,297] +++ connection to spawn: ssh -l admin 192.168.113.254, id: 140008721403328 +++

[2020-07-05 03:26:00,298] connection to LISP-HOME-1941



Hi, Rich

LISP-HOME-1941#

[2020-07-05 03:26:00,557] +++ initializing handle +++

[2020-07-05 03:26:00,558] +++ LISP-HOME-1941: executing command 'term length 0' +++

term length 0

LISP-HOME-1941#

[2020-07-05 03:26:00,874] +++ LISP-HOME-1941: executing command 'term width 0' +++

term width 0

LISP-HOME-1941#

[2020-07-05 03:26:01,020] +++ LISP-HOME-1941: executing command 'show version' +++

show version

Cisco IOS Software, C1900 Software (C1900-UNIVERSALK9-M), Version 15.4(3)M3, RELEASE SOFTWARE (fc2)

Technical Support: http://www.cisco.com/techsupport

Copyright (c) 1986-2015 by Cisco Systems, Inc.

Compiled Fri 05-Jun-15 12:31 by prod_rel_team



ROM: System Bootstrap, Version 15.0(1r)M3, RELEASE SOFTWARE (fc1)



LISP-HOME-1941 uptime is 2 weeks, 15 hours, 1 minute

System returned to ROM by power-on

System restarted at 12:24:35 HKG Sat Jun 20 2020

System image file is "flash:c1900-universalk9-mz.SPA.154-3.M3.bin"

Last reload type: Normal Reload

Last reload reason: power-on







This product contains cryptographic features and is subject to United

States and local country laws governing import, export, transfer and

use. Delivery of Cisco cryptographic products does not imply

third-party authority to import, export, distribute or use encryption.

Importers, exporters, distributors and users are responsible for

compliance with U.S. and local country laws. By using this product you

agree to comply with applicable laws and regulations. If you are unable

to comply with U.S. and local laws, return this product immediately.



A summary of U.S. laws governing Cisco cryptographic products may be found at:

http://www.cisco.com/wwl/export/crypto/tool/stqrg.html



If you require further assistance please contact us by sending email to

export@cisco.com.



Cisco CISCO1941/K9 (revision 1.0) with 2559936K/61440K bytes of memory.

Processor board ID FTX1417815R

15 Gigabit Ethernet interfaces

2 terminal lines

1 Virtual Private Network (VPN) Module

1 Internal Services Module (ISM) with Services Ready Engine (SRE)

   Cisco WLAN Controller 7.4.110.0 in slot/sub-slot 0/0

DRAM configuration is 64 bits wide with parity disabled.

255K bytes of non-volatile configuration memory.

254464K bytes of ATA System CompactFlash 0 (Read/Write)





License Info:



License UDI:



-------------------------------------------------

Device#   PID                SN

-------------------------------------------------

*1       CISCO1941/K9          FTX1417815R







Technology Package License Information for Module:'c1900'



------------------------------------------------------------------------

Technology    Technology-package                  Technology-package

              Current              Type           Next reboot

------------------------------------------------------------------------

ipbase        ipbasek9             Permanent      ipbasek9

security      securityk9           Permanent      securityk9

data          datak9               Permanent      datak9

NtwkEss       None                 None           None



Configuration register is 0x2102



LISP-HOME-1941#

[2020-07-05 03:26:01,210] +++ LISP-HOME-1941: config +++

config term

Enter configuration commands, one per line.  End with CNTL/Z.

LISP-HOME-1941(config)#no logging console

LISP-HOME-1941(config)#line console 0

LISP-HOME-1941(config-line)#exec-timeout 0

LISP-HOME-1941(config-line)#end

LISP-HOME-1941#

[2020-07-05 03:26:01,846] +++ LISP-HOME-1941: executing command 'show ip interface brief' +++

show ip interface brief

Interface                  IP-Address      OK? Method Status                Protocol

Embedded-Service-Engine0/0 unassigned      YES NVRAM  administratively down down

GigabitEthernet0/0         unassigned      YES NVRAM  down                  down

ISM0/0                     2.2.2.254       YES NVRAM  up                    up

GigabitEthernet0/1         10.74.221.254   YES NVRAM  up                    up

ISM0/1                     unassigned      YES unset  up                    up

GigabitEthernet0/0/0       unassigned      YES unset  up                    up

GigabitEthernet0/0/1       unassigned      YES unset  down                  down

GigabitEthernet0/0/2       unassigned      YES unset  down                  down

GigabitEthernet0/0/3       unassigned      YES unset  down                  down

GigabitEthernet0/1/0       unassigned      YES unset  up                    up

GigabitEthernet0/1/1       unassigned      YES unset  down                  down

GigabitEthernet0/1/2       unassigned      YES unset  down                  down

GigabitEthernet0/1/3       unassigned      YES unset  down                  down

GigabitEthernet0/1/4       unassigned      YES unset  down                  down

GigabitEthernet0/1/5       unassigned      YES unset  up                    up

GigabitEthernet0/1/6       unassigned      YES unset  down                  down

GigabitEthernet0/1/7       unassigned      YES unset  up                    up

Dialer1                    unassigned      YES NVRAM  up                    up

LISP0                      2.2.2.254       YES unset  up                    up

Loopback0                  unassigned      YES unset  up                    up

Loopback1                  153.16.66.66    YES NVRAM  up                    up

Loopback2                  153.16.66.65    YES NVRAM  up                    up

Loopback11                 11.11.11.11     YES NVRAM  up                    up

Loopback30                 192.168.130.1   YES NVRAM  up                    up

Loopback55                 4.5.6.7         YES manual up                    up

NVI0                       153.16.66.66    YES unset  up                    up

Tunnel0                    unassigned      YES unset  up                    down

Tunnel1                    192.168.113.254 YES unset  up                    up

Tunnel2                    192.168.113.254 YES unset  up                    up

Tunnel10                   172.30.151.190  YES NVRAM  up                    up

Tunnel11                   10.11.100.3     YES NVRAM  administratively down down

Tunnel103                  192.103.1.1     YES NVRAM  up                    down

Tunnel171                  172.171.2.13    YES NVRAM  up                    up

Tunnel172                  172.171.20.13   YES NVRAM  up                    down

Tunnel181                  172.181.1.13    YES NVRAM  up                    up

Virtual-Access1            unassigned      NO  unset  up                    up

Virtual-Access2            unassigned      YES unset  up                    up

Vlan1                      unassigned      YES unset  up                    up

Vlan100                    124.244.46.157  YES DHCP   up                    up

Vlan113                    192.168.113.254 YES NVRAM  up                    up

Vlan114                    192.168.114.254 YES NVRAM  up                    up

LISP-HOME-1941#

out is

{   'interface': {   'Dialer1': {   'interface_is_ok': 'YES',

                                    'ip_address': 'unassigned',

                                    'method': 'NVRAM',

                                    'protocol': 'up',

                                    'status': 'up'},

                     'Embedded-Service-Engine0/0': {   'interface_is_ok': 'YES',

                                                       'ip_address': 'unassigned',

                                                       'method': 'NVRAM',

                                                       'protocol': 'down',

                                                       'status': 'administratively '

                                                                 'down'},

                     'GigabitEthernet0/0': {   'interface_is_ok': 'YES',

                                               'ip_address': 'unassigned',

                                               'method': 'NVRAM',

                                               'protocol': 'down',

                                               'status': 'down'},

                     'GigabitEthernet0/0/0': {   'interface_is_ok': 'YES',

                                                 'ip_address': 'unassigned',

                                                 'method': 'unset',

                                                 'protocol': 'up',

                                                 'status': 'up'},

                     'GigabitEthernet0/0/1': {   'interface_is_ok': 'YES',

                                                 'ip_address': 'unassigned',

                                                 'method': 'unset',

                                                 'protocol': 'down',

                                                 'status': 'down'},

                     'GigabitEthernet0/0/2': {   'interface_is_ok': 'YES',

                                                 'ip_address': 'unassigned',

                                                 'method': 'unset',

                                                 'protocol': 'down',

                                                 'status': 'down'},

                     'GigabitEthernet0/0/3': {   'interface_is_ok': 'YES',

                                                 'ip_address': 'unassigned',

                                                 'method': 'unset',

                                                 'protocol': 'down',

                                                 'status': 'down'},

                     'GigabitEthernet0/1': {   'interface_is_ok': 'YES',

                                               'ip_address': '10.74.221.254',

                                               'method': 'NVRAM',

                                               'protocol': 'up',

                                               'status': 'up'},

                     'GigabitEthernet0/1/0': {   'interface_is_ok': 'YES',

                                                 'ip_address': 'unassigned',

                                                 'method': 'unset',

                                                 'protocol': 'up',

                                                 'status': 'up'},

                     'GigabitEthernet0/1/1': {   'interface_is_ok': 'YES',

                                                 'ip_address': 'unassigned',

                                                 'method': 'unset',

                                                 'protocol': 'down',

                                                 'status': 'down'},

                     'GigabitEthernet0/1/2': {   'interface_is_ok': 'YES',

                                                 'ip_address': 'unassigned',

                                                 'method': 'unset',

                                                 'protocol': 'down',

                                                 'status': 'down'},

                     'GigabitEthernet0/1/3': {   'interface_is_ok': 'YES',

                                                 'ip_address': 'unassigned',

                                                 'method': 'unset',

                                                 'protocol': 'down',

                                                 'status': 'down'},

                     'GigabitEthernet0/1/4': {   'interface_is_ok': 'YES',

                                                 'ip_address': 'unassigned',

                                                 'method': 'unset',

                                                 'protocol': 'down',

                                                 'status': 'down'},

                     'GigabitEthernet0/1/5': {   'interface_is_ok': 'YES',

                                                 'ip_address': 'unassigned',

                                                 'method': 'unset',

                                                 'protocol': 'up',

                                                 'status': 'up'},

                     'GigabitEthernet0/1/6': {   'interface_is_ok': 'YES',

                                                 'ip_address': 'unassigned',

                                                 'method': 'unset',

                                                 'protocol': 'down',

                                                 'status': 'down'},

                     'GigabitEthernet0/1/7': {   'interface_is_ok': 'YES',

                                                 'ip_address': 'unassigned',

                                                 'method': 'unset',

                                                 'protocol': 'up',

                                                 'status': 'up'},

                     'ISM0/0': {   'interface_is_ok': 'YES',

                                   'ip_address': '2.2.2.254',

                                   'method': 'NVRAM',

                                   'protocol': 'up',

                                   'status': 'up'},

                     'ISM0/1': {   'interface_is_ok': 'YES',

                                   'ip_address': 'unassigned',

                                   'method': 'unset',

                                   'protocol': 'up',

                                   'status': 'up'},

                     'LISP0': {   'interface_is_ok': 'YES',

                                  'ip_address': '2.2.2.254',

                                  'method': 'unset',

                                  'protocol': 'up',

                                  'status': 'up'},

                     'Loopback0': {   'interface_is_ok': 'YES',

                                      'ip_address': 'unassigned',

                                      'method': 'unset',

                                      'protocol': 'up',

                                      'status': 'up'},

                     'Loopback1': {   'interface_is_ok': 'YES',

                                      'ip_address': '153.16.66.66',

                                      'method': 'NVRAM',

                                      'protocol': 'up',

                                      'status': 'up'},

                     'Loopback11': {   'interface_is_ok': 'YES',

                                       'ip_address': '11.11.11.11',

                                       'method': 'NVRAM',

                                       'protocol': 'up',

                                       'status': 'up'},

                     'Loopback2': {   'interface_is_ok': 'YES',

                                      'ip_address': '153.16.66.65',

                                      'method': 'NVRAM',

                                      'protocol': 'up',

                                      'status': 'up'},

                     'Loopback30': {   'interface_is_ok': 'YES',

                                       'ip_address': '192.168.130.1',

                                       'method': 'NVRAM',

                                       'protocol': 'up',

                                       'status': 'up'},

                     'Loopback55': {   'interface_is_ok': 'YES',

                                       'ip_address': '4.5.6.7',

                                       'method': 'manual',

                                       'protocol': 'up',

                                       'status': 'up'},

                     'NVI0': {   'interface_is_ok': 'YES',

                                 'ip_address': '153.16.66.66',

                                 'method': 'unset',

                                 'protocol': 'up',

                                 'status': 'up'},

                     'Tunnel0': {   'interface_is_ok': 'YES',

                                    'ip_address': 'unassigned',

                                    'method': 'unset',

                                    'protocol': 'down',

                                    'status': 'up'},

                     'Tunnel1': {   'interface_is_ok': 'YES',

                                    'ip_address': '192.168.113.254',

                                    'method': 'unset',

                                    'protocol': 'up',

                                    'status': 'up'},

                     'Tunnel10': {   'interface_is_ok': 'YES',

                                     'ip_address': '172.30.151.190',

                                     'method': 'NVRAM',

                                     'protocol': 'up',

                                     'status': 'up'},

                     'Tunnel103': {   'interface_is_ok': 'YES',

                                      'ip_address': '192.103.1.1',

                                      'method': 'NVRAM',

                                      'protocol': 'down',

                                      'status': 'up'},

                     'Tunnel11': {   'interface_is_ok': 'YES',

                                     'ip_address': '10.11.100.3',

                                     'method': 'NVRAM',

                                     'protocol': 'down',

                                     'status': 'administratively down'},

                     'Tunnel171': {   'interface_is_ok': 'YES',

                                      'ip_address': '172.171.2.13',

                                      'method': 'NVRAM',

                                      'protocol': 'up',

                                      'status': 'up'},

                     'Tunnel172': {   'interface_is_ok': 'YES',

                                      'ip_address': '172.171.20.13',

                                      'method': 'NVRAM',

                                      'protocol': 'down',

                                      'status': 'up'},

                     'Tunnel181': {   'interface_is_ok': 'YES',

                                      'ip_address': '172.181.1.13',

                                      'method': 'NVRAM',

                                      'protocol': 'up',

                                      'status': 'up'},

                     'Tunnel2': {   'interface_is_ok': 'YES',

                                    'ip_address': '192.168.113.254',

                                    'method': 'unset',

                                    'protocol': 'up',

                                    'status': 'up'},

                     'Virtual-Access1': {   'interface_is_ok': 'NO',

                                            'ip_address': 'unassigned',

                                            'method': 'unset',

                                            'protocol': 'up',

                                            'status': 'up'},

                     'Virtual-Access2': {   'interface_is_ok': 'YES',

                                            'ip_address': 'unassigned',

                                            'method': 'unset',

                                            'protocol': 'up',

                                            'status': 'up'},

                     'Vlan1': {   'interface_is_ok': 'YES',

                                  'ip_address': 'unassigned',

                                  'method': 'unset',

                                  'protocol': 'up',

                                  'status': 'up'},

                     'Vlan100': {   'interface_is_ok': 'YES',

                                    'ip_address': '124.244.46.157',

                                    'method': 'DHCP',

                                    'protocol': 'up',

                                    'status': 'up'},

                     'Vlan113': {   'interface_is_ok': 'YES',

                                    'ip_address': '192.168.113.254',

                                    'method': 'NVRAM',

                                    'protocol': 'up',

                                    'status': 'up'},

                     'Vlan114': {   'interface_is_ok': 'YES',

                                    'ip_address': '192.168.114.254',

                                    'method': 'NVRAM',

                                    'protocol': 'up',

                                    'status': 'up'}}}

root@NM44:~/yaml#



Regards,
Rich Yim
Systems Engineer
Cisco Systems (HK)
Mobile: 96422596
31/F Great Eagle Center, 23 Harbour Road, Wan Chai, HK
[A picture containing game, food  Description automatically generated][A close up of a logo  Description automatically generated]

**Comment by ahersi2-cisco** [comment]
Hi,

Do you mind telling me what version of genie and pyATS you have? If they are outdated please update and try running again and provide that output as well.

Thank you,
Abdurahman

**Comment by richyim** [comment]
Dear Adburahman,


root@NM44:~/yaml# pyats version check

You are currently running pyATS version: 20.5

Python: 3.8.2 [64bit]



  Package                      Version

  ---------------------------- -------

  genie                        20.5

  genie.libs.clean             20.5

  genie.libs.conf              20.5

  genie.libs.filetransferutils 20.5

  genie.libs.ops               20.5

  genie.libs.parser            20.5

  genie.libs.robot             20.5

  genie.libs.sdk               20.5

  genie.telemetry              20.5

  genie.trafficgen             20.5

  pyats                        20.5

  pyats.aereport               20.5

  pyats.aetest                 20.5

  pyats.async                  20.5

  pyats.connections            20.5

  pyats.contrib                20.5

  pyats.datastructures         20.5

  pyats.easypy                 20.5

  pyats.kleenex                20.5

  pyats.log                    20.5

  pyats.reporter               20.5

  pyats.results                20.5

  pyats.robot                  20.5

  pyats.tcl                    20.5

  pyats.topology               20.5

  pyats.utils                  20.5

  unicon                       20.5

  unicon.plugins               20.5




Regards,

Rich Yim
Systems Engineer
Cisco Systems (HK)
Mobile: 96422596
31/F Great Eagle Center, 23 Harbour Road, Wan Chai, HK
[A picture containing game, food  Description automatically generated][A close up of a logo  Description automatically generated]

**Comment by ahersi2-cisco** [comment]
Hi richyim,

I just want to confirm which command you want to use. Is 'show ip sla summary' a short version of a command you want to use? Can you find the command you want to use or something related in the following;

https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/parsers

Thank you,
Abdurahman

**Comment by richyim** [comment]
Thanks Abdurahman,

I cannot find the show IP SLA command in the list. Therefore, I think this is the reason. Can I ask for a feature request?

Second question I would like to ask if there is a way to have pyATS on Raspberry Pi?

Regards,

Rich Yim
Systems Engineer
Cisco Systems (HK)
Mobile: 96422596
31/F Great Eagle Center, 23 Harbour Road, Wan Chai, HK
[A picture containing game, food  Description automatically generated][A close up of a logo  Description automatically generated]

**Comment by ahersi2-cisco** [comment]
Hi Rich,

By feature are you referring to a new parser? If not what kind of feature are you referring to?

Thank you,
Abdurahman

**Comment by ahersi2-cisco** [comment]
Hi Rich,

In regards to your question about Raspberry Pi, you can have pyATS on it. The steps are the same as other devices. Just make sure you have the correct specifications in your testbed file.

Thank you,
Abdurahman
