### ISSUE TITLE
Genie ASA Learn Error - Could not find the API under asa, and common

### ISSUE THREAD

**Issue by ogruca** [CiscoTestAutomation/genieparser#179]
Hi

First of all thank you all for all your work in this wonderful tool, this has opened my eyes to network automation and started my curiosity in programming.  I wasnt sure if this is the correct place to post this issue so apologies in advance.

I am having an issue when learning all genie modules fo Cisco ASA (physical and virtual) version 9.12(3)205.  The script runs upto 97% then generates the error below.

Could not find the API under asa, and common

If i run the command with some verbosity genie learn all --testbed-file at.yaml -vvvv i get a bit more detail.
 
Enabled forked tasklog generation
Disabled forked tasklog generation
pyats.async_.exceptions.RemoteException: 

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 290, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "src/genie/conf/base/api.py", line 52, in genie.conf.base.api.API.__getattr__.wrapper_match
  File "src/genie/conf/base/api.py", line 123, in genie.conf.base.api.API.get_api
AttributeError: Could not find the API under asa, and common

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/pyats/cli/base.py", line 207, in pyats.cli.base.Command.main
  File "src/genie/cli/commands/learn.py", line 125, in genie.cli.commands.learn.LearnCommand.run
  File "src/genie/cli/commands/learn.py", line 188, in genie.cli.commands.learn.LearnCommand._learn_ops
  File "src/pyats/async_/parallelcall.py", line 157, in pyats.async_.parallelcall.Pcall.pcall
  File "src/pyats/async_/parallelcall.py", line 278, in pyats.async_.parallelcall.Pcall.join
pyats.async_.exceptions.ChildProcessException: Could not find the API under asa, and common

Could not find the API under asa, and common

Here is my virtual environment
Package                      Version
---------------------------- ----------
aiohttp                      3.6.2
async-timeout                3.0.1
attrs                        19.3.0
certifi                      2019.11.28
chardet                      3.0.4
dill                         0.3.1.1
distro                       1.4.0
genie                        20.5
genie.libs.clean             20.5
genie.libs.conf              20.5
genie.libs.filetransferutils 20.5
genie.libs.ops               20.5
genie.libs.parser            20.5
genie.libs.sdk               20.5
idna                         2.9
Jinja2                       2.11.1
jsonpickle                   1.3
junit-xml                    1.9
MarkupSafe                   1.1.1
multidict                    4.7.5
netaddr                      0.7.19
pathspec                     0.7.0
pip                          20.1.1
ply                          3.11
prettytable                  0.7.2
psutil                       5.7.0
pyasn1                       0.4.8
pyats                        20.5
pyats.aereport               20.5
pyats.aetest                 20.5
pyats.async                  20.5
pyats.connections            20.5
pyats.datastructures         20.5
pyats.easypy                 20.5
pyats.kleenex                20.5
pyats.log                    20.5
pyats.reporter               20.5
pyats.results                20.5
pyats.tcl                    20.5
pyats.topology               20.5
pyats.utils                  20.5
pycryptodomex                3.9.8
pysmi                        0.3.4
pysnmp                       4.4.12
python-engineio              3.13.1
python-socketio              4.6.0
PyYAML                       5.3
requests                     2.23.0
setuptools                   40.8.0
six                          1.14.0
tqdm                         4.43.0
unicon                       20.5
unicon.plugins               20.5
urllib3                      1.25.8
wheel                        0.34.2
xlrd                         1.2.0
XlsxWriter                   1.2.8
xlwt                         1.3.0
xmltodict                    0.12.0
yamllint                     1.20.0
yarl                         1.4.2

The testbed file is shown below
testbed:
  name: Cisco Asa
  credentials:
    default:
      username: xxxxx
      password: xxxxx
    enable:
      password: xxxxx

devices:
  sdc1va081:
    alias: sdc1va081
    os: asa
    type: ASAv
    connections:
      defaults:
        class: unicon.Unicon
      console:
        ip: 10.139.15.12
        protocol: ssh
    custom:
      abstraction:
        order: [os, type]

**Comment by LenzDong** [comment]
Hi,
Genie learn is based on the ops model and currently we don't have any api and ops model for ASA device 
but we do have some parsers for ASA.

Here is the available ops models, mainly support IOSXE/IOSXR/NXOS devices
https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/models

Here is the available parsers for ASA
https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/parsers
![image](https://user-images.githubusercontent.com/5717109/86926517-2a2d6400-c100-11ea-90c7-23bf88e31fcf.png)

**Comment by jeaubin** [comment]
Adding models for ASA has been added to our backlog, but current as @LenzDong mentioned, we dont have some for ASA.

Though we have many parsers!
