### ISSUE TITLE
IOS-CORE: Show mac address-table: cannot parse 

### ISSUE THREAD

**Issue by martinLennart** [CiscoTestAutomation/genieparser#18]
genie parse "show mac address-table" --testbed-file git/testbed.yml --output git/macadress-table/
C6880-X-LE
Version 15.1(02)SY01 [ Rel 1.1]

Getting following error message:

Issue with the parser show mac address-table

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 272, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 498, in genie.conf.base.device.Device.parse
  File "src/genie/metaparser/_metaparser.py", line 302, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 284, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 398, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['total_mac_addresses']]

**Comment by martinLennart** [comment]
Output:
[Error - 13:40:16] (node:14592) UnhandledPromiseRejectionWarning: #<Object>
[Error - 13:40:16] (node:14592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[Error - 13:40:16] (node:14592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by karmoham** [comment]
Hi Martin,

Thank you for reporting this issue. Can you please send us the full device output at pyats-support-ext@cisco.com so we fix the issue?

Device output is securely handled inside the team and won't be exposed to anyone else.

Thanks,
Karim

**Comment by jeaubin** [comment]
@martinLennart 
The issue has been fixed. We’ve released a beta package for this fix.
 
Pip install genie.libs.parser --upgrade --pre
 
Let us know if it works as expected.

**Comment by urskog84** [comment]
nice what is the pre-relased version number?

**Comment by karmoham** [comment]
Hi,

The beta package version is **19.4.1b4**.

Thanks,
Karim

**Comment by karmoham** [comment]
Hi Peter/Martin,

Can you please confirm the beta package solved the issue?

Thanks,
Karim

**Comment by martinLennart** [comment]
hello Karim!

I can confirm 19.4.1b4 solved the problem.

**Comment by karmoham** [comment]
Thanks for the confirmation Martin!
