### ISSUE TITLE
Update Testing Strategy

### ISSUE THREAD

**Issue by itdependsnetworks** [CiscoTestAutomation/genieparser#181]
The testing framework requires a lot of boilerplate code and is much of the raw values collected are actually incorrect. Take for example: https://github.com/CiscoTestAutomation/genieparser/blob/b0603c1456dea15160b2a19312d8675e7a450b2d/src/genie/libs/parser/ios/tests/test_show_acl.py#L170-L177 this evaluates to: 

```
        Router# show access-lists 101
        Extended IP access list 101
            10 permit ip host 10.3.3.3 host 10.5.5.34
            20 permit icmp any any
            30 permit ip host 10.34.2.2 host 10.2.54.2
            40 permit ip host 10.3.4.31 host 10.3.32.3 log
```
instead of 
```
Router# show access-lists 101
Extended IP access list 101
    10 permit ip host 10.3.3.3 host 10.5.5.34
    20 permit icmp any any
    30 permit ip host 10.34.2.2 host 10.2.54.2
    40 permit ip host 10.3.4.31 host 10.3.32.3 log
```
This difference, may be subtle but can be crucial in building the proper parser.

I propose following a directory structure based approach, examples of which can be seen in the NAPALM and ntc-templates. There are additional use cases covered here, such as raised issues, but I do think this should be doable. It should also make it simple to determine which tests are built, reduce the size of any file, and provide an overall easier user experience.

`tests/<command>/<test_type>/<user_defined>/(expected.json|return.raw)`

```
tests/show_ip_access_lists/equal/golden/return.raw
tests/show_ip_access_lists/equal/golden/expected.json
tests/show_ip_access_lists/schema_empty/empty/return.raw
tests/show_ip_access_lists/schema_empty/empty/expected.json
```

I know this simplified solution does not account for all solutions, but I suspect this strategy can make it easier.

**Comment by itdependsnetworks** [comment]
@danielgraziano @xiaoxinz-cisco not sure what is going on with the assignments. This is work I may be willing to take on, as it likely makes it easier for me in the long run, just need to understand if this is a consideration or not.

**Comment by jeaubin** [comment]
@itdependsnetworks What you are proposing is:

Have a directory structure 

```<parser-cmd>/<type>/<any name>/<return.raw|expected.json>```

Depending on the type, it will use different boiler plate code. 

Few types idea

* Equal, raw parsed must equal expected.json
* Raise a type of exception
* .... 

For this we need a small infrastructure that go reads these file and generates testcases automatically.

It makes sense. We can keep all current testcases as is, but all new one could use that testcase type.

We dont have cycle to do this right now, but I can add it to our backlog and see if we can tackle this around September. If you want to do it, that would be fantastic.


Let me know if you had something else in mind

**Comment by itdependsnetworks** [comment]
This is exactly what I had in mind. We will be contributing a bunch, and I think the effort to update this will be worth it. Let me get back to you next week with timeline expectations (if I think we can take on)

**Comment by jeaubin** [comment]
Perfect,  Thanks. 

Thanks for contributing.
