### ISSUE TITLE
"show isis" parse failure

### ISSUE THREAD

**Issue by clay584** [CiscoTestAutomation/genieparser#183]
An issue was opened on my ansible filter plugin, but it is raising an exception on Device.parse(). Can you all take a look?

https://github.com/clay584/parse_genie/issues/11

Here is the line where it is crashing.
https://github.com/clay584/parse_genie/blob/master/filter_plugins/genie.py#L123

**Comment by tahigash** [comment]
asked the person who opened Issue on parse_genie. now waiting for the output.

**Comment by tahigash** [comment]
confirmed with @arynair over emails. The issue was in Ansible playbook. and now works after updating Ansible playbook. Closing.
