### ISSUE TITLE
Docstring Copy/Paste Error

### ISSUE THREAD

**Issue by clay584** [CiscoTestAutomation/genieparser#19]
It's silly, but this looks like a copy/paste error in this docstring.

https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/ios/show_lldp.py#L1

Docstring says the filename is `show_spanning_tree.py`, should be `show_lldp.py`.

**Comment by jeaubin** [comment]
Hi @clay584   - Thanks, 

Will fix.

**Comment by jeaubin** [comment]
It has been fixed and pushed to github

Thanks,
