### ISSUE TITLE
Change Log Merge Conflict

### ISSUE THREAD

**Issue by itdependsnetworks** [CiscoTestAutomation/genieparser#190]
The process for adding change-logs leads to a high likelihood of merge conflicts. Is there room to re-evaluate this method? 

Perhaps something like

```
{month}/{add|update}/{feature}.md
```
and then the build artifact concatenates this information?

**Comment by jeaubin** [comment]
We are actually changing our merge/build artifact this month. 

Let me add this to the backlog. We had discussion to change it in the past, so this month would be a good time. 

Thanks,

**Comment by jeaubin** [comment]
Something similar has been rolled out for last release; 

Create a new file under that directory for every PR named - changelog_<feature>_<unique number>.rst

Then for each release we have a script that merge them all within our release note.
