### ISSUE TITLE
[Parser][ios/iosxe][ShowIpInterface] helper_address crash when only one

### ISSUE THREAD

**Issue by Maxiturne** [CiscoTestAutomation/genieparser#191]
On interfaces where where we only have one ip-helper address, showIpInterface parser is crashing because the template is expecting a list and the script return a string

Output of show ip interface : 
VlanXXX is up, line protocol is up
  Internet address is XXX.XXX.XXXX.XXXX/YY
  Broadcast address is 255.255.255.255
  Address determined by configuration file
  MTU is 1500 bytes
  Helper address is XXX.XXX.XXX.XXX
  ....

Exception generated : genie.metaparser.util.exceptions.SchemaTypeError: VlanXXX.helper_address: Expected type '<class 'list'>' but got type 'XXX.XXX.XXX.XXX'(<class 'str'>)

Incriminated Line : 
https://github.com/CiscoTestAutomation/genieparser/blob/8626c5e3917ac973850bbce5bfe181160720ce68/src/genie/libs/parser/iosxe/show_interface.py#L2071

Not sure but for me, the line should be : 
interface_dict[interface]['helper_address'] = [m.groupdict()['address']]

**Comment by bastell** [comment]
Hi,

You are correct, there is a mismatch between the schema and the parsed output. I'll make sure this is fixed, and update you here when it's available next week.

Thanks,
Ben

**Comment by mgdransfield** [comment]
I fixed this as I also saw the same issue and have a pull request with a couple of other updates
