### ISSUE TITLE
Incorrect instantiation of `SchemaTypeError` class

### ISSUE THREAD

**Issue by jmcgill298** [CiscoTestAutomation/genieparser#194]
I looked through the code for some Schema Validation examples. I emulated the examples of using the `SchemaTypeError` to generate errors when the data type was an invalid type, however, when testing the code, the raising of this error generated another exception. I looked into it and the SchemaTypeError constructor requires `path`, `schema`, and `data` args, and optionally takes a `detail` argument. Currently the uses of SchemaTypeError are only passing the optional `detail` arg, which is actually being taken as the `path` arg; however these should all fail to instantiate an instance since they are missing 2 required args.

Here is a list of 
[SchemaTypeError Instances](https://github.com/CiscoTestAutomation/genieparser/search?p=2&q=%22raise+SchemaTypeError%22&unscoped_q=%22raise+SchemaTypeError%22)

**Comment by karmoham** [comment]
Hi Jacob,

Thanks for narrowing down to the misuse of the `SchemaTypeError` in the Junos parsers. We will fix it and it should be part of the next official release v20.8.

Thanks,
Karim
