### ISSUE TITLE
IOSXE: 'show switch' parser issue

### ISSUE THREAD

**Issue by oianson** [CiscoTestAutomation/genieparser#205]
Hi, 

On the IOSXE 'show switch' parser, it is not detecting switch number 1 here, suspect it is due to the hyphen in the state (V-Mismatch).

```
Switch/Stack Mac Address : 00ca.e50e.1500 - Local Mac Address
Mac persistency wait time: Indefinite
                                             H/W   Current
Switch#   Role    Mac Address     Priority Version  State 
------------------------------------------------------------
 1       Member   00cc.fc7f.fb80     15     0       V-Mismatch          
*2       Active   00ca.e50e.1500     1      V06     Ready  
```

**Comment by ahersi2-cisco** [comment]
Hi oianson,

Thanks for the question. Can you please provide the parser output for the CLI output you provided?

Thank you,
Abdurahman

**Comment by oianson** [comment]
```
{
  "switch": {
    "mac_address": "00ca.e50e.1500",
    "mac_persistency_wait_time": "indefinite",
    "stack": {
      "2": {
        "role": "active",
        "state": "ready",
        "mac_address": "00ca.e50e.1500",
        "priority": "1",
        "hw_ver": "V06"
      }
    }
  }
}
```

**Comment by ahersi2-cisco** [comment]
Hi Oianson,

You suspected correctly. The regular expression wasn't correctly capturing the hypen. We encourage users to submit PR's, so if you'd like you can make the change in the regex pattern and submit a PR, which will be reviewed and merged when accepted. The change will have to be made in the 'show_platform.py' file, specifically on the 'p3_1' variable on the captured group called 'state'. As an alternative I can make the change for you and update you when the change is merged and a beta is released for you to use. Let me know if this helps and if you will decide to make the change yourself or wait for a beta.

Thank you,
Abdurahman

**Comment by oianson** [comment]
Thanks Abdurahman
I've submitted a PR on the bitbucker, will close this issue. THanks
