### ISSUE TITLE
LLDP Interface Schema Documentation Issue

### ISSUE THREAD

**Issue by clay584** [CiscoTestAutomation/genieparser#21]
[This](https://pubhub.devnetcloud.com/media/pyats-packages/docs/genie/genie_libs/#/parsers/show%20lldp%20interface) documentation does not appear to match the actual schema definition for the [ShowLldpEntrySchema](https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/iosxe/show_lldp.py#L82) class.

**Comment by jeaubin** [comment]
@clay584   -

![image](https://user-images.githubusercontent.com/576771/60284893-ab8dcc00-98da-11e9-9408-4a7027643ae9.png)

![image](https://user-images.githubusercontent.com/576771/60284904-b21c4380-98da-11e9-83bd-77c2d69e63ad.png)


The documentation is for show lldp interface, not show lddp entry.

[Here](https://pubhub.devnetcloud.com/media/pyats-packages/docs/genie/genie_libs/#/parsers/show%20lldp%20entry%20%7Bentry%7D) is the documentation for show lddp entry

**Comment by jeaubin** [comment]
ah! 

We've updated our doc,  but it is now pointing to a new location.

https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/parsers

On this one you can find show lldp neighbors detail 

![image](https://user-images.githubusercontent.com/576771/60299381-96c13080-98fa-11e9-88df-3ed3d6f8f230.png)



And on this one, 

![image](https://user-images.githubusercontent.com/576771/60299431-ac365a80-98fa-11e9-9c8c-1748f2b42d36.png)


it shows correctly.

We'll see if we can redirect the old page to the new page.

**Comment by jeaubin** [comment]
@clay584  - Can you confirm that its working as expected, then we will close this issue.

**Comment by clay584** [comment]
It's all good now. Thanks!
