### ISSUE TITLE
ImportError: cannot import name get_ops_exclude

### ISSUE THREAD

**Issue by GPorter73** [CiscoTestAutomation/genieparser#22]
I'm trying to run genie learn today. It's worked in the past, but it's not working at the moment with the following output:

`(genie_lab_router) [gporter@fwdnetcent01 genie_lab_router]$ genie learn
Traceback (most recent call last):
  File "/home/gporter/genie_lab_router/bin/genie", line 6, in <module>
    from genie.cli.__main__ import main
  File "src/genie/cli/__main__.py", line 8, in init genie.cli.__main__
  File "src/genie/cli/commands/learn.py", line 6, in init genie.cli.commands.learn
ImportError: cannot import name get_ops_exclude`

**Comment by GPorter73** [comment]
closing this out for now. I'll email support.

**Comment by jeaubin** [comment]
It seems some package arent up to date.  Can you run this command to update all packages

pip install --upgrade genie genie.abstract genie.conf genie.examples genie.harness genie.libs.conf genie.libs.filetransferutils genie.libs.ops genie.libs.parser genie.libs.robot genie.libs.sdk genie.libs.telemetry genie.metaparser genie.ops genie.parsergen genie.predcore genie.telemetry genie.utils unicon genie.trafficgen

This will update everything to latest, it should work after.

**Comment by GPorter73** [comment]
Thanks! That resolved it.
