### ISSUE TITLE
iosxe "show access-lists" renumbers the sequence numbers and also misses statements over 10 entries

### ISSUE THREAD

**Issue by alurmtr** [CiscoTestAutomation/genieparser#228]
A couple of issues here. 

1.- Parse genie "show access-list" parser renumbers the sequences for a standard list. This works Ok when the actual output of the cisco command "show access-list" is ordered as 10, 20, 30, 40..etc. But there are cases when the output from the cisco command is out of order, and parse genie reorders it.

It has been documented here that unordered access-list behavior is possible
https://community.cisco.com/t5/switching/access-list-wrong-order/m-p/3181371/highlight/true#M390769

For example, for the following "Show access-lists" output
Standard IP access list 10
    60 permit IP_ADDRESS_6
    110 permit IP_ADDRESS_11
    100 permit IP_ADDRESS_10
    80 permit IP_ADDRESS_8
    70 permit IP_ADDRESS_7
    130 permit IP_ADDRESS_13
    140 permit IP_ADDRESS_14
    50 permit IPADDRESS_5
    90 permit IP_ADDRESS_9
    120 permit IP_ADDRESS_12
    10 permit IP_ADDRESS_1, wildcard bits MASK (x matches)
    20 permit IP_ADDRESS_2, wildcard bits MASK (y matches)
    30 permit IP_ADDRESS_3, wildcard bits MASK (z matches)
    40 permit IP_ADDRESS_4, wildcard bits MASK
    150 deny   any

After passing it through genie, the genie parser will parse and renumber the sequence  as:

    10 -> permit IP_ADDRESS_8
    20 -> permit IP_ADDRESS_11
    30 -> permit IP_ADDRESS_10
    40 -> permit IP_ADDRESS_7
    50 -> permit IP_ADDRESS_6
    60 -> permit IP_ADDRESS_13

    and so on....

Second issue...
2.- When more than 10 entries are added to an standard acl, parse genie does not parse the additional entries correctly 

Using the example above, "Standard IP access list 10". After then tenth entry, parse genie will stop creating new aces, and will append new entries to the tenth ace.

Parsed output:
        "10": {
            "aces": {
                "10": {
                    "actions": {
                        "forwarding": "permit"
                    },
                    "matches": {
                        "l3": {
                            "ipv4": {
                                "protocol": "ipv4",
                                "source_network": {
                                    "IP_ADDRESS_6 0.0.0.0": {
                                        "source_network": IP_ADDRESS_6 0.0.0.0"
                                    }
                                }
                            }
                        }
                    },
                    "name": "10"
                },
                "100": {
                    "actions": {
                        "forwarding": "permit"
                    },
                    "matches": {
                        "l3": {
                            "ipv4": {
                                "protocol": "ipv4",
                                "source_network": {
                                    "IP_ADDRESS_4 MASK": {
                                        "source_network": "IP_ADDRESS_4 MASK"
                                    },
                                    "IP_ADDRESS_3 MASK": {
                                        "source_network": "IP_ADDRESS_3 MASK"
                                    },
                                    "IP_ADDRESS_1 MASK": {
                                        "source_network": "IP_ADDRESS_1 MASK"
                                    },
                                    "IP_ADDRESS_2 MASK": {
                                        "source_network": "IP_ADDRESS_2 MASK"
                                    },
                                    "IP_ADDRESS_12 MASK": {
                                        "source_network": "IP_ADDRESS_12 MASK"
                                    },
                                    "any": {
                                        "source_network": "any"
                                    }
                                }
                            }
                        }
                    },
                    "name": "100",
                    "statistics": {
                        "matched_packets": 89
                    }
                },
                "20": {
                    "actions": {
                        "forwarding": "permit"
                    },
                    "matches": {
                        "l3": {
                            "ipv4": {
                                "protocol": "ipv4",
                                "source_network": {
                                    "IP_ADDRESS_11 MASK": {
                                        "source_network": "IP_ADDRESS_11 MASK"
                                    }
                                }
                            }
                        }
                    },
                    "name": "20"
                },
                "30": {
                    "actions": {
                        "forwarding": "permit"
                    },
                    "matches": {
                        "l3": {
                            "ipv4": {
                                "protocol": "ipv4",
                                "source_network": {
                                    "IP_ADDRESS_10 MASK": {
                                        "source_network": "IP_ADDRESS_10 MASK"
                                    }
                                }
                            }
                        }
                    },
                    "name": "30"
                },

and so on.....

What's the problem?

in your code  iosxe/show_acl.py

This logic here:
seq = int(sorted(acl_dict.get('aces', {'0': 'dummy'}).keys())[-1]) + 10

will pickup the last element of the sorted array. However as you see below, the key array is like this array after the tenth element

['10', '100', '20', '30', '40', '50', '60', '70', '80', '90']

so it will never increment past 100 as python places the string '100' after '10' instead of '90'.

it is unnecessary/incorrect to reorder the acl entries on the parse. The regex code already captures the original sequence number under "seq". In my opinion, this line here:

seq = int(sorted(acl_dict.get('aces', {'0': 'dummy'}).keys())[-1]) + 10

should be replaced with

seq = group['seq']

However, looking at the code, looks like the intention was to handle ACL entries with no sequence numbers? . In that case, I can see why you would need to append a sequence number. However, we haven't seen those cases where there are no sequence numbers in the cisco output for standard ip access list ("show access-list")

Thanks

A

**Comment by ahersi2-cisco** [comment]
Hi A,

Thank you for the detailed message. In regards to your first query, would you be able to provide the complete CLI and parsed output? As for the second query, it could be possible that the parser didn't anticipate that specific scenario, but I understand the issue here. We encourage users to submit pull requests, and you are more than welcome to submit one which will get reviewed and merged if approved. Otherwise, I can take a look into this, and once a fix is obtained a beta can be released for you if the updated code is needed right away. Otherwise a new version is released every month, which will include the changes. Please let me know which approach you favor.

Thank you,
Abdurahman

**Comment by alurmtr** [comment]
Hello Abdurahman,

I actually added the parsed output in the second case.

You can see it goes 10, 100, 20, 30

I wont be able to get to this for a bit so if you are able to fix, go for it. Then again, i think the fix that would take care of both issues would be to replace
seq = int(sorted(acl_dict.get('aces', {'0': 'dummy'}).keys())[-1]) + 10
 with
seq = group['seq']

However, this doesn't address the case where the ACL output doesn't have a sequence number. Which i haven't seen but may be possible?, i  don't know.

Thanks
A

**Comment by ahersi2-cisco** [comment]
Hello alumtr,

Sorry for the delay, a fix has been made for this and is currently in code review. Once it is approved I will merge it and can release a beta for you to use. Thank you for the patience.

Abdurahman

**Comment by ahersi2-cisco** [comment]
Hello alumtr,

Beta package v20.8.1b6 has been released with the fix, you can install it using the following command;

pip install --upgrade genie.libs.parser --pre

 

https://pypi.org/project/genie.libs.parser/20.8.1b6/

Thank you,
Abdurahman

**Comment by jeaubin** [comment]
This has been released part of the official release
