### ISSUE TITLE
unable to find parser for command 'show version' 

### ISSUE THREAD

**Issue by Network748** [CiscoTestAutomation/genieparser#229]
I am receiving the following error:
  {"changed": false, "msg": "Unable to find parser for command 'show version' (invalid syntax (show_cts.py, line 133))"}

Thanks

**Comment by jeaubin** [comment]
Can you share

1) On what OS you are trying
2) Are you running with pyats parse command line? If so can you paste the whole log,  or send us the whole output to pyats-support-ext@cisco.com

We would need more information to understand what is going on.

**Comment by Network748** [comment]
OS:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

running the following code:
gather_facts: False
  collections:
    - clay584.genie
  vars:
    ansible_python_interpreter: /usr/bin/python

  tasks:
    - name: Get Data From Device
      ios_command:
        commands: show interfaces status
      register: arp_output

    - name: Print Structured Data
      debug:
        msg: "{{ arp_output['stdout'][0] | clay584.genie.parse_genie(command='show interfaces status', os='ios') }}"
      delegate_to: localhost

---------------------
produces the following error:
=> {"msg": "parse_genie: No such attribute in abstraction package 'genie.libs.parser': 'genie.libs.parser.sho                                       w_interface.ShowInterfacesStatus' - Available parsers: https://pubhub.devnetcloud.com/media/pyats-packages/docs/genie/genie_libs/#/parsers"}

----------------------------------------------------------------------------------------------
I have clay584 in the same directory as my playbooks.

Running the following code:

 connection: network_cli
  gather_facts: no
  roles:
    - ansible-pyats
  tasks:
    - name: Run command
      cli_command:
        command: show ip route
      register: cli_output

    - name: Parsing output
      set_fact:
        parsed_output: "{{ cli_output.stdout | pyats_parser('show ip route', 'ios') }}"

produces the following error:
: FAILED! => {"msg": "Unable to find parser for command 'show ip route' (invalid syntax (show_cts.py, line 133))"}

**Comment by Network748** [comment]
Additional error: 

TASK [pyats_parse_command] ********************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named genie.libs.parser.utils
fatal: [IP address]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/username/.ansible/tmp/ansible-local-30397iqn__63i/ansible-tmp-1599669320.5429263-30404-239462753506452/AnsiballZ_pyats_parse_command.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/username/.ansible/tmp/ansible-local-30397iqn__63i/ansible-tmp-1599669320.5429263-30404-239462753506452/AnsiballZ_pyats_parse_command.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/username/.ansible/tmp/ansible-local-30397iqn__63i/ansible-tmp-1599669320.5429263-30404-239462753506452/AnsiballZ_pyats_parse_command.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.pyats_parse_command', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_pyats_parse_command_payload_f50Tk1/ansible_pyats_parse_command_payload.zip/ansible/modules/pyats_parse_command.py\", line 16, in <module>\nImportError: No module named genie.libs.parser.utils\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by Network748** [comment]
ok, I now added it the following vars:
    **ansible_python_interpreter: /usr/bin/python3**
directly onto the playbook and now I keep  getting the following error:

FAILED! => {"changed": false, "msg": "Unable to find parser for command 'show interface status' (invalid syntax (show_cts.py, line 133))"}

**Comment by tahigash** [comment]
Hi @Network748, I confirmed below line in the error.

```
File "/usr/lib/python2.7/runpy.py", line 188, in run_module\n fname, loader, pkg_name)\n File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code\n mod_name, mod_fname, mod_loader, pkg_name)\n File "/usr/lib/python2.7/runpy.py", line 72,
```

It says `python2.7`, but pyATS support python3.5+. Could you please check if you are running on python3.5+? if not, please create python virtualenv with python3.5+ and check there.

**Comment by Network748** [comment]
Yes, I created a virtualenv and hardcoded the following on the playbook ansible_python_interpreter: /usr/bin/python3. 

Getting the following error now: 
FAILED! => {"changed": false, "msg": "Unable to find parser for command 'show interface status' (invalid syntax (show_cts.py, line 133))"}

**Comment by tahigash** [comment]
Hi @Network748 
sorry for delayed response.
```
FAILED! => {"changed": false, "msg": "Unable to find parser for command 'show interface status' (invalid syntax (show_cts.py, line 133))"}
```
for above message, it says `unable to find parser`. It seems correct command is `show interfaces status`. (in your log, `s` was missing after `interface`)

please try with `show interfaces status`.

**Comment by jeaubin** [comment]
Closing as no update and wrong command sent. Feel free to re-open if seen again
