### ISSUE TITLE
Not parsing "show inventory"

### ISSUE THREAD

**Issue by berishap** [CiscoTestAutomation/genieparser#230]
Hi,

it is not possible to parse the ouput of "show inventory" on a WS-C4507R+E with IOS-XE Version 03.07.02.E

Error:

```---------------------------------------------------------------------------
SchemaEmptyParserError                    Traceback (most recent call last)
<ipython-input-15-7a9d81f8b5fe> in <module>
----> 1 output = tb.devices['HOSTNAME'].parse('show inventory')

~/ws/nb-collector/venv/lib/python3.7/site-packages/genie/conf/base/device.cpython-37m-x86_64-linux-gnu.so in genie.conf.base.device.Device.parse()

~/ws/nb-collector/venv/lib/python3.7/site-packages/genie/conf/base/device.cpython-37m-x86_64-linux-gnu.so in genie.conf.base.device.Device._get_parser_output()

~/ws/nb-collector/venv/lib/python3.7/site-packages/genie/metaparser/_metaparser.cpython-37m-x86_64-linux-gnu.so in genie.metaparser._metaparser.MetaParser.parse()

~/ws/nb-collector/venv/lib/python3.7/site-packages/genie/metaparser/_metaparser.cpython-37m-x86_64-linux-gnu.so in genie.metaparser._metaparser.MetaParser.parse()

~/ws/nb-collector/venv/lib/python3.7/site-packages/genie/metaparser/util/schemaengine.cpython-37m-x86_64-linux-gnu.so in genie.metaparser.util.schemaengine.Schema.validate()

SchemaEmptyParserError: Parser Output is empty```

Thank you.

Regards,
Petrit

**Comment by karmoham** [comment]
Hi Berishap,

Can you please send the device `show inventory` output to `pyats-support-ext@cisco.com` so we can check the parser and place any fix if needed?

Thanks,
Karim

**Comment by berishap** [comment]
Hi Karim,

Thank you. I did send the output.

Thank you.
Regards,
Petrit

**Comment by ahersi2-cisco** [comment]
Hi Petrit,

Thank you for providing the output. I'll take a look into it and update you shortly.

Thank you,
Abdurahman

**Comment by ahersi2-cisco** [comment]
Hi Petrit,

A fix was made for your issue, and it is currently under review. As soon as it's approved, I can get it merged and release a beta for you. I will you keep you updated once that's done.

Thank you,
Abdurahman

**Comment by ahersi2-cisco** [comment]
Hi Petrit,

Sorry for the delay, the changes can now be seen if you upgrade using the following;

pip install --pre genie.libs.parser

Let me know if this helps.

Thank you,
Abdurahman

**Comment by jeaubin** [comment]
Part of the latest release 20.9
