### ISSUE TITLE
Issue with VTP status parser?

### ISSUE THREAD

**Issue by ledazzler** [CiscoTestAutomation/genieparser#25]
Hi,

I think there is an issue with the VTP parser.

I'm running a test script, connected to a single IOS switch.     I can successfully connect to the device, and parse 'show version', 'show interface' and 'show vlan'.   However, the parser for 'show vtp staus' throws an error:

>>> a.parse("show vtp status")
[2019-07-25 11:30:58,310] +++ <<switchname>>: executing command 'show vtp status' +++
show vtp status
VTP Version                     : running VTP1 (VTP2 capable)
Configuration Revision          : 0
Maximum VLANs supported locally : 1005
Number of existing VLANs        : 131
VTP Operating Mode              : Transparent
VTP Domain Name                 : <<VTP Domain>>
VTP Pruning Mode                : Enabled
VTP V2 Mode                     : Disabled
VTP Traps Generation            : Enabled
MD5 digest                      : 0x55 0xC8 0xE5 0x71 0x48 0x6A 0xB7 0x97 
Configuration last modified by 0.0.0.0 at 0-0-00 00:00:00
<<switchname>>#
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/genie/conf/base/device.py", line 498, in genie.conf.base.device.Device.parse
  File "src/genie/metaparser/_metaparser.py", line 271, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/ubuntu/environments/stpaul/lib/python3.5/site-packages/genie/libs/parser/iosxe/show_vtp.py", line 204, in cli
    ret_dict['vtp']['configuration_revision'] = int(m.groupdict()['val'])
KeyError: 'vtp'

**Comment by jeaubin** [comment]
Thanks for reporting it, we will look into it.

**Comment by jeaubin** [comment]
Hi, 

This has been fixed and released.

pip install genie.libs.parser --upgrade

Thanks,

**Comment by jeaubin** [comment]
Can we close this issue? Can you confirm it is now working?

**Comment by jeaubin** [comment]
Closing as it's been fixed - but not confirmation. If any new issue - please comment/raise new issue.
