### ISSUE TITLE
show interface nxos

### ISSUE THREAD

**Issue by Altagot** [CiscoTestAutomation/genieparser#260]
Not a big issue but still:
When show interfaces on nxos you can get for flapping : Last link flapped 15week(s) 5day(s)
Checking the parsing :
```
#Last link flapped 00:07:28
        p18 = re.compile(r'^Last *link *flapped'
                            ' *(?P<last_link_flapped>[a-z0-9\:]+)$')
```
Parenthesis and space are not taken into account:

`#Last link flapped 00:07:28
        p18 = re.compile(r'^Last *link *flapped'
                            ' *(?P<last_link_flapped>[a-z0-9\:\s\(\)]+)$')
`

Trying with this is working. Didn't check other type of devices

**Comment by badalsoyantar** [comment]
Hi,
Can you share sample output with me?

**Comment by badalsoyantar** [comment]
Added this fix.
