### ISSUE TITLE
IOS XE: show isis neighbors broken when no tag is present

### ISSUE THREAD

**Issue by lzuzcak** [CiscoTestAutomation/genieparser#261]
Hello team

The "show isis neighbors" parser is broken for platforms, which do not include tag in first line of output like CSR1000v.

> Tag null:
System Id       Type Interface     IP Address      State Holdtime Circuit Id
XXXX           L2   GiX           X.X.X.X     UP    7        XXXX.01

In case that there is no "Tag" line included in output like on ASR920, parser will crash due to "local variable 'isis_dict' referenced before assignment".
 
> System Id       Type Interface     IP Address      State Holdtime Circuit Id
XXXX           L2   GiX           X.X.X.X     UP    7        XXXX.01

This is caused due to fact, that parser expects that "Tag" line is present in output and sets variable isis_dict only in that case.

[https://github.com/CiscoTestAutomation/genieparser/blob/2fcd6d3e44891551af4b9d05e2c053218ee25c32/src/genie/libs/parser/iosxe/show_isis.py#L60](url)

Code should also handle situation, when "Tag" line is not present in the "show isis neighbors" output.

I hope that you can fix this in future releases.

Thank you

Lubos Zuzcak

**Comment by KamyarZiabari** [comment]
I will open up PR for this soon.

**Comment by KamyarZiabari** [comment]
Hi @lzuzcak 
The fix is released with the latest changes of pyats
please update using 
```pip install --upgrade pyats[full]```

**Comment by lzuzcak** [comment]
Hello @KamyarZiabari 

I have tested the fix, it works fine !

Thank you

Lubos Zuzcak
