### ISSUE TITLE
ios xe - Show interface

### ISSUE THREAD

**Issue by Altagot** [CiscoTestAutomation/genieparser#269]
When using show interfaces (again :)) got : 
`fatal: [switch_test]: FAILED! => {"msg": "parse_genie: '' - Failed to parse command output."}`

checking the interfaces : 
`switch_test# sh int eth2/12
Ethernet2/12 is down (SFP checksum error)
 Dedicated Interface
`

SFP checksum error is not taken into account in the script : 
`p1 = re.compile(r'^(?P<interface>\S+)\s*is\s*(?P<link_state>(down|up))?'
                        r'(administratively\s+(?P<admin_1>(down|up)))?\s*'
                        r'(\(Administratively\s*(?P<admin_2>(down|up))\))?'
                        r'(\(VLAN\/BD\s+is+\s+(down|up)\))?'
                        r'(,\s*line\s+protocol\s+is\s+(?P<line_protocol>\w+))?'
                        r'(,\s+autostate\s+(?P<autostate>\S+))?'
                        r'(\(Link\s+not\s+connected\))?'
                        r'(\(SFP\s+not\s+inserted\))?'
                        r'(\(suspended\(.*\)\))?'
                        r'(\(\S+ErrDisabled\))?'
                        r'(\(.*ACK.*\))?$')`

Same for this :
`switch_test# sh int po2002
port-channel2002 is down (No operational members)
`

**Comment by bastell** [comment]
Hi,
Sorry about the delay. This issue has not been forgotten. I will have a proper status update for you later today.

**Comment by Altagot** [comment]
No problem, thanks by the way for taking this into account.

**Comment by bastell** [comment]
Hi, I've implemented the required changes to the parser. Once they have been accepted I will let you know when a patch is available.
