### ISSUE TITLE
 Route Distinguisher Parse failure

### ISSUE THREAD

**Issue by dorko20** [CiscoTestAutomation/genieparser#27]
Hello,  
I've found a wrong regexp expression under the VRF RD match in the Genie parser lib `show_vrf.py` for IOS-XR.  
In case the RD has a format of `ip_address:number` (e.g.: `172.16.0.1:1009`) , then there is no match.

My proposed solution is to add `\.` to the regexp:
```
Current regexp:
...
            # VRF VRF1; RD 200:1; VPN ID not set
            p1 = re.compile(r'^VRF +(?P<vrf>[\w\-]+); +'
                             'RD +(?P<rd>[\w\s\:\<\>]+); +'
                             'VPN +ID +(?P<vpn_id>[\w\s\:]+)$')
...


New regexp:
...
            # VRF VRF1; RD 200:1; VPN ID not set
            p1 = re.compile(r'^VRF +(?P<vrf>[\w\-]+); +'
                             'RD +(?P<rd>[\w\s\:\<\>\.]+); +'
                             'VPN +ID +(?P<vpn_id>[\w\s\:]+)$')
...
```

**Comment by jeaubin** [comment]
@dorko20  - Would you like to create a Pull request for this - all credits to you :) 

Otherwise we can do it for you.

**Comment by dorko20** [comment]
Ji @jeaubin ,  
thank you for your reply,  
I tried to create a new pull request, but seems like I don't have permissions to do so.  
To be honest I don't have too much experience with Github yet so maybe I am missing something, but I tried the following which didn't work:  

```
git checkout -b pull-request-show-vrf 
git push origin pull-request-show-vrf
remote: Permission to CiscoTestAutomation/genieparser.git denied to dorko20.
fatal: unable to access 'https://github.com/CiscoTestAutomation/genieparser.git/': The requested URL returned error: 403
```  

Please go ahead with pull request creation :)

**Comment by ccieojisan** [comment]
Hi @dorko20 

We fixed the issue and genie v19.8 has been released with the fix.
Could you please upgrade by below command and see if it works?

pip install genie --upgrade

**Comment by tahigash** [comment]
Hi @dorko20 

We fixed the issue and genie v19.8 has been released with the fix.
Could you please upgrade by below command and see if it works?

pip install genie --upgrade

**Comment by dorko20** [comment]
Hi @tahigash ,
I can confirm it is working now, thank you !

**Comment by tahigash** [comment]
Hi @dorko20 
Thanks for the check and reporting the issue again. Closing the issue.
