### ISSUE TITLE
Github Actions tests failing

### ISSUE THREAD

**Issue by qduk** [CiscoTestAutomation/genieparser#272]
It look like the Actions tests are failing due to the new version of pyats. Import error is pictured below. I was able to get the test to run successfully using pyats version 20.8
![image](https://user-images.githubusercontent.com/38091261/94721176-19fddd00-031b-11eb-83c4-0dd00eb6aec4.png)

**Comment by tahigash** [comment]
Hi @qduk thanks for reporting. We've already pushed new package `pyats.aetest` v20.9.1 and rerun the GitHub actions and confirmed no issue after the fix.
https://github.com/CiscoTestAutomation/genieparser/pull/236/checks

Closing this issue.
