### ISSUE TITLE
Show vtp status parser fails when vlan mode set to transparent.

### ISSUE THREAD

**Issue by nathantabailey** [CiscoTestAutomation/genieparser#291]
On cisco 2960CX, 2960X, and 2960S models.  Using ansible and ansible-galaxy role clay584-parse_genie.

Output from switch(es):
switch-2960CX#show vtp status
VTP Version capable             : 1 to 3
VTP version running             : 3
VTP Domain Name                 : testing
VTP Pruning Mode                : Disabled
VTP Traps Generation            : Disabled
Device ID                       : a488.7356.b680

Feature VLAN:
--------------
VTP Operating Mode                : Transparent
Number of existing VLANs          : 5
Number of existing extended VLANs : 0
Maximum VLANs supported locally   : 255

Feature MST:
--------------
VTP Operating Mode                : Client
Configuration Revision            : 0
Primary ID                        : 0000.0000.0000
Primary Description               :
MD5 digest                        :

Relevant ansible-playbook task:

    - name: Set fact with Genie filter plugin
      set_fact:
        vtp_status: "{{ cli_output['stdout'][0] | parse_genie(command='show vtp status', os='ios') }}"

Failure message from playbook task:

TASK [Set fact with Genie filter plugin] *****************************************************************************************************************************************************************************
fatal: [switch-2960X]: FAILED! => {"msg": "parse_genie: Missing keys: [['vtp', 'feature', 'vlan', 'configuration_revision'], ['vtp', 'feature', 'vlan', 'primary_id']] - Failed to parse command output."}

Filter works as anticipated with vlan mode client and server.

**Comment by ThomasJRyan** [comment]
This has been fixed in the latest beta release. You can install it like so:
`pip install --pre genie.libs.parser`
