### ISSUE TITLE
pull request 275 issue

### ISSUE THREAD

**Issue by mgdransfield** [CiscoTestAutomation/genieparser#299]
PR275 seems to have added an incomplete schema in iosxe/show_wireless.py so that make json fails

**Comment by tahigash** [comment]
@mgdransfield thanks for reporting. I'm now looking into this.

**Comment by tahigash** [comment]
thanks for reporting again. fixed on `master` branch.
Please pull latest code on `master` branch and check.

closing this issue. please feel free to reopen if you see the same.
