### ISSUE TITLE
Can't "offline" parse IOS OSPF commands because parser makes additional calls to the device

### ISSUE THREAD

**Issue by jamiecaesar** [CiscoTestAutomation/genieparser#335]
The IOS/IOSXE parsers for OSPF commands make additional calls to the device (via `self.device.execute()`) to gather additional data for the returned output.

This causes problems with "offline" parsing (i.e. You want to use the Genie parsers on a command output gathered by some other means, NOT using pyATS to connect to the device).  The parse_genie filter for Ansible is an example of this:  Ansible uses its own mechanism to pull the command output from the device, and then uses the genie parser library to parse the result and return it to the playbook.

Personally, I have only tried this with `show ip ospf neighbor detail`, but I expect other OSPF parsers may have this same behavior.

Side Note: The NXOS versions of these parsers do not have this behavior.

Example code to reproduce the issue:
```
device = Device("new_device", os='ios')
device.custom.setdefault("abstraction", {})["order"] = ["os"]
device.cli = AttrDict({"execute": None})
parsed_output = device.parse(cmd, output=raw_cli_output)
```

Running this code returns the following traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 584, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/Users/jcaesar/Development/gitlab/playbooks/venv/lib/python3.7/site-packages/genie/libs/parser/iosxe/show_ospf.py", line 3351, in cli
    out = self.device.execute(cmd)
  File "src/pyats/topology/device.py", line 518, in pyats.topology.device.Device.__getattr__
AttributeError: 'Device' object has no attribute 'execute'
```

Looking specifically at the `genie/libs/parser/iosxe/show_ospf.py` file listed in the traceback, the following code is throwing the exception:
```
# Get OSPF process ID from 'show ip ospf interface'
cmd = 'show ip ospf interface {}'.format(interface)
out = self.device.execute(cmd)
```

Since the `Device` object was created as a mock object to access the parsing functionality, there isn't a way to connect to this device to gather more information, and so the parsing fails.

**Comment by KamyarZiabari** [comment]
@jamiecaesar We are addressing the issue, and the adjustments are in Pull requests. Will let you know how to update as soon as the code is merged.

**Comment by jamiecaesar** [comment]
Thank you for the update!

**Comment by KamyarZiabari** [comment]
Hi @jamiecaesar 
I released a beta package for you. Command to install the patch
pip install --upgrade --pre genie.libs.parser
Also If you install the pyats version 20.12 on Wednesday 16th (), you will have these changes as we officially release pyats this month on 15th.

**Comment by KamyarZiabari** [comment]
@jamiecaesar 
For the command to work, and parser to pick it up, you need to run it like below
```parsed_output = device.parse(show ip ospf neighbour detail__, output=raw_cli_output)```
Those double under score at the end of the command, is give you the ability to run this command ```show ip ospf neighbour detail``` in offline mode. We added this only for a few commands as the original ones needed to be connected to an actual device to collect data. 

Let me know if you have question on this.
