### ISSUE TITLE
show_cloudexpress_applications error

### ISSUE THREAD

**Issue by mgdransfield** [CiscoTestAutomation/genieparser#336]
There is an unexpected indent on line 122 in viptela/show_cloudexpress_applications.py recently added.

**Comment by ahersi2-cisco** [comment]
Hi, 

I see the issue, and will push the fix. Thanks for catching that.

Thank you,
Abdurahman

**Comment by Tristou27** [comment]
Hello,

I've add this modification in a recent PR, else the code was in error. It has been merged with #340 

Rgds
Tristan

**Comment by mgdransfield** [comment]
looks fixed, thanks
