### ISSUE TITLE
Regex Denial of Service risk in asa show_inventory

### ISSUE THREAD

**Issue by beatsbears** [CiscoTestAutomation/genieparser#344]
The regex on this line https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/asa/show_inventory.py#L53 is susceptible to reDOS.

An example payload like 
```
Name: "test", DESCR: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```
will cause the function execution to stall for an extremely long time.

I believe this can be fixed by updating the pattern to 
```
r'^Name: +"+(?P<name>.+)"+,* +DESCR:+ "+(?P<description>.+)"$'
```

**Comment by ahersi2-cisco** [comment]
Hi beatsbears,

Thank you for sharing the suggestion! Just to let you know genieparser is open-sourced, and we encourage users to create pull requests with their fixes. If it gets approved we will merge it into our code base. Let me know if this is something that interests you.

Also, the doc below gives instructions on creating pull requests if you need it, thank you!
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

Regards,
Abdurahman

**Comment by ahersi2-cisco** [comment]
Hi beatsbears,

Just following up on your earlier suggestion. I don't believe you submitted a PR so I went ahead to look to make the change myself. However, I don't really see this suggestion as a fix. The regex pattern you provided and the one we currently have won't match the sample output you showed. This would be a failed match. Did you come across a sample output like the one you provided or was that example created by you? If you have a sample output that you came across, we can modify the regex, however at the moment this change doesn't look like a fix. Feel free to let me know, thanks!

**Comment by ahersi2-cisco** [comment]
This issue will be closed, feel free to open it up again if you see any issues
