### ISSUE TITLE
ios - show interfaces

### ISSUE THREAD

**Issue by Altagot** [CiscoTestAutomation/genieparser#352]
When using show interfaces on a port-channel only ( parse | show interface <interface>) the script is adding some informations on the interfaces :
```
               # build connected interface port_channel
                for intf in intfs:
                    if intf not in interface_dict:
                        interface_dict[intf] = {}
                    if 'port_channel' not in interface_dict[intf]:
                        interface_dict[intf]['port_channel'] = {}
                    interface_dict[intf]['port_channel']['port_channel_member'] = True
                    interface_dict[intf]['port_channel']['port_channel_int'] = interface
```
Problem is with that is the mandatory field of the schema does not exist and error is prompt : ansible task failed.
So when using parsing only on dedicated interface, it should not go into that loop.

**Comment by ahersi2-cisco** [comment]
Hi Altagot,

Can you provide the full device output you used to get this error?

Thank you,
Abdurahman

**Comment by ahersi2-cisco** [comment]
Please reopen issue if can provide output.
