### ISSUE TITLE
SchemaMissingKeyError: Missing keys: Error with show switch parser

### ISSUE THREAD

**Issue by wilbeacham85** [CiscoTestAutomation/genieparser#353]
Hey,

When running show switch parser I get the following error

SchemaMissingKeyError: Missing keys: [['switch', 'mac_persistency_wait_time']]

The device is an 2960X and is running code version 15.2(7)E2. The following output is given when by the cli

```
2960X-1_Stack#sh switch 
Switch/Stack Mac Address : 580a.201c.8c00
                                           H/W   Current
Switch#  Role   Mac Address     Priority Version  State 
----------------------------------------------------------
*1       Master 580a.201c.8c00     1      4       Ready               
 2       Member 6cfa.89e9.4480     1      4       Ready      
```

**Comment by ThomasJRyan** [comment]
This has been fixed and will be available for the next release (next week). Thank you very much for bringing this to our attention
