### ISSUE TITLE
nxos - show interfaces

### ISSUE THREAD

**Issue by Altagot** [CiscoTestAutomation/genieparser#356]
Hello,
Message that are not taken into account :
Ethernet1/11 is down (inactive)
Ethernet1/12 is down (Transceiver validation failed)
Ethernet1/13 is down (SFP validation failed)
Ethernet1/13 is down (Channel admin down)

Needs to be add : 
r'(\(inactive\))?'
r'(\(Transceiver\s+validation\s+failed\))?'
r'(\(SFP\s+validation\s+failed\))?'
r'(\(Channel\s+admin\s+down\))?')

**Comment by badalsoyantar** [comment]
Added support for this output.
