### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by itdependsnetworks** [CiscoTestAutomation/genieparser#357]
@ahersi2-cisco as per https://github.com/CiscoTestAutomation/genieparser/pull/348#issuecomment-736011102 the constant is in the incorrect location, and the tests are not passing. 

![image](https://user-images.githubusercontent.com/9260483/101973077-5004ea80-3c03-11eb-9b0c-cf1be4ed63e4.png)

**Comment by ahersi2-cisco** [comment]
I need to modify the github action to use pyats run instead of just running the script, which is why the unit tests are failing here

**Comment by ahersi2-cisco** [comment]
issue fixed
