### ISSUE TITLE
Multiple ShowSystemInternalL2fwderMac

### ISSUE THREAD

**Issue by itdependsnetworks** [CiscoTestAutomation/genieparser#370]
There are two ShowSystemInternalL2fwderMac parsers in NXOS route. It is not clear to me which is the intended version. 

https://github.com/CiscoTestAutomation/genieparser/blob/31f634272b09d7d74ec1f40fe6f94120b1225eee/src/genie/libs/parser/nxos/show_system.py#L248
https://github.com/CiscoTestAutomation/genieparser/blob/31f634272b09d7d74ec1f40fe6f94120b1225eee/src/genie/libs/parser/nxos/show_fdb.py#L348

**Comment by thaixuann** [comment]
Hi @itdependsnetworks ,
Could you please let me know what issue do you have when you are using these 2 parsers?

Thanks,
--Thai.

**Comment by thaixuann** [comment]
Hi @itdependsnetworks,
I removed the duplicated. It will be in the coming release 21.2.
I will resolve this issue.
Thanks,
--Thai.
