### ISSUE TITLE
junos "show chassis hardware" :: local variable 'chassis_inventory_dict' referenced before assignment

### ISSUE THREAD

**Issue by klbnet** [CiscoTestAutomation/genieparser#372]
junos "show chassis hardware" command is not parsing. Error is:
parse_genie: local variable 'chassis_inventory_dict' referenced before assignment

Looked at previous issues and saw genie.libs.parser are usually updated for this issue? 
I have this version currently installed: 
genie.libs.parser (20.12.1b0)

TASK [Get Chassis/Inventory From Device] *****************************************************************
task path: /home/klobue/ansible/reports/deployment-handoff-acx-parse2scr.yml:26
Loading collection ansible.netcommon from /home/klobue/.ansible/collections/ansible_collections/ansible/netcommon
redirecting (type: become) ansible.builtin.enable to ansible.netcommon.enable
<TA1.LAB1.PTN> attempting to start connection
<TA1.LAB1.PTN> using connection plugin ansible.netcommon.netconf
Found ansible-connection at path /home/klobue/ansible/network_ops/.venv/bin/ansible-connection
<TA1.LAB1.PTN> found existing local domain socket, using it!
<TA1.LAB1.PTN>
<TA1.LAB1.PTN> local domain socket path is /home/klobue/.ansible/pc/1a4b94b09b
redirecting (type: action) ansible.builtin.junos to junipernetworks.junos.junos
redirecting (type: action) ansible.builtin.junos to junipernetworks.junos.junos
<TA1.LAB1.PTN> ESTABLISH LOCAL CONNECTION FOR USER: klobue
<TA1.LAB1.PTN> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/klobue/.ansible/tmp/ansible-local-32324su7pj8ju `"&& mkdir "` echo /home/klobue/.ansible/tmp/ansible-local-32324su7pj8ju/ansible-tmp-1609779467.1770523-32399-11158040666792 `" && echo ansible-tmp-1609779467.1770523-32399-11158040666792="` echo /home/klobue/.ansible/tmp/ansible-local-32324su7pj8ju/ansible-tmp-1609779467.1770523-32399-11158040666792 `" )&& sleep 0'
redirecting (type: modules) ansible.builtin.junos_command to junipernetworks.junos.junos_command
Using module file /home/klobue/.ansible/collections/ansible_collections/junipernetworks/junos/plugins/modules/junos_command.py
<TA1.LAB1.PTN> PUT /home/klobue/.ansible/tmp/ansible-local-32324su7pj8ju/tmpt5067wrd TO /home/klobue/.ansible/tmp/ansible-local-32324su7pj8ju/ansible-tmp-1609779467.1770523-32399-11158040666792/AnsiballZ_junos_command.py
<TA1.LAB1.PTN> EXEC /bin/sh -c 'chmod u+x /home/klobue/.ansible/tmp/ansible-local-32324su7pj8ju/ansible-tmp-1609779467.1770523-32399-11158040666792/ /home/klobue/.ansible/tmp/ansible-local-32324su7pj8ju/ansible-tmp-1609779467.1770523-32399-11158040666792/AnsiballZ_junos_command.py && sleep 0'
<TA1.LAB1.PTN> EXEC /bin/sh -c '/home/klobue/ansible/network_ops/.venv/bin/python3 /home/klobue/.ansible/tmp/ansible-local-32324su7pj8ju/ansible-tmp-1609779467.1770523-32399-11158040666792/AnsiballZ_junos_command.py && sleep 0'
<TA1.LAB1.PTN> EXEC /bin/sh -c 'rm -f -r /home/klobue/.ansible/tmp/ansible-local-32324su7pj8ju/ansible-tmp-1609779467.1770523-32399-11158040666792/ > /dev/null 2>&1 && sleep 0'
ok: [TA1.LAB1.PTN] => {
    "attempts": 1,
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "show chassis hardware"
            ],
            "display": null,
            "interval": 1,
            "match": "all",
            "provider": null,
            "retries": 10,
            "rpcs": null,
            "wait_for": null
        }
    },
    "stdout": [
        "Hardware inventory:\nItem             Version  Part number  Serial number     Description\nChassis                                XM3620330008      ACX5448-M\nMidplane         REV 09   650-092523   XM3620330008      ACX5448-M\nPEM 0            REV 05   740-053352   1GD1A131472       JPSU-850W-AC-AFO\nPEM 1          REV 05   740-053352   1GD1A131470       JPSU-850W-AC-AFO\nRouting Engine 0          BUILTIN BUILTIN           RE-ACX-5448\nDFEB            \nFPC 0                     BUILTIN      BUILTIN FPC BUILTIN\n  MIC 0                                                  44x1GE/44x10GE MACSEC\n    PIC 0              BUILTIN      BUILTIN           44x1GE/44x10GE MACSEC\n      Xcvr 0     REV 01   740-031850 AC1947SA1XJ       SFP-LX10\n      Xcvr 23    REV 01   740-031981   K842009445        SFP+-10G-LR\n  MIC 1                                                  24x10/25GE 6x40/100GE\n    PIC 1                 BUILTIN      BUILTIN           24x10/25GE 6x40/100GE\n      Xcvr 0     REV 01   740-061409   1GTQA5350JA       QSFP-100GBASE-LR4-T2\nFan Tray 0                                               Fan Tray ACX5448-M 0, Front to Back Airflow - AFO\nFan Tray 1                                               Fan Tray ACX5448-M 1, Front to Back Airflow - AFO\nFan Tray 2                                               Fan Tray ACX5448-M 2, Front to Back Airflow - AFO\nFan Tray 3                                               Fan Tray ACX5448-M 3, Front to Back Airflow - AFO\nFan Tray 4                                               Fan Tray ACX5448-M 4, Front to Back Airflow - AFO\nFan Tray 5                                               Fan Tray ACX5448-M5, Front to Back Airflow - AFO"
    ],
    "stdout_lines": [
        [
            "Hardware inventory:",
            "Item             Version  Part number  Serial number     Description",
            "Chassis                                XM3620330008      ACX5448-M",
            "Midplane         REV 09   650-092523   XM3620330008      ACX5448-M",
            "PEM 0            REV 05   740-053352   1GD1A131472       JPSU-850W-AC-AFO",
            "PEM 1            REV 05   740-053352   1GD1A131470       JPSU-850W-AC-AFO",
            "Routing Engine 0          BUILTIN      BUILTIN           RE-ACX-5448",
            "DFEB            ",
            "FPC 0                     BUILTIN      BUILTIN           FPC BUILTIN",
            "  MIC 0                                                  44x1GE/44x10GE MACSEC",
            "    PIC 0                 BUILTIN      BUILTIN           44x1GE/44x10GE MACSEC",
            "      Xcvr 0     REV 01   740-031850   AC1947SA1XJ       SFP-LX10",
            "      Xcvr 23    REV 01   740-031981   K842009445        SFP+-10G-LR",
            "  MIC 1                                                  24x10/25GE 6x40/100GE",
            "    PIC 1                 BUILTIN      BUILTIN           24x10/25GE 6x40/100GE",
            "      Xcvr 0     REV 01   740-061409   1GTQA5350JA       QSFP-100GBASE-LR4-T2",
            "Fan Tray 0                                               Fan Tray ACX5448-M 0, Front to BackAirflow - AFO",
            "Fan Tray 1                                               Fan Tray ACX5448-M 1, Front to BackAirflow - AFO",
            "Fan Tray 2                                               Fan Tray ACX5448-M 2, Front to BackAirflow - AFO",
            "Fan Tray 3                                               Fan Tray ACX5448-M 3, Front to BackAirflow - AFO",
            "Fan Tray 4                                               Fan Tray ACX5448-M 4, Front to BackAirflow - AFO",
            "Fan Tray 5                                               Fan Tray ACX5448-M 5, Front to BackAirflow - AFO"
        ]
    ]
}

TASK [Set Chassis/Inventory Fact Genie Filter] ***********************************************************
task path: /home/klobue/ansible/reports/deployment-handoff-acx-parse2scr.yml:34
fatal: [TA1.LAB1.PTN]: FAILED! => {
    "msg": "parse_genie: local variable 'chassis_inventory_dict' referenced before assignment - Failed toparse command output."
}

**Comment by LenzDong** [comment]
Hi, 

Can you please store the device output in a file and send the file to pyats-support-ext@cisco.com
We will take a look and fix the issue.

Thanks,

**Comment by LenzDong** [comment]
update to latest beta package resolve the issue
