### ISSUE TITLE
ios/iosxe "show ip protocols" failing to parse

### ISSUE THREAD

**Issue by TwistByrn** [CiscoTestAutomation/genieparser#378]
parse_genie: ''Device'' object has no attribute ''execute'' - Failed to parse command output.'

    Python 3.8.5
    pyATS/Genie 20.12
    Ansible 2.10.4
    iosv Version 15.6(2)T

**Comment by ThomasJRyan** [comment]
Hello,

This error could be caused by any number of issues. One of the more likely ones is a misconfigured testbed yaml file or you having not connected to your device. Can you give me the process you took that caused this please

**Comment by TwistByrn** [comment]
Thanks for the reply Ryan.

https://github.com/clay584/genie_collection for ansible
Here is the playbook that is being used


---

- name: testing out parse genie
  hosts: ISP-PE2
  gather_facts: False
  connection: local
  collections:
    - clay584.parse_genie
  tasks:
  # - name: Define Provider
  #   set_fact:
  #     provider:
  #       host: "{{ inventory_hostname }}"
  #       username: "{{ ansible_user }}"
  #       password: "{{ ansible_ssh_pass }}"

  - name: Get Data From Device
    ios_command:
      # provider: "{{ provider }}"
      commands:
        - "show ip protocol"
    register: ios_output

  - name: Print Structured Data
    debug:
      msg:
"{{ ios_output['stdout'][0] | clay584.genie.parse_genie(command='show
ip protocol', os='iosxe')  }}"
    delegate_to: localhost

fatal: [ISP-PE2]: FAILED! => {"msg": "parse_genie: 'Device' object has no
attribute 'execute' - Failed to parse command output."}

**Comment by TwistByrn** [comment]
Looks like the Playbook is missing

---

- name: testing out parse genie
  hosts: ISP-PE2
  gather_facts: False
  connection: local
  collections:
    - clay584.genie
  tasks:
  - name: Get Data From Device
    ios_command:
      commands: 
        - "show ip protocol"
    register: ios_output

  - name: Print Structured Data
    debug:
      msg: "{{ ios_output['stdout'][0] | clay584.genie.parse_genie(command='show ip protocol', os='iosxe') }}"
    delegate_to: localhost

**Comment by ThomasJRyan** [comment]
If I'm understanding this, it almost looks as if you aren't using a device at all? In which case you need to manually supply the output through the `output` parameter
