### ISSUE TITLE
iosxr ShowIpInterfaceBrief: parser too strict for vrf_name

### ISSUE THREAD

**Issue by BenoitLarouche27** [CiscoTestAutomation/genieparser#381]
https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/iosxr/show_interface.py#L81

the vrf_name can (at least) have dashed and underscore in their names, but the current regex parser doesn't accept them, causing non-parsed lines, and raising an exception:
`genie.metaparser.util.exceptions.SchemaEmptyParserError: Parser Output is empty`

Example of a more complex line:
`'BVI123                         10.12.34.56    Up              Up       MyOrg-MyGroup_Channel_Zone'`

Suggested new regex for vrf_name, adding `-` and `_`: 
`(?P<vrf_name>[A-Za-z0-9-_:]+)`

**Comment by LenzDong** [comment]
Thank you for reporting the issue.
The fix will be included in v20.1 release on Jan 26
