### ISSUE TITLE
show eigrp neighbor should be type ipaddress and not string

### ISSUE THREAD

**Issue by rohit04saluja** [CiscoTestAutomation/genieparser#383]
```ShowIpv4EigrpNeighbors``` returns ```eigrp_nbr``` as ```str```. Need the nbr address as ```ipaddress.IPv4Address``` or ```ipaddress.IPv6Address``` 

## Actual Output
```
'eigrp_nbr': {
  '1.0.0.1': {
```

## Expected Output
```
'eigrp_nbr`: {
  IPv4Address('1.0.0.1'): {
```

**Comment by tahigash** [comment]
@rohit04saluja what's the matter with string? The change will break someone's script which uses the parser.

**Comment by rohit04saluja** [comment]
Since it's an ip address to perform any ip address operations the string needs to be converted to ```ipaddress.ip_address```. Wouldn't it be better to have it in a standard class?

Similar thoughts for other parameters like time

**Comment by tahigash** [comment]
sorry, currently we prefer to return string instead of object like `IPv4Address` in parsed_output.
if you need something like above, please do after getting string from parsed output.

```
ipaddress.IPv4Address('<ipaddress string>')
