### ISSUE TITLE
iosxe - show ip bgp neighbors {neighbor} received-routes- failed to parse command output

### ISSUE THREAD

**Issue by ogruca** [CiscoTestAutomation/genieparser#396]
Hi All
Thank you for this great contribution, apologies if this is a simple one but i am using this parser above to parse through received routes and getting the error:
"parse_genie: cli() missing 1 required positional argument: 'neighbor' - Failed to parse command output"

This is the parser that i am using in the task.
varx: "{{ yyy.stdout[0] | parse_genie(command='show ip bgp neighbors {neighbor} received-routes', os='iosxe') }}"

ansible 2.10
genie 21.1.3
pyats 21.1

**Comment by danielgraziano** [comment]
@ogruca you need to parse the actual command. An example could be:
`show ip bgp neighbors 192.168.0.1 received-routes`
