### ISSUE TITLE
show interface parser doesn't represent units of speed measurement

### ISSUE THREAD

**Issue by pcorpx** [CiscoTestAutomation/genieparser#397]
Hello! We faced with problem of using data from 'show interface' parser. We'd like to see current speed and bandwidth. But unfortunetly the object we retrieve represents only numerical value and as follows mess up us with the lack of measurement units.
Would you mind to change regexp and add key/value pair to result object?

**Comment by danielgraziano** [comment]
@pcorpx we encourage contribution from the community. Would you be interested in making this enhancement and contributing back? If so please let me know and you can find the information required below:

How to write a parser: https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/writeparser/writeparser.html
Contribution Guidelines: https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/contribute/contribute.html

**Comment by jeaubin** [comment]
@pcorpx  would that be something you are interested? 

Otherwise please provide the device output and more information. You can send it to pyats-support-ext@cisco.com

**Comment by tahigash** [comment]
no update for a while. so closing. please feel free to reopen if this still needs to be fixed.
