### ISSUE TITLE
show cdp neighbors detail - parsing error

### ISSUE THREAD

**Issue by amrit-ma-siu** [CiscoTestAutomation/genieparser#404]
Hi,

Error:
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['index', 4, 'platform'], ['index', 4, 'capabilities']

When looking at the parsing of "show cdp neighbors detail" for IOS-XR, I found that when the Platform has "/" in the detail, it would not parse the Platform and Capabilities.

example:
Platform: cisco ISR4431/K9,  Capabilities: Router Switch IGMP 

Upon further looking into regex101 , (?P<platform>[a-zA-Z\d +\\-\\/]+) adding the character looks to help.

**Comment by LukasMcClelland** [comment]
Hi Amrit, thanks for reaching out and letting us know about this issue. I will be working to fix this

**Comment by kazemy** [comment]
Hi Lukas - Sounds good. thnx!

**Comment by LukasMcClelland** [comment]
A pull request for this fix has been approved and merged. The fix will be included in the next release

**Comment by amrit-ma-siu** [comment]
> A pull request for this fix has been approved and merged. The fix will be included in the next release

Thank you.

**Comment by LukasMcClelland** [comment]
Happy to help!

**Comment by kazemy** [comment]
Thank you @LukasMcClelland  - I will close this issue
