### ISSUE TITLE
IOSXR - show interfaces description - not parsing correctly

### ISSUE THREAD

**Issue by amrit-ma-siu** [CiscoTestAutomation/genieparser#405]
The parser output does not include interfaces which have description containing spaces.

Example:
Gi0/1/1/8          up          up          Link to XYZ

**Comment by RomainGuilloux** [comment]
Hello, 

The "show interfaces descriptions" parser for junos also does not match the following data:

```shell
ge-0/0/0        up    up   BBT link to LABJ2 (ge-0/0/0) - backbone
ge-0/0/0.0      up    up   BBT link to LABJ2 (ge-0/0/0.0) - backbone
ge-0/0/1        up    up   LBT0 link to LABP1 (GigabitEthernet0/0/0/0) - backbone
ge-0/0/1.0      up    up   LBT0 link to LABP1 (GigabitEthernet0/0/0/0) - backbone
```

File identified: 
https://github.com/CiscoTestAutomation/genieparser/blob/afbffe28f69c12d198b4852dabc906afccab212d/src/genie/libs/parser/junos/show_interface.py#L255

https://github.com/CiscoTestAutomation/genieparser/blob/afbffe28f69c12d198b4852dabc906afccab212d/src/genie/libs/parser/iosxr/show_interface.py#L2990

Should be replaced by: 
```python
# for junos
p2 = re.compile(r'^(?P<name>\S+) +(?P<admin_status>\S+) +(?P<oper_status>\S+) +(?P<description>.*)$') 

# for iosxr
p1 = re.compile(r'^(?P<interface>(\S+)[^-]) +(?P<status>\S+) +(?P<protocol>\S+) +(?P<description>.*)$')
```

**Comment by kazemy** [comment]
Hi Amrit and thank you for reaching out. The issue has been resolved and is being reviewed and will be merged after the review process.

**Comment by kazemy** [comment]
Hi Amrit - The review is completed and the PR is merged and it will be available in our next release.
Thank you for bringing this issue to our attentions.
I will close this issue.
