### ISSUE TITLE
NXOS show routing does not match VRFs with non-alphanumeric characters

### ISSUE THREAD

**Issue by seanblundy** [CiscoTestAutomation/genieparser#406]
https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/nxos/show_routing.py#L217

VRF Names such as test-lab will not match against this regex, and as a result, Genie will not catch the routing table.

Example Device Output:
```
MyNexusDevice# show ip route vrf User-VLAN
IP Route Table for VRF "User-VLAN"
'*' denotes best ucast next-hop
'**' denotes best mcast next-hop
'[x/y]' denotes [preference/metric]
'%<string>' in via output denotes VRF <string>

0.0.0.0/0, ubest/mbest: 1/0
    *via 192.168.1.1%Internet, [20/0], 38w2d, bgp-64512, external, tag 65000
10.0.0.0/24, ubest/mbest: 1/0
    *via 169.254.0.1%Server-VLAN, [20/0], 38w2d, bgp-64512, external, tag 65001
10.0.0.10/32, ubest/mbest: 1/0
    *via 169.254.1.1%Legacy-VLAN, [20/0], 38w2d, bgp-64512, external, tag 65002
10.2.0.0/24, ubest/mbest: 1/0
    *via 172.16.0.1%default, [200/0], 02:46:06, bgp-64512, internal, tag 64513 (mpls-vpn)
```

In my limited testing on the Cisco DevNet Sandbox, the following VRF names were valid:
vrf context test!name
vrf context test#name
vrf context test$name
vrf context test*name
vrf context test+name
vrf context test-name
vrf context test.name
vrf context test:name
vrf context test;name
vrf context test=name
vrf context test@name
vrf context test^name
vrf context test_name
vrf context test{name
vrf context test}name

**Comment by LukasMcClelland** [comment]
Hi Sean, thanks for bringing this to our attention. I'm working to fix this issue

**Comment by LukasMcClelland** [comment]
A pull request for this fix has been approved and merged. The fix will be included in the next release

**Comment by LukasMcClelland** [comment]
Closing the issue for now, I will still notify when fix is released

**Comment by LukasMcClelland** [comment]
Fix should be released now 👍
