### ISSUE TITLE
show interface does not show err-disabled state

### ISSUE THREAD

**Issue by wilbeacham85** [CiscoTestAutomation/genieparser#407]
It would be good to parse back the line protocol err-disabled state as its missing

{
   "Te2/0/48": {
      "TenGigabitEthernet2/0/48": {
         "port_channel": {
            "port_channel_member": false
         },
         "enabled": false,
         "line_protocol": "down",
         "oper_status": "down",

9300-stack#show interfaces tenGigabitEthernet 2/0/48
TenGigabitEthernet2/0/48 is down, line protocol is down (err-disabled) 
  Hardware is Ten Gigabit Ethernet, address is ac3a.67ea.35b0 (bia ac3a.67ea.35b0)
  MTU 1500 bytes, BW 1000000 Kbit/sec, DLY 10 usec,

**Comment by kazemy** [comment]
Hi @wilbeacham85 and thank you for reaching out.
Which OS is this issue for? 
Thank you!

**Comment by wilbeacham85** [comment]
This was on IOS-XE 16.12.4 and i have seen this on IOS as well

**Comment by kazemy** [comment]
Hi @wilbeacham85 - A pull request has been submitted to resolve this issue and is being reviewed. I will let you know when the review process if completed.
Thank you!

**Comment by kazemy** [comment]
Hi @wilbeacham85,
The pull request is merged and the fix will be available in our next general release.
Thank you again for bringing this issue to our attention.
I will close this issue!
