### ISSUE TITLE
IOSXR - Genie Diff - not populating correctly - show bgp

### ISSUE THREAD

**Issue by amrit-ma-siu** [CiscoTestAutomation/genieparser#415]
while running Genie Diff for bgp summary, it did not populate the diff result correctly.
It is only showing the first neighbor address and adds all other neighbors' prefix changes diff under it.

Incorrect output:
-------------------------------------
` instance:`
`  default:`
`   vrf:`
`    default:`
`     neighbor:`
`      1111:2222:3333::4444:`
`       address_family:`
`        ipv6 unicast:`
`-        accepted_prefixes: 11`
`+        accepted_prefixes: 22`
`        ipv6 unicast:`
`-        accepted_prefixes: 33`
`+        accepted_prefixes: 44`

Expected output:
-------------------------------------------
` instance:`
`  default:`
`   vrf:`
`    default:`
`     neighbor:`
`      1111:2222:3333::4444:`
`       address_family:`
`        ipv6 unicast:`
`-        accepted_prefixes: 11`
`+        accepted_prefixes: 22`
**`      1111:2222:3333::5555:`
`       address_family:`**
`        ipv6 unicast:`
`-        accepted_prefixes: 33`
`+        accepted_prefixes: 44`

**Comment by danielgraziano** [comment]
Thanks for reporting, I am looking into this.

**Comment by danielgraziano** [comment]
I've got a fix ready. It's being reviewed at the moment. The fix will be released in version 21.4 (unless you would like a beta package before that). Please let me know @amrit-ma-siu

**Comment by amrit-ma-siu** [comment]
> I've got a fix ready. It's being reviewed at the moment. The fix will be released in version 21.4 (unless you would like a beta package before that). Please let me know @amrit-ma-siu

thank you @danielgraziano . I have found the issue with diff with other output (like for interfaces) too. So if you have beta package then i can give it a try before the 21.4 release.

**Comment by danielgraziano** [comment]
@amrit-ma-siu I've released a beta package for genie (version 21.3.2b1). To install it please run `pip install --upgrade --pre genie`

**Comment by danielgraziano** [comment]
Closing - If there are still issues please raise a new issue
