### ISSUE TITLE
[Feature Request] - Parser not found Exception

### ISSUE THREAD

**Issue by renatoalmeidaoliveira** [CiscoTestAutomation/genieparser#419]
When the genie/libs/parser/utils/common.get_parser didn't find the correct parser it raises a simple Exception.
It would be great to have an ParserNotFound Exception.
I could create it on genie/libs/parser/utils/common.py file but don't know if it's the best option.

**Comment by jeaubin** [comment]
Thanks @renatoalmeidaoliveira  for the feedback.

We will consider it.

**Comment by kazemy** [comment]
Hi @renatoalmeidaoliveira  - A pull request has been submitted for this change and is in review. I will let you know when the review is complete and it is merged. Thank you!

**Comment by kazemy** [comment]
Hi @renatoalmeidaoliveira - The pull requested has been merged and the fix will be available after our general release.
Thank you again for bring this into our attention.
I will close this issue!
