### ISSUE TITLE
Feature request for show access-list on ASA

### ISSUE THREAD

**Issue by MikeJames15** [CiscoTestAutomation/genieparser#429]
This is not an bug but a feature request.

I would like to request the implementation of the "show access-list" command on ASAs if that were possible.
Thanks

**Comment by kazemy** [comment]
Hi @MikeJames15,

Thank you for bringing this to our attention. 
As you are aware Genie is open source and many users are contributing to it constantly. 

Our team has created following guides to help users with parser development.
contribute
https://github.com/CiscoTestAutomation/genieparser

Write a parser
https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/writeparser/writeparser.html

There are also many useful external resources.

Creating a pyATS | Genie Parser from SCRATCH:
https://www.youtube.com/watch?v=knxkbWTamBY

We encourage you to proceed and develop your own parser and become part of this growing family.

Thank you again,
Amir
