### ISSUE TITLE
IOS/IOSXE-show ip route summary- parser error

### ISSUE THREAD

**Issue by amrit-ma-siu** [CiscoTestAutomation/genieparser#435]
https://github.com/CiscoTestAutomation/genieparser/blob/0fb5df813b67fa8eb8a029d55f3bed759bc0f578/src/genie/libs/parser/iosxe/show_routing.py#L1878

The regex was not capturing the command output as there was no **space** after _Default-IP-Routing-Table_ on first line itself

`IP routing table name is Default-IP-Routing-Table(0)`

Below looks to help, replacing + with * to count for **_zero space or more_**

`p1 = re.compile(r'^IP +routing +table +name +is +(?P<vrf>\S+) *\((?P<vrf_id>\w+)\)$')`

**Comment by kazemy** [comment]
Hi @amrit-ma-siu - Thank you for reaching out and detailing the issue.
A pull request has been submitted and it is in review.
I will let you know when it is ready for general release.
Amir

**Comment by kazemy** [comment]
Hi @amrit-ma-siu - The PR is merged and will be available in our next general release. Thank you again for letting us know about it.
-Amir
