### ISSUE TITLE
show standby all IOS

### ISSUE THREAD

**Issue by jeparra2010** [CiscoTestAutomation/genieparser#439]
If the name of the interface includes a subinterfaces the parser doesn't seem to work correctly:

GigabitEthernet1/39.760 - Group 32
  State is Active
    13 state changes, last state change 11w5d
  Virtual IP address is 10.95.201.1
  Active virtual MAC address is 0000.0c07.ac20
    Local virtual MAC address is 0000.0c07.ac20 (v1 default)
  Hello time 300 msec, hold time 1 sec
    Next hello sent in 0.160 secs
  Preemption enabled
  Active router is local
  Standby router is 10.95.201.3, priority 80 (expires in 0.896 sec)
  Priority 100 (default 100)
  Group name is "hsrp-Gi1/39.760-32" (default)

GigabitEthernet1/39.1430 - Group 143
  State is Active
    16 state changes, last state change 11w5d
  Virtual IP address is 190.13.103.91
  Active virtual MAC address is 0000.0c07.ac8f
    Local virtual MAC address is 0000.0c07.ac8f (v1 default)
  Hello time 1 sec, hold time 3 sec
    Next hello sent in 0.240 secs
  Preemption enabled
  Active router is local
  Standby router is unknown
  Priority 100 (default 100)
  Group name is "hsrp-Gi1/39.1430-143" (default)
GigabitEthernet1/39.1600 - Group 251
  State is Active
    11 state changes, last state change 11w5d
  Virtual IP address is 10.95.105.105
  Active virtual MAC address is 0000.0c07.acfb
    Local virtual MAC address is 0000.0c07.acfb (v1 default)
  Hello time 300 msec, hold time 1 sec
    Next hello sent in 0.032 secs
  Preemption enabled
  Active router is local
  Standby router is 10.95.105.107, priority 80 (expires in 0.928 sec)
  Priority 100 (default 100)
  Group name is "hsrp-Gi1/39.1600-251" (default)
GigabitEthernet1/39.1600 - Group 251
  State is Active
    11 state changes, last state change 11w5d
  Virtual IP address is 10.95.105.105
  Active virtual MAC address is 0000.0c07.acfb
    Local virtual MAC address is 0000.0c07.acfb (v1 default)
  Hello time 300 msec, hold time 1 sec
    Next hello sent in 0.016 secs
  Preemption enabled
  Active router is local
  Standby router is 10.95.105.107, priority 80 (expires in 0.832 sec)
  Priority 100 (default 100)
  Group name is "hsrp-Gi1/39.1600-251" (default)
GigabitEthernet1/39.1601 - Group 250
  State is Active
    11 state changes, last state change 11w5d
  Virtual IP address is 10.95.105.113
  Active virtual MAC address is 0000.0c07.acfa
    Local virtual MAC address is 0000.0c07.acfa (v1 default)
  Hello time 300 msec, hold time 1 sec
    Next hello sent in 0.096 secs
  Preemption enabled
  Active router is local
  Standby router is 10.95.105.115, priority 80 (expires in 1.104 sec)
  Priority 100 (default 100)
GigabitEthernet1/39.1603 - Group 250
  State is Active
    12 state changes, last state change 11w5d
  Virtual IP address is 10.95.105.129
  Active virtual MAC address is 0000.0c07.acfa
    Local virtual MAC address is 0000.0c07.acfa (v1 default)
  Hello time 300 msec, hold time 1 sec
    Next hello sent in 0.192 secs
  Preemption enabled
  Active router is local
  Standby router is 10.95.105.131, priority 80 (expires in 0.912 sec)
  Priority 100 (default 100)
  Group name is "hsrp-Gi1/39.1603-250" (default)
GigabitEthernet1/39.1605 - Group 162
  State is Standby
    76 state changes, last state change 11w5d
  Virtual IP address is 10.95.108.33
  Active virtual MAC address is 0000.0c07.aca2
    Local virtual MAC address is 0000.0c07.aca2 (v1 default)
  Hello time 300 msec, hold time 1 sec
    Next hello sent in 0.144 secs
  Preemption enabled
  Active router is 10.95.108.35, priority 100 (expires in 0.912 sec)
  Standby router is local
  Priority 80 (configured 80)
  Group name is "hsrp-Gi1/39.1605-162" (default)
GigabitEthernet1/39.1609 - Group 168
  State is Active
    11 state changes, last state change 11w5d
  Virtual IP address is 10.95.109.9
  Active virtual MAC address is 0000.0c07.aca8
    Local virtual MAC address is 0000.0c07.aca8 (v1 default)
  Hello time 1 sec, hold time 3 sec
    Next hello sent in 0.384 secs
  Preemption enabled
  Active router is local
  Standby router is 10.95.109.11, priority 80 (expires in 3.376 sec)
  Priority 100 (default 100)
  Group name is "hsrp-Gi1/39.1609-168" (default)
GigabitEthernet1/40.761 - Group 33
  State is Active
    13 state changes, last state change 11w5d
  Virtual IP address is 10.95.201.9
  Active virtual MAC address is 0000.0c07.ac21
    Local virtual MAC address is 0000.0c07.ac21 (v1 default)
  Hello time 300 msec, hold time 1 sec
    Next hello sent in 0.224 secs
  Preemption enabled
  Active router is local
  Standby router is 10.95.201.11, priority 80 (expires in 0.944 sec)
  Priority 100 (default 100)
  Group name is "hsrp-Gi1/40.761-33" (default)
.
.
.
.
.

and the parser output is:

{"msg": "parse_genie: Missing keys: [['GigabitEthernet1/39.760', 'address_family', 'ipv4', 'version', 1, 'groups', 32, 'group_number'], ['GigabitEthernet1/39.1430', 'address_family', 'ipv4', 'version', 1, 'groups', 143, 'group_number'], ['GigabitEthernet1/39.1600', 'address_family', 'ipv4', 'version', 1, 'groups', 251, 'group_number'], ['GigabitEthernet1/39.1601', 'address_family', 'ipv4', 'version', 1, 'groups', 250, 'group_number'], ['GigabitEthernet1/39.1603', 'address_family', 'ipv4', 'version', 1, 'groups', 250, 'group_number'], ['GigabitEthernet1/39.1605', 'address_family', 'ipv4', 'version', 1, 'groups', 161, 'group_number'], ['GigabitEthernet1/39.1606', 'address_family', 'ipv4', 'version', 1, 'groups', 166, 'group_number'], ['GigabitEthernet1/39.1609', 'address_family', 'ipv4', 'version', 1, 'groups', 168, 'group_number'], ['GigabitEthernet1/40.761', 'address_family', 'ipv4', 'version', 1, 'groups', 33, 'group_number'], ['GigabitEthernet1/40.1602', 'address_family', 'ipv4', 'version', 1, 'groups', 252, 'group_number'], ['GigabitEthernet1/40.1607', 'address_family', 'ipv4', 'version', 1, 'groups', 167, 'group_number'], ['GigabitEthernet1/41.1402', 'address_family', 'ipv4', 'version', 1, 'groups', 82, 'group_number'], ['GigabitEthernet1/41.1407', 'address_family', 'ipv4', 'version', 1, 'groups', 87, 'group_number'], ['GigabitEthernet1/41.1408', 'address_family', 'ipv4', 'version', 1, 'groups', 88, 'group_number']] - Failed to parse command output."}

**Comment by daniMaarouf** [comment]
Thanks for reporting this. The fix has been merged internally and will appear in PyATS 21.5 (end of May).
