### ISSUE TITLE
LLDP Parser: Abbreviated interface name expansion platform differences

### ISSUE THREAD

**Issue by saparikh** [CiscoTestAutomation/genieparser#442]
LLDP Neighbor detail output from an IOS-XR box, connecting to an NX-OS box:

```
------------------------------------------------
Local Interface: TenGigE0/1/0/4/0
Chassis id: abcd.abcd.abcd
Port id: Ethernet1/1
Port Description: foo
System Name: ROUTER_X

System Description:
Cisco Nexus Operating System (NX-OS) Software 7.0(3)I4(5)
TAC support: http://www.cisco.com/tac
Copyright (c) 2002-2016, Cisco Systems, Inc. All rights reserved.

Time remaining: 105 seconds
Hold Time: 120 seconds
System Capabilities: B,R
Enabled Capabilities: B,R
Management Addresses:
  IPv4 address: 10.1.1.1.
```

The matching entry from the NX-OS device:

```
Chassis id: abcd.abcd.abcd
Port id: Te0/1/0/4/0
Local Port id: Eth1/1
Port Description: BAR
System Name: ROUTER_Y
System Description: Cisco IOS XR Software, Version 5.3.4[Default]
Copyright (c) 2018 by Cisco Systems, Inc., ASR9K Series
Time remaining: 92 seconds
System Capabilities: R
Enabled Capabilities: R
Management Address: not advertised
Management Address IPV6: not advertised
Vlan ID: not advertised

```

Using the Genie parsers, the parsed output from the IOS-XR device looks like this (I mapped the fields I cared about to these keys in my code):
```
Local_router: ROUTER_Y
Remote_router: ROUTER_X
Local_Interface: TenGigE0/1/0/4/0
Remote_Interface: Ethernet1/1
```

The parsed output from the NXOS device
```
Local_router: ROUTER_X
Remote_router: ROUTER_Y
Local_Interface: Ethernet1/1
Remote_Interface: TenGigabitEthernet0/1/0/4/0
```

The NX-OS LLDP parser is converting the abbreviated interface name `Te0/1/0/4/0` to `TenGigabitEthernet0/1/0/4/0`. However the IOS-XR LLDP parser is leaving the local interface abbreviated as `TenGigE0/1/0/4/0` since that is a valid interface name on an IOS-XR device.

This inconsistency creates a challenge in validating LLDP neighbor output between devices.

It seems like for the parsing of `show lldp neighbors detail` output, the NX-OS parser could recognize the other end is an IOS-XR device given the `System Description` and map the abbreviated name to the correct interface name.

I recognize that this doesn't work if you are just parsing `show lldp neigbhors`

**Comment by danielgraziano** [comment]
Both of these should be expanded to the full interface name. Assigning @kazemy to look into

**Comment by saparikh** [comment]
@danielgraziano `TenGigabitEthernet0/1/0/4/0` is actually not a valid interface name in IOS-XR. So it should just be expanded to `TenGigE0/1/0/4/0`. If `TenGigE0/1/0/4/0` is also the correct interface name for IOS/IOS-XE and NXOS then the fix would be simple. But if not, the expansion will have to be aware of the other platforms OS.

**Comment by GerriorL** [comment]
https://wwwin-github.cisco.com/pyATS/genieparser/pull/499
