### ISSUE TITLE
Link to list of Genie parsers is broken

### ISSUE THREAD

**Issue by strattner** [CiscoTestAutomation/genieparser#449]
The link is referenced on a number of blog and how-to posts around the web, but also within the documentation here. One example: https://github.com/CiscoTestAutomation/genieparser/blob/master/CODING.md#available-parsers

Link goes to: https://pubhub.devnetcloud.com/media/pyats-packages/docs/genie/genie_libs/#/parsers

And returns 404. With some additional information:
Code: NoSuchKey
Message: The specified key does not exist.
Key: media/pyats-packages/docs/genie/genie_libs/index.html
RequestId: C2WQHHAPH5FMPG1E
HostId: tQ15PGgHbLfPZhi8PJdyDDGz08P9IfkKTu/xDOroWtDYBIvEUGQE0HTiZv5hOUS/LmrDZQ8Kvi4=

**Comment by domachad** [comment]
Hi @strattner, 
Thank you for reporting this issue.
The broken link was fixed.
Please let us know if you encounter any other issues.
