### ISSUE TITLE
NXOS - Show Interface - parsing error

### ISSUE THREAD

**Issue by amrit-ma-siu** [CiscoTestAutomation/genieparser#453]
Few issues, i have come across

**### 1.  Interface not being captured for following down states**

https://github.com/CiscoTestAutomation/genieparser/blob/5dd0f88aa69745c63d439bf8d886fdc22a6ab80e/src/genie/libs/parser/nxos/show_interface.py#L223

we need to add/modify above RegEx to capture following examples

r'(\(VLAN\/BD\s+does\s+not\s+exist\))
r'(\(inactive\))?'
r'(\(Transceiver\s+validation\s+failed\))?'
r'(\(Channel\s+admin\s+down\))?'

examples:
Vlan3378 is down (VLAN/BD does not exist), line protocol is down, autostate enabled
Ethernet1/11 is down (inactive)
Ethernet1/12 is down (Transceiver validation failed)
Ethernet1/13 is down (Channel admin down)

**### 2. Interface description is being captured wrong**

https://github.com/CiscoTestAutomation/genieparser/blob/5dd0f88aa69745c63d439bf8d886fdc22a6ab80e/src/genie/libs/parser/nxos/show_interface.py#L259

This is strange behavior observed only for Vlan description.

From the output of "show interface", details under Vlan interfaces as in below example, we have description which is followed by Internet Address and if, IP Address is not defined, it is followed by MTU/BW/DLY.  For other physical interfaces, it is OK as Internet Address is on separate line.
(this was for NXOS: version 7.0(3)I4(7))

example:

Vlan420 is up, line protocol is up, autostate enabled
  Hardware is EtherSVI, address is 1234.5678.90ab
  Description: VLAN information   Internet Address is 10.10.10.1/24
  MTU 1500 bytes, BW 1000000 Kbit, DLY 10 usec,

   reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation ARPA, loopback not set
  Keepalive not supported
  ARP type: ARPA
  Last clearing of "show interface" counters never
  L3 in Switched:
    ucast: 0 pkts, 0 bytes

**Comment by domachad** [comment]
Hi @amrit-ma-siu, thank you for reporting this issue.

We are working on fixing this parser.
Could you provide a complete example of an output containing "(VLAN/BD does not exist)"?

Thanks in advance.

**Comment by domachad** [comment]
Hi @amrit-ma-siu, the issue was solved and a fix will be available in the next release (version 21.6).
I am closing the issue.
Please let us know if the problem persists or if you encounter any other issues.
