### ISSUE TITLE
Handling of Forward Slash Fails in Dict Obj. Lookup #5

### ISSUE THREAD

**Issue by kiddy94** [CiscoTestAutomation/genieparser#46]
### Code:

```
- name: Testing PyATS

  tasks:

  - name: Read in parse_genie role
    include_role:
      name: clay584.parse_genie

  - name: show interfaces
    ios_command:
      commands:
        - show interfaces
    register: interfaces

  - name: Set Fact Genie Filter
    set_fact: 
      pyats_interfaces: "{{ interfaces['stdout'][0] | parse_genie(command='show interfaces', os='iosxe') }}"

  - name: Debug
    debug:
      var: pyats_interfaces.GigabitEthernet0/0
```

### Expect:
```
 "ansible_facts": {
        "pyats_interfaces": {
            "GigabitEthernet0/0": {
                "arp_timeout": "04:00:00",
                "arp_type": "arpa",
                "auto_negotiate": true,
                "bandwidth": 1000000,
                "counters": {
                    "in_broadcast_pkts": 0,
                    "in_crc_errors": 0,
                    "in_errors": 0,
                    "in_frame": 0,
                    "in_giants": 0, etc.
```

### Getting:
`"pyats_interfaces.GigabitEthernet0/0": "VARIABLE IS NOT DEFINED!: 'dict object' has no attribute 'GigabitEthernet0'"`

It appears it's being treated as an escape character.

**Comment by thaixuann** [comment]
Hello @kiddy94 
Thanks for letting us know the issue. I will look into and let you know when it fixed.

--Thai.

**Comment by kiddy94** [comment]
A user on stackoverflow shared a good workaround:

You have 2 equivalent syntax to address vars inside a dictionaries in ansible:

* The dot notation: 
```
some.var.to.address
```
* The bracket notation:
```
some['var']['to']['address']
```

Both notations can be mixed in the way you want e.g. `some['var']['to'].address`

Although they are equivalent, some cases force you to use the bracket notation.

* when the name of the field comes from a variable e.g. `my_var[item]`
* when the name of the field contains special characters e.g. `my_var['field with spaces']`

You are in this latest case. So replacing your debug line with the following should fix your problem:
```
- name: Debug
  debug:
    var: pyats_interfaces['GigabitEthernet0/0']
```
