### ISSUE TITLE
IOS-XR parser show rpl route-policy

### ISSUE THREAD

**Issue by jeparra2010** [CiscoTestAutomation/genieparser#462]
Route-policy:
!
route-policy OSPF2202BGP
  if tag eq 300 then
    set community DCBQ_VOZ
    set next-hop 10.20.96.53
    set local-preference 330
  elseif tag eq 30 then
    set community DCBQ_VOZ
    set next-hop 10.20.96.53
    set local-preference 310
  endif
end-policy
!
Parser's output:
   "OSPF2202BGP": {
            "statements": {
                "10": {
                    "actions": {
                        "set_community_list": "DCBQ_VOZ",
                        "set_local_pref": 330,
                        "set_next_hop": "10.20.96.53"
                    },
                    "conditions": {} => empty
                },
                "20": {
                    "actions": {
                        "set_community_list": "DCBQ_VOZ",
                        "set_local_pref": 310,
                        "set_next_hop": "10.20.96.53"
                    },
                    "conditions": {} => empty
                }
            }
        },

**Comment by GerriorL** [comment]
Hi @jeparra2010,
Sorry for the delay. It seems like your device output is being parsed correctly as there is no field in the device output that would go into the conditions dictionary, so it being empty is expected.
