### ISSUE TITLE
Show environment parser (IOS) not compatible with all devices.

### ISSUE THREAD

**Issue by ryanpjbyrne** [CiscoTestAutomation/genieparser#467]
`show environment` & `show environment | include {include}` parsers for IOS appear to be not compatible with **some** IOS devices. 

Currently testing against a C2960 Switch where the only options avaliable are:

```
XXXXXXXXXXX# show env ?
  all          Show all environment status
  power        Show power supply status
  temperature  Show temperature status
```
A normal `show environment` isn't usable.
```
XXXXXXXXX#show environment
                      ^
% Invalid input detected at '^' marker.
```

I found this post which may help to illustrate the difference in command between devices : https://shrubbery.net/pipermail/rancid-discuss/2015-September/008695.html

Would love to see a `Show env all` parser for IOS if thats at all possible! 👍

**Comment by LukasMcClelland** [comment]
Hi @ryanpjbyrne, 

Agreed! It would be great to have both options 👍 

Are you interested in make the parser and contributing to the project? Or would you prefer if we tackle it?

**Comment by ryanpjbyrne** [comment]
@LukasMcClelland, more than happy to have a go! Is there a getting started guide/exemplar that I should be following?

**Comment by LukasMcClelland** [comment]
Yes we do, we have a guide https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/writeparser/writeparser.html

There are some videos linked on that page as well. Please let me know if you have any questions
