### ISSUE TITLE
IOSXR -  show processes cpu parser

### ISSUE THREAD

**Issue by maqsshah** [CiscoTestAutomation/genieparser#478]
Hello Team,
I am facing difficulties with "show processes cpu", it seems like broken in a special case `NoneType` when key is missing from `text`, I feel like it is here in [parser/iosxr/show_processes.py](https://github.com/CiscoTestAutomation/genieparser/blob/a882779aa2e54ad58d6f963eed9bc322895d9ac5/src/genie/libs/parser/iosxr/show_processes.py) 
```
# ---- node0_RP0_CPU0 ----
p1 = re.compile(r'^----\s+(?P<location>\S+)\s+----$')
```
my script is:
```
#test.py
import yaml
from genie import testbed

DUT = 'P-9001-1'

#load testbed file, iosxr configured in testbed.yaml
testbed = testbed.load('testbed.yaml')

device = testbed.devices[DUT]

text = """
Wed Jun  2 14:19:28.883 UTC
---- node0_RP0_CPU0 ----
CPU utilization for one minute: 2%; five minutes: 2%; fifteen minutes: 2%
PID    1Min    5Min    15Min Process
1        0%      0%       0% kernel
8195     0%      0%       0% dllmgr
"""

i = device.parse('show processes cpu', output=text)
import pprint
pprint.pprint(i)
```
If we delete `---- node0_RP0_CPU0 ----` in above `test.py` it produces:

```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    i = device.parse('show processes cpu', output=text)
  File "src/genie/conf/base/device.py", line 524, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 557, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/cisco/cxta/workspace/genieparser/src/genie/libs/parser/iosxr/show_processes.py", line 454, in cli
    ret_dict['location'][location].update(
KeyError: 'location'

```
In the absence of any other value in the `text` it does not produce error.

**Comment by LukasMcClelland** [comment]
This is expected behavior. Please see [this line of code in genieparser](https://wwwin-github.cisco.com/pyATS/genieparser/blob/d46d8d9566c4cdbd4ebbef0f891510f98f128075/src/genie/libs/parser/iosxr/show_processes.py#L429).
The parser needs to find output that will match the following regex pattern r'^----\s+(?P<location>\S+)\s+----$'

Parsers are written to be quite specific about the output they expect. 

Are you able to share the device output from the `show processes cpu` command?

**Comment by oianson** [comment]
Hi @LukasMcClelland

I was sent output from 3 different xr devices and they all look the same as the one below. None of them had the line '---- node0_RP0_CPU0 ---'  for the p1 match. 

Could the parser have a default value such as 'cpu' if there's no p1 match? Not sure if the device prompt can be read as the RP and cpu number is there. Though adding complexity, if even possible. 

```
RP/0/RP0/CPU0:ASR9912-D-0603#show processes cpu
Thu Jun 24 15:23:26.181 UTC

CPU utilization for one minute: 3%; five minutes: 3%; fifteen minutes: 3%

PID    1Min    5Min    15Min Process
1        0%      0%       0% kernel
8195     0%      0%       0% dllmgr
12290    0%      0%       0% wd-critical-mon
... 
```

**Comment by LukasMcClelland** [comment]
Ah, perfect. That output was the missing piece 👍 

Thank you for providing that @oianson. @domachad will look into this and fix if needed

**Comment by oianson** [comment]
Thanks @LukasMcClelland 
@domachad could you please share the PR URL once available, I will use it as a learning curve on how to fix such issues.

**Comment by maqsshah** [comment]
@LukasMcClelland @oianson Thank you for taking time solve the issue.

**Comment by LukasMcClelland** [comment]
No problem. Due to scheduling we'll remove @domachad, and we'll get @akhosrav to work on this instead.

We'll put a link to the PR here so you can both see the process :)

**Comment by maqsshah** [comment]
@LukasMcClelland @akhosrav Thank you for solve the issue 🥇 👍

**Comment by akhosrav** [comment]
you are welcome
