### ISSUE TITLE
parser version -->  'platform': {'errored': NotImplementedError()},

### ISSUE THREAD

**Issue by kebced** [CiscoTestAutomation/genieparser#48]
hello

when i do a learn_all, the 'platform' feature not work, since update genie-metaparser

_Successfully installed MarkupSafe-1.1.1 aiohttp-3.6.2 async-timeout-3.0.1 attrs-19.2.0 chardet-3.0.4 dill-0.3.1.1 distro-1.4.0 genie.libs.parser-19.9 genie.metaparser-19.9 idna-2.8 jinja2-2.10.3 junit-xml-1.8 multidict-4.5.2 pathspec-0.6.0 psutil-5.6.3 pyats-19.9.2 pyats.aereport-19.9 pyats.aetest-19.9.1 pyats.async-19.9 pyats.connections-19.9 pyats.datastructures-19.9 pyats.easypy-19.9.3 pyats.kleenex-19.9.1 pyats.log-19.9.1 pyats.reporter-19.9.1 pyats.results-19.9 pyats.tcl-19.9 pyats.topology-19.9 pyats.utils-19.9 pyyaml-5.1.2 requests-2.22.0 setproctitle-1.1.10 six-1.12.0 unicon-19.9 urllib3-1.25.6 wheel-0.33.6 xmltodict-0.12.0 yamllint-1.17.0 yarl-1.3.0_

**my testbed:**
_testbed:
  name: TESTBED
devices:
  R1:
      os: ios
      type: iouxe
      connections:
          console:
              protocol: telnet
              ip: 192.168.248.174
              port: 32769_

**my test code:**
_from genie.conf import Genie

import pprint
import os

eve='/Users/cedric/Devops/RecetteTechnique/testbed.yaml'
testbed=Genie.init(eve)
pprint.pprint (testbed.devices)
rtr = testbed.devices["R1"]
rtr.connect()

Cannot read termcap database;
using dumb terminal settings.
{'R1': <Device R1 at 0x110c78eb8>,
 'R2': <Device R2 at 0x110d3e8d0>}
[2019-10-14 14:14:10,905] +++ R1 logfile /tmp/R1-cli-20191014T141410905.log +++
[2019-10-14 14:14:10,906] +++ Unicon plugin ios +++
Trying 192.168.248.174...

[2019-10-14 14:14:10,940] +++ connection to spawn: telnet 192.168.248.174 32769, id: 4578089000 +++
[2019-10-14 14:14:10,940] connection to R1
Connected to 192.168.248.174.
Escape character is '^]'.
]0;R1
R1#
[2019-10-14 14:14:11,752] +++ initializing handle +++
[2019-10-14 14:14:11,753] +++ R1: executing command 'term length 0' +++
term length 0
R1#
[2019-10-14 14:14:11,949] +++ R1: executing command 'term width 0' +++
term width 0
R1#
[2019-10-14 14:14:12,182] +++ R1: executing command 'show version' +++
show version
Cisco IOS Software, Solaris Software (I86BI_LINUXL2-ADVENTERPRISE-M), Experimental Version 15.1(20131216:211730) [mmen 106]
Copyright (c) 1986-2013 by Cisco Systems, Inc.
Compiled Mon 16-Dec-13 13:50 by mmen

ROM: Bootstrap program is Linux

R1 uptime is 1 day, 9 minutes
System returned to ROM by reload at 0
System image file is "unix:/opt/unetlab/addons/iol/bin/i86bi-linux-l2-adventerprise-15.1b.b"
Last reload reason: Unknown reason

Linux Unix (Intel-x86) processor with 981578K bytes of memory.
Processor board ID 67108880
4 Ethernet interfaces
1 Virtual Ethernet interface
1024K bytes of NVRAM.

Configuration register is 0x0

R1#
[2019-10-14 14:14:12,408] +++ R1: config +++
config term
Enter configuration commands, one per line.  End with CNTL/Z.
R1(config)#no logging console
R1(config)#line console 0
R1(config-line)#exec-timeout 0
R1(config-line)#end
R1#
**info_all=rtr._learn_all()
import pprint
pprint.pprint(info_all)**
{'acl': <Acl object at 0x1112761d0>,
 'arp': <Arp object at 0x111276160>,
 'bgp': <Bgp object at 0x1106ff208>,
 'config': {'errored': LookupError('Could not find genie.libs.ops.config.config.Config for device R1',)},
 'dot1x': <Dot1X object at 0x11073ea90>,
 'eigrp': <Eigrp object at 0x1107cb9e8>,
 'fdb': <Fdb object at 0x1107b4cc0>,
 'hsrp': <Hsrp object at 0x1107b4908>,
 'igmp': <Igmp object at 0x1107d9e10>,
 **'interface': {'errored': TypeError("cli() got an unexpected keyword argument 'intf'",)},**
 'lag': <Lag object at 0x1106f08d0>,
 'lisp': <Lisp object at 0x11073e6d8>,
 'lldp': <Lldp object at 0x110805828>,
 'mcast': <Mcast object at 0x110771550>,
 'mld': {'errored': TypeError("'NoneType' object is not iterable",)},
 'msdp': <Msdp object at 0x110805b00>,
 'nd': {'errored': NotImplementedError()},
 'ntp': <Ntp object at 0x11082a5f8>,
 'ospf': <Ospf object at 0x111f8bba8>,
 'pim': <Pim object at 0x112097278>,
 **'platform': {'errored': NotImplementedError()},**
 'prefix_list': <PrefixList object at 0x1120cc9e8>,
 'rip': <Rip object at 0x1120a1e10>,
 'route_policy': <RoutePolicy object at 0x1120a2668>,
 'routing': <Routing object at 0x1120a20f0>,
 'static_routing': <StaticRouting object at 0x1121065f8>,
 'stp': <Stp object at 0x112058400>,
 'vlan': <Vlan object at 0x112071518>,
 'vrf': <Vrf object at 0x1120eb630>,
 'vxlan': {'errored': NotImplementedError()}}

**>>> print(info_all["platform"].version)**
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'dict' object has no attribute 'version'

**>>> print(info_all["platform"])**
{'errored': NotImplementedError()}_

Cedric

**Comment by thaixuann** [comment]
Hello Cedric,
Would you please provide the output of the ‘platform’ command on this device? The output will help to ensure to understand what caused the issue.

Thanks,

Thai Nguyen
Core Software Group (CSG)  - SSR | Genie
DevX Engineering Community http://devx.cisco.com<http://devx.cisco.com/>

2018 Pioneer Award Winner -
Devx Pervasive Quality Platform with pyATS & Genie

**Comment by thaixuann** [comment]
Hello Cedric,
Would you please forward the outputs of the command on the device to pyats-support-ext@cisco.com.

Thanks,
--Thai.

**Comment by kebced** [comment]
it's OK with iosxe.
thx for you help.
