### ISSUE TITLE
"ShowRouteReceiveProtocolPeerAddressExtensive" Doesn't support IPv6 Addresses with A-F characters.

### ISSUE THREAD

**Issue by ancker010** [CiscoTestAutomation/genieparser#487]
https://github.com/CiscoTestAutomation/genieparser/blob/2e5a98699bb5457cf1777d7af38947124ae13bec/src/genie/libs/parser/junos/show_route.py#L3300

The regex for this parser (and probably others) only match IPv4 addresses, AND IPv6 addresses that do NOT have "a-f" characters.

It will match:
1.1.1.1/24
2001:123::/48

It will NOT match:
2001:123:a::/48

**Comment by ancker010** [comment]
This is fixed in the following PR: #488

**Comment by lsheikal** [comment]
https://github.com/CiscoTestAutomation/genieparser/pull/488
