### ISSUE TITLE
IOSXR- show route afi-all safi-all summary- Dotted ASN not captured

### ISSUE THREAD

**Issue by amrit-ma-siu** [CiscoTestAutomation/genieparser#489]
https://github.com/CiscoTestAutomation/genieparser/blob/73bb15dc83ed90bc38c683e33098e987b843509d/src/genie/libs/parser/iosxr/show_routing.py#L1478

The instance RegEx does not account for dotted ASN.

bgp **65000.65000**                  6176       5          0           1532888

**Comment by domachad** [comment]
Hi @amrit-ma-siu, thank you for reporting this issue.
We will look into it.
Can you provide a complete output that we can use to test the fix?

Thanks in advance

**Comment by amrit-ma-siu** [comment]
here is the sample output


IPv4 Unicast:
-------------
Route Source                     Routes     Backup     Deleted     Memory(bytes)
connected                        7          1          0           1984         
local                            8          0          0           1984         
static                           0          0          0           0            
ospf 65000                       5          0          0           1352         
bgp 65000.65000                  6174       5          0           1532392      
dagr                             0          0          0           0            
Total                            6194       6          0           1537712      


IPv4 Multicast:
---------------
Route Source                     Routes     Backup     Deleted     Memory(bytes)
local                            0          0          0           0            
connected                        0          0          0           0            
Total                            0          0          0           0            


IPv6 Unicast:
-------------
Route Source                     Routes     Backup     Deleted     Memory(bytes)
connected                        7          1          0           2176         
connected l2tpv3_xconnect        0          0          0           0            
local                            8          0          0           2176         
static                           2          0          0           544          
ospf 65000                       7          0          0           2176         
bgp 65000.65000                  36         5          1           11288        
local-srv6 bgp-65000.65000       0          0          0           0            
Total                            60         6          1           18360        


IPv6 Multicast:
---------------
Route Source                     Routes     Backup     Deleted     Memory(bytes)
connected                        0          0          0           0            
local                            0          0          0           0            
Total                            0          0          0           0

**Comment by domachad** [comment]
Hi @amrit-ma-siu thank you for sharing the output.
What error message do you get?
It seems like this parser is not detecting other rows as well

**Comment by amrit-ma-siu** [comment]
Yes other rows are also missing.
I was more concerned with the  **"bgp 65000.65000"** . It appears that Dotted ASN number / instance value is not captured in other parsers like for BGP too. I will separate issue for it.

**Comment by domachad** [comment]
Hi @amrit-ma-siu 
A fix for this pattern was provided and should be available to you in the next release.
Version 21.7 is about to be released, so you won't have to wait too long.

Thank you once again for reporting the issue.
I will close it, but feel free to leave comments or to reopen it if you encounter any problems.
