### ISSUE TITLE
IOSXR - show bgp instance all all all - dotted notation ASN not captured

### ISSUE THREAD

**Issue by amrit-ma-siu** [CiscoTestAutomation/genieparser#492]
following ASN path RegEx needs to be modified to capture Dotted notation.

https://github.com/CiscoTestAutomation/genieparser/blob/73bb15dc83ed90bc38c683e33098e987b843509d/src/genie/libs/parser/iosxr/show_bgp.py#L5007

https://github.com/CiscoTestAutomation/genieparser/blob/73bb15dc83ed90bc38c683e33098e987b843509d/src/genie/libs/parser/iosxr/show_bgp.py#L5056

https://github.com/CiscoTestAutomation/genieparser/blob/73bb15dc83ed90bc38c683e33098e987b843509d/src/genie/libs/parser/iosxr/show_bgp.py#L5077

May be we will need to review other BGP parsers too and allow dot (.) in the ASN number.

**Comment by LukasMcClelland** [comment]
Hi @amrit-ma-siu, thank you for reaching out.

Do you have example device output that you can provide? That way tests can be made and changes can be justified and protected from future changes

**Comment by LukasMcClelland** [comment]
Would you be willing to make these changes yourself and make a contribution to the genieparser repo?

A guide for writing, testing, and contributing parser can be found here https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/writeparser/writeparser.html

**Comment by amrit-ma-siu** [comment]
Yes Lukas, I look forward to contributing to the repo in near future. Meanwhile I will be reporting issues as I encounter them.

**Comment by LukasMcClelland** [comment]
Excellent, looking forward to your contribution! Thank you for letting us know about issues too.

Closing this issue as you'll be contributing the fix 👍

**Comment by amrit-ma-siu** [comment]
Ok, my first PR#502 submitted for the fix  :)
