### ISSUE TITLE
IOSXR - Issue while parsing ISIS data

### ISSUE THREAD

**Issue by yhayatou** [CiscoTestAutomation/genieparser#493]
Hello,

I'm performing some tests with pyATS and I'm not able to learn ISIS feature. 

Seems like it's a parsing issue. I'm attaching the exception file. 

Can you please advise ?

**Envrionment :**
- Python 3.6
- Pyats & Genie 21.6
- IOSXR 6.5.3

Regards,
Hayatou.
[isis_iosxr_bpar830_exception.txt](https://github.com/CiscoTestAutomation/genieparser/files/6869481/isis_iosxr_bpar830_exception.txt)

**Comment by akhosrav** [comment]
@yhayatou 
Hi, can you please send me the expected output too

**Comment by yhayatou** [comment]
Hello @akhosrav ,

Attached, the expected output.

Thanks,
Hayatou.
[Show_isis_interface.txt](https://github.com/CiscoTestAutomation/genieparser/files/6872931/Show_isis_interface.txt)

**Comment by akhosrav** [comment]
@yhayatou 
Thanks will look in to it

**Comment by akhosrav** [comment]
I have checked the parser and it seems there is no error in it, 
would you please confirm if your issue been solved or not?
