### ISSUE TITLE
Add entry_point support for dynamic loading of parsers

### ISSUE THREAD

**Issue by jeremyschulman** [CiscoTestAutomation/genieparser#50]
## User Story

As a creator of genie parsers, I would like to be able to define my own/private python packages that contain parsers, and then dynamically load them into the genie framework using the setuptools entry_point mechanism ([described here](https://setuptools.readthedocs.io/en/latest/setuptools.html#extensible-applications-and-frameworks)).  I would like the behavior to operate as follows:

## General Approach

The entry point values should point to user defined function(s) within their private package.  Genie will call these functions during the initial loading of the framework, at the same time (immediately after) the parser definitions are loaded from the JSON file (stored in the genie distribution).  These user defined functions will be responsible for returning a dictionary of data containing the parser classes to load into the genie framework.

## Example setup.py entry_points definition

````python
# setup.py
# example private package is called idreamofgenie

entry_points={
   "genie.libs.parser": [
      "idreamofgenie": idreamofgenie:load_my_parsers"
   ]
}
````

The above example represents that the `idreamofgenie` package has a function called `load_my_parsers`.

## Example package entry point function
````python
# file: idreamofgenie.__init__.py


# import private parser modules
from idreamofgenie.parsers import iosxe, nxos


def load_my_parsers():
    """
    This function is called during the genie.libs.parser startup to dynamically load
    parsers defined in the this private package.

    Returns
    -------
    dict[list]
        key: <str> - OS name, for example "nxos"
        value: list[class<MetaParser>] - list of parser classes
    """

    return {
        'iosxe': [
            iosxe.show_interface_transceiver.ShowInterfaceTransceiver
        ],
        'nxos': [
            nxos.show_interface_transceiver.ShowInterfaceTransceiver
        ]
    }

````

**Comment by jeaubin** [comment]
Thanks Jeremy,  we will look into it today

**Comment by jeaubin** [comment]
Merged; will be part of the next release. 

Thanks!
