### ISSUE TITLE
traceroute with vrf

### ISSUE THREAD

**Issue by kebced** [CiscoTestAutomation/genieparser#52]
Hi

i can do a traceroute, but i don't find any parameters for traceroute with vrf.
how can i do it ?

Thx.

from genie.conf import Genie
eve='/Users/cedric/Devops/RecetteTechnique/testbed.yaml'
testbed=Genie.init(eve)
rtr = testbed.devices["R1"]
rtr.connect()
rtr.traceroute("2.2.2.2\n")
2019-10-29 10:52:52,654] +++ R1: traceroute +++
traceroute
Protocol [ip]: 
Target IP address: 2.2.2.2
Source address: 
Numeric display [n]: 
Timeout in seconds [3]: 
Probe count [3]: 
Minimum Time to Live [1]: 
Maximum Time to Live [30]: 
Port Number [33434]: 
Loose, Strict, Record, Timestamp, Verbose[none]: 
Type escape sequence to abort.
Tracing the route to 2.2.2.2
VRF info: (vrf in name/id, vrf out name/id)
  1 10.0.13.3 2 msec 3 msec 0 msec
  2 10.0.23.2 2 msec *  2 msec
R1#
'traceroute\r\nProtocol [ip]: \r\nTarget IP address: 2.2.2.2\r\nSource address: \r\nNumeric display [n]: \r\nTimeout in seconds [3]: \r\nProbe count [3]: \r\nMinimum Time to Live [1]: \r\nMaximum Time to Live [30]: \r\nPort Number [33434]: \r\nLoose, Strict, Record, Timestamp, Verbose[none]: \r\nType escape sequence to abort.\r\nTracing the route to 2.2.2.2\r\nVRF info: (vrf in name/id, vrf out name/id)\r\n  1 10.0.13.3 2 msec 3 msec 0 msec\r\n  2 10.0.23.2 2 msec *  2 msec\r\n'

**Comment by karmoham** [comment]
Hi,

We will check it and get back to you.

Thanks,
Karim

**Comment by tahigash** [comment]
Hi @kebced ,

device.traceroute() doesn't not support vrf option at this point. we will see what we can do in next release 19.11 (end of Nov).

Regards,

**Comment by kebced** [comment]
Ok thx

**Comment by tahigash** [comment]
@kebced FYI. We've implemented vrf option of traceroute with pyATS/Genie 19.11 for IOSXE device.

```
>>> dev.traceroute('3.3.3.3', vrf='VRF1')
[2019-12-04 17:16:02,855] +++ R1_xe: traceroute +++
traceroute vrf VRF1
Protocol [ip]:
Target IP address: 3.3.3.3
Ingress traceroute [n]:
Source address or interface:
DSCP Value [0]:
Numeric display [n]:
Resolve AS number in (G)lobal table, (V)RF or(N)one [G]:
Timeout in seconds [3]:
Probe count [3]:
Minimum Time to Live [1]:
Maximum Time to Live [30]:
Port Number [33434]:
Loose, Strict, Record, Timestamp, Verbose[none]:
Type escape sequence to abort.
Tracing the route to 3.3.3.3
VRF info: (vrf in name/id, vrf out name/id)
  1 3.3.3.3 2 msec 1 msec 2 msec
```
