### ISSUE TITLE
IOSXE - show cts role-based permissions fails parsing

### ISSUE THREAD

**Issue by komurzak-cisco** [CiscoTestAutomation/genieparser#521]
The following cli output gives an error when trying to parse it:
```
m-bcp-c9516-01#show cts role-based permissions
IPv4 Role-based permissions from group Invalid to group Invalid:
Permit IP-00
RBACL Monitor All for Dynamic Policies : FALSE
RBACL Monitor All for Configured Policies : FALSE
```

![image](https://user-images.githubusercontent.com/89828894/131451050-2dd1358a-52a5-4744-9444-155d0b3a537e.png)

looks like in file src/genie/libs/parser/iosxe/show_cts.py
lines 1933, 1944 tries to access nonexistent collection key cts_rb_permissions_dict['indexes']

**Comment by danielgraziano** [comment]
@tahigash since you are assigned to review the PR I assigned you here. This will close once the PR is merged

**Comment by tahigash** [comment]
PR is closed due to no update. so closing this as well.
