### ISSUE TITLE
IOSXE - show running-config interface {interface} - missing keys

### ISSUE THREAD

**Issue by urskog84** [CiscoTestAutomation/genieparser#525]
I'm hunting down the "mac-address sticky" in our access switch infra

```
!
interface GigabitEthernet1/0/5
 description arne-44
 switchport port-security mac-address sticky
 switchport port-security mac-address sticky 1020.4bb1.6f2f
 source template USER_NoAuth
!
```

i hope ther parser "show running-config interface {interface}" can find the "sticy mac" and the "source template" in the near future
regars Petter

**Comment by ThomasJRyan** [comment]
When it comes to stuff like this, we like to encourage the community to contribute back to the project. This wouldn't be a difficult addition but the core team can't guarantee a timeline so it's more effective to try patching it in yourself.

It would require a modification to the schema here https://github.com/CiscoTestAutomation/genieparser/blob/f77c9ae118685b64964bf542d86b09d625e08095/src/genie/libs/parser/iosxe/show_run.py#L227

an additional regex pattern here https://github.com/CiscoTestAutomation/genieparser/blob/f77c9ae118685b64964bf542d86b09d625e08095/src/genie/libs/parser/iosxe/show_run.py#L535

and a block of code to handle the regex here https://github.com/CiscoTestAutomation/genieparser/blob/f77c9ae118685b64964bf542d86b09d625e08095/src/genie/libs/parser/iosxe/show_run.py#L1008

Along with a unittest to verify the changes

**Comment by urskog84** [comment]
Open pull request #540
