### ISSUE TITLE
IOSXE - Update BGP Parser

### ISSUE THREAD

**Issue by etiedem** [CiscoTestAutomation/genieparser#531]
Trying to parse the output for: `show ip bgp vpnv4 vrf zone1 community 65000:11111`

```
genie parse "show ip bgp vpnv4 vrf zone1 community 65000:11111" --testbed testbed.yml --devices dot1
{
  "instance": {
    "default": {
      "vrf": {}
    }
  }
}
```

The output should be parsed with the same parser as `show ip bgp`

**Comment by etiedem** [comment]
#538 - I've submitted a pull request for this issue

**Comment by tahigash** [comment]
thanks for opening the PR! we will review the PR. we can track this over the PR. so closing this issue.
