### ISSUE TITLE
Regex not matching in line 99 of show_spanning_tree.py

### ISSUE THREAD

**Issue by aroravansh** [CiscoTestAutomation/genieparser#532]
Error in line 99 of [show_spanning_tree.py](https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/nxos/show_spanning_tree.py):
<img width="763" alt="issue" src="https://user-images.githubusercontent.com/44532230/132082958-4b3e5376-048b-407f-8c90-4742cf2621df.PNG">

The output generated by running the job:
pyats parse "show spanning-tree mst detail" --testbed-file site.yaml 

<img width="473" alt="op" src="https://user-images.githubusercontent.com/44532230/132083030-72f6f62e-a9ca-4322-854d-005657c80e12.PNG">
The regex only supports VLAN range with only 2 mapped pairs whereas the output for the job gives 5 pairs of VLAN ranges

**Comment by aroravansh** [comment]
Please review the attempted fix [here](https://github.com/CiscoTestAutomation/genieparser/pull/533)

**Comment by danielgraziano** [comment]
Reassigned to the assigned pull request reviewers

**Comment by LukasMcClelland** [comment]
Thank you for contributing! Thomas and Lukeman will review and track your PR. 

We'll close this issue and if you have any notes to add, then you can add them to the PR description instead :)
