### ISSUE TITLE
Using a parser offline

### ISSUE THREAD

**Issue by vincentbernat** [CiscoTestAutomation/genieparser#539]
Hey!

I didn't find a way to parse an output without connecting to a device. There is [pyats-genie-command-parse](https://pypi.org/project/pyats-genie-command-parse/) for this purpose, but this is odd to not be able to do it out of the box. I was able to get something with:

    >>> from genie.conf.base import Device
    >>> from genie.libs.parser.utils import get_parser
    >>> device = Device("router", os="iosxr")
    >>> device.custom.setdefault("abstraction", {})["order"] = ["os", "platform"]
    >>> cmd = "show route ipv4 unicast"
    >>> output = """
    ... Tue Oct 29 21:29:10.924 UTC
    ...
    ... O    10.13.110.0/24 [110/2] via 10.12.110.1, 5d23h, GigabitEthernet0/0/0/0.110
    ... """
    >>> parser, _ = get_parser(cmd, device)
    >>> device.parse(cmd, output=output)

It would be nice to not have to hack the device to make it work offline.

**Comment by vincentbernat** [comment]
It also works with the one I have put. It's just that it is not really documented. It would be nicer to not try to fetch from the device when `output` is provided to `device.parse()`.

**Comment by domachad** [comment]
I am sorry, I understood that it was not working for you.
You are right, this will be added to the documentation.

Thank you for reporting it.
