### ISSUE TITLE
Show ip ospf database opaque-area errors when we have Unnumbered links and multiple areas

### ISSUE THREAD

**Issue by phongere** [CiscoTestAutomation/genieparser#547]
Seeing errors with below conditions
1. Unnumbered point to point links which gives local and remote interface id which is not a sub tlv.
2. When multiple areas are there the current code node setting address family properly which causes error

**Comment by omehrabi** [comment]
Hi, 
Could you provide more inf. what error are you seeing. is it parser errors or something else? could you provide log from your test?

**Comment by phongere** [comment]
>>> rtr1.parse('show ip ospf database opaque-area self-originate')

2021-09-27 18:30:06,299: %UNICON-INFO: +++ R1 with alias 'a': executing command 'show ip ospf database opaque-area self-originate' +++
show ip ospf database opaque-area self-originate

            OSPF Router with ID (1.1.1.1) (Process ID 100)

                Type-10 Opaque Area Link States (Area 0)

  LS age: 1673
  Options: (No TOS-capability, DC)
  LS Type: Opaque Area Link
  Link State ID: 1.0.0.0
  Opaque Type: 1 (Traffic Engineering)
  Opaque ID: 0
  Advertising Router: 1.1.1.1
  LS Seq Number: 8000000E
  Checksum: 0x3EDE
  Length: 28
  Fragment number : 0

    MPLS TE router ID : 1.1.1.1

    Number of Links : 0

  LS age: 1673
  Options: (No TOS-capability, DC)
  LS Type: Opaque Area Link
  Link State ID: 1.0.0.25
  Opaque Type: 1 (Traffic Engineering)
  Opaque ID: 25
  Advertising Router: 1.1.1.1
  LS Seq Number: 8000000E
  Checksum: 0xDD6
  Length: 120
  Fragment number : 25

    Link connected to Point-to-Point network
      Link ID : 1.1.1.6
      Admin Metric : 2
      Maximum bandwidth : 125000000
      Affinity Bit : 0x80000001
      Local Interface ID : 21
      Remote Interface ID : 20
      IGP Metric : 1
      Extended Affinity : 0x 80000001
      Unidir Link Avg Delay : 10, Anomalous : no
      Unidir Link Min Delay : 10, Unidir Link Max Delay : 10, Anomalous : no
      Unidir Link Delay Variance : 0

    Number of Links : 1

  LS age: 1673
  Options: (No TOS-capability, DC)
  LS Type: Opaque Area Link
  Link State ID: 4.0.0.0
  Opaque Type: 4 (Router Information)
  Opaque ID: 0
  Advertising Router: 1.1.1.1
  LS Seq Number: 80000016
  Checksum: 0x2126
  Length: 76

    TLV Type: Router Information
    Length: 4
    Capabilities:
      Graceful Restart Helper
      Stub Router Support

    TLV Type: Segment Routing Algorithm
    Length: 2
      Algorithm: SPF
      Algorithm: Strict SPF

    TLV Type: Segment Routing Range
    Length: 12
      Range Size: 8000

      Sub-TLV Type: SID/Label
      Length: 3
        Label: 16000

    TLV Type: Segment Routing Node MSD
    Length: 2
      Sub-type: Node Max Sid Depth, Value: 16

    TLV Type: Segment Routing Local Block
    Length: 12
      Range Size: 1000

      Sub-TLV Type: SID/Label
      Length: 3
        Label: 15000

  LS age: 1673
  Options: (No TOS-capability, DC)
  LS Type: Opaque Area Link
  Link State ID: 7.0.0.0
  Opaque Type: 7 (Extended Prefix)
  Opaque ID: 0
  Advertising Router: 1.1.1.1
  LS Seq Number: 80000013
  Checksum: 0x8478
  Length: 56

    TLV Type: Extended Prefix
    Length: 32
      Prefix    : 1.1.1.1/32
      AF        : 0
      Route-type: Intra
      Flags     : N-bit

      Sub-TLV Type: Prefix SID
      Length: 8
        Flags : None
        MTID  : 0
        Algo  : SPF
        SID   : 1

      Sub-TLV Type: Prefix SID
      Length: 8
        Flags : None
        MTID  : 0
        Algo  : Strict SPF
        SID   : 101

  LS age: 1673
  Options: (No TOS-capability, DC)
  LS Type: Opaque Area Link
  Link State ID: 7.0.0.1
  Opaque Type: 7 (Extended Prefix)
  Opaque ID: 1
  Advertising Router: 1.1.1.1
  LS Seq Number: 8000000E
  Checksum: 0xB8D4
  Length: 44

    TLV Type: Extended Prefix
    Length: 20
      Prefix    : 1.1.1.11/32
      AF        : 0
      Route-type: Inter
      Flags     : N-bit, A-bit

      Sub-TLV Type: Prefix SID
      Length: 8
        Flags : None
        MTID  : 0
        Algo  : Strict SPF
        SID   : 111

  LS age: 1673
  Options: (No TOS-capability, DC)
  LS Type: Opaque Area Link
  Link State ID: 8.0.0.21
  Opaque Type: 8 (Extended Link)
  Opaque ID: 21
  Advertising Router: 1.1.1.1
  LS Seq Number: 80000011
  Checksum: 0x1337
  Length: 152

    TLV Type: Extended Link
    Length: 128
    Link connected to : another Router (point-to-point)
    (Link ID) Neighboring Router ID: 1.1.1.6
    (Link Data) Interface IP address: 0.0.0.21

      Sub-TLV Type: Adj SID
      Length : 7
        Flags  : L-Bit, V-bit
        MTID   : 0
        Weight : 0
        Label  : 17

      Sub-TLV Type: Adj SID
      Length : 7
        Flags  : L-Bit, V-bit, B-bit
        MTID   : 0
        Weight : 0
        Label  : 19

      Sub-TLV Type: Local / Remote Intf ID
        Local Interface ID   : 21
        Remote Interface ID   : 20

      Sub-TLV Type: ASLA
      Length: 60
        SABM Length: 4
        UDABM Length: 0
        Standard App ID: SR TE
        SABM Value: 0x40000000

        Sub-Sub-TLV Type: Unidirectional Link Delay
        Length: 4
        Delay: 10 usec, Anomalous: no

        Sub-Sub-TLV Type: Min/Max Unidirectional Link Delay
        Length: 8
        Delay Minimum: 10 usec, Maximum: 10 usec, Anomalous: no

        Sub-Sub-TLV Type: Unidirectional Link Delay Variance
        Length: 4
        Delay Variance: 0 usec

        Sub-Sub-TLV Type: Admin Group (AG)
        Length: 4
        AG Value: 0x80000001

        Sub-Sub-TLV Type: Extended Admin Group (EAG)
        Length: 4
        EAG Value: 0x80000001

        Sub-Sub-TLV Type: TE Metric
        Length: 4
        TE Metric: 2


                Type-10 Opaque Area Link States (Area 1)

  LS age: 1673
  Options: (No TOS-capability, DC)
  LS Type: Opaque Area Link
  Link State ID: 1.0.0.0
  Opaque Type: 1 (Traffic Engineering)
  Opaque ID: 0
  Advertising Router: 1.1.1.1
  LS Seq Number: 8000000E
  Checksum: 0x3EDE
  Length: 28
  Fragment number : 0

    MPLS TE router ID : 1.1.1.1

    Number of Links : 0

  LS age: 1673
  Options: (No TOS-capability, DC)
  LS Type: Opaque Area Link
  Link State ID: 4.0.0.0
  Opaque Type: 4 (Router Information)
  Opaque ID: 0
  Advertising Router: 1.1.1.1
  LS Seq Number: 80000016
  Checksum: 0x91A5
  Length: 76

    TLV Type: Router Information
    Length: 4
    Capabilities:
      Graceful Restart Helper
      Stub Router Support
      Traffic Engineering Support

    TLV Type: Segment Routing Algorithm
    Length: 2
      Algorithm: SPF
      Algorithm: Strict SPF

    TLV Type: Segment Routing Range
    Length: 12
      Range Size: 8000

      Sub-TLV Type: SID/Label
      Length: 3
        Label: 16000

    TLV Type: Segment Routing Node MSD
    Length: 2
      Sub-type: Node Max Sid Depth, Value: 16

    TLV Type: Segment Routing Local Block
    Length: 12
      Range Size: 1000

      Sub-TLV Type: SID/Label
      Length: 3
        Label: 15000

  LS age: 1673
  Options: (No TOS-capability, DC)
  LS Type: Opaque Area Link
  Link State ID: 7.0.0.0
  Opaque Type: 7 (Extended Prefix)
  Opaque ID: 0
  Advertising Router: 1.1.1.1
  LS Seq Number: 80000013
  Checksum: 0xA566
  Length: 44

    TLV Type: Extended Prefix
    Length: 20
      Prefix    : 1.1.1.11/32
      AF        : 0
      Route-type: Intra
      Flags     : N-bit

      Sub-TLV Type: Prefix SID
      Length: 8
        Flags : None
        MTID  : 0
        Algo  : Strict SPF
        SID   : 111

  LS age: 1673
  Options: (No TOS-capability, DC)
  LS Type: Opaque Area Link
  Link State ID: 7.0.0.1
  Opaque Type: 7 (Extended Prefix)
  Opaque ID: 1
  Advertising Router: 1.1.1.1
  LS Seq Number: 8000000E
  Checksum: 0x97E6
  Length: 56

    TLV Type: Extended Prefix
    Length: 32
      Prefix    : 1.1.1.1/32
      AF        : 0
      Route-type: Inter
      Flags     : N-bit, A-bit

      Sub-TLV Type: Prefix SID
      Length: 8
        Flags : None
        MTID  : 0
        Algo  : SPF
        SID   : 1

      Sub-TLV Type: Prefix SID
      Length: 8
        Flags : None
        MTID  : 0
        Algo  : Strict SPF
        SID   : 101

  LS age: 1673
  Options: (No TOS-capability, DC)
  LS Type: Opaque Area Link
  Link State ID: 7.0.0.2
  Opaque Type: 7 (Extended Prefix)
  Opaque ID: 2
  Advertising Router: 1.1.1.1
  LS Seq Number: 8000000F
  Checksum: 0x6118
  Length: 56

    TLV Type: Extended Prefix
    Length: 32
      Prefix    : 1.1.1.2/32
      AF        : 0
      Route-type: Inter
      Flags     : N-bit

      Sub-TLV Type: Prefix SID
      Length: 8
        Flags : NP-bit
        MTID  : 0
        Algo  : SPF
        SID   : 2

      Sub-TLV Type: Prefix SID
      Length: 8
        Flags : NP-bit
        MTID  : 0
        Algo  : Strict SPF
        SID   : 102

  LS age: 1673
  Options: (No TOS-capability, DC)
  LS Type: Opaque Area Link
  Link State ID: 7.0.0.3
  Opaque Type: 7 (Extended Prefix)
  Opaque ID: 3
  Advertising Router: 1.1.1.1
  LS Seq Number: 8000000E
  Checksum: 0xA7CE
  Length: 56

    TLV Type: Extended Prefix
    Length: 32
      Prefix    : 1.1.1.3/32
      AF        : 0
      Route-type: Inter
      Flags     : N-bit

      Sub-TLV Type: Prefix SID
      Length: 8
        Flags : NP-bit
        MTID  : 0
        Algo  : SPF
        SID   : 3

      Sub-TLV Type: Prefix SID
      Length: 8
        Flags : NP-bit
        MTID  : 0
        Algo  : Strict SPF
        SID   : 103

  LS age: 1673
  Options: (No TOS-capability, DC)
  LS Type: Opaque Area Link
  Link State ID: 7.0.0.4
  Opaque Type: 7 (Extended Prefix)
  Opaque ID: 4
  Advertising Router: 1.1.1.1
  LS Seq Number: 8000000E
  Checksum: 0xEB86
  Length: 56

    TLV Type: Extended Prefix
    Length: 32
      Prefix    : 1.1.1.4/32
      AF        : 0
      Route-type: Inter
      Flags     : N-bit

      Sub-TLV Type: Prefix SID
      Length: 8
        Flags : NP-bit
        MTID  : 0
        Algo  : SPF
        SID   : 4

      Sub-TLV Type: Prefix SID
      Length: 8
        Flags : NP-bit
        MTID  : 0
        Algo  : Strict SPF
        SID   : 104

  LS age: 1673
  Options: (No TOS-capability, DC)
  LS Type: Opaque Area Link
  Link State ID: 7.0.0.5
  Opaque Type: 7 (Extended Prefix)
  Opaque ID: 5
  Advertising Router: 1.1.1.1
  LS Seq Number: 8000000E
  Checksum: 0xC8FA
  Length: 44

    TLV Type: Extended Prefix
    Length: 20
      Prefix    : 1.1.1.14/32
      AF        : 0
      Route-type: Inter
      Flags     : N-bit

      Sub-TLV Type: Prefix SID
      Length: 8
        Flags : NP-bit
        MTID  : 0
        Algo  : Strict SPF
        SID   : 114

  LS age: 1673
  Options: (No TOS-capability, DC)
  LS Type: Opaque Area Link
  Link State ID: 7.0.0.6
  Opaque Type: 7 (Extended Prefix)
  Opaque ID: 6
  Advertising Router: 1.1.1.1
  LS Seq Number: 8000000F
  Checksum: 0x2448
  Length: 56

    TLV Type: Extended Prefix
    Length: 32
      Prefix    : 1.1.1.5/32
      AF        : 0
      Route-type: Inter
      Flags     : N-bit

      Sub-TLV Type: Prefix SID
      Length: 8
        Flags : NP-bit
        MTID  : 0
        Algo  : SPF
        SID   : 5

      Sub-TLV Type: Prefix SID
      Length: 8
        Flags : NP-bit
        MTID  : 0
        Algo  : Strict SPF
        SID   : 105

  LS age: 1673
  Options: (No TOS-capability, DC)
  LS Type: Opaque Area Link
  Link State ID: 7.0.0.7
  Opaque Type: 7 (Extended Prefix)
  Opaque ID: 7
  Advertising Router: 1.1.1.1
  LS Seq Number: 8000000F
  Checksum: 0x68FF
  Length: 56

    TLV Type: Extended Prefix
    Length: 32
      Prefix    : 1.1.1.6/32
      AF        : 0
      Route-type: Inter
      Flags     : N-bit

      Sub-TLV Type: Prefix SID
      Length: 8
        Flags : NP-bit
        MTID  : 0
        Algo  : SPF
        SID   : 6

      Sub-TLV Type: Prefix SID
      Length: 8
        Flags : NP-bit
        MTID  : 0
        Algo  : Strict SPF
        SID   : 106

R1#
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/auto/ospf-india/bgl/ats5.3.0/ats_easy/phongere/pyats_genie_dev/lib/python3.6/site-packages/genie/conf/base/device.py", line 525, in parse
    alias, context)
  File "/auto/ospf-india/bgl/ats5.3.0/ats_easy/phongere/pyats_genie_dev/lib/python3.6/site-packages/genie/conf/base/device.py", line 551, in _get_parser_output
    out = parser(getattr(self, alias), context=context).parse(**copy)
  File "/auto/ospf-india/bgl/ats5.3.0/ats_easy/phongere/pyats_genie_dev/lib/python3.6/site-packages/genie/metaparser/_metaparser.py", line 272, in parse
    output = call(**kwargs)
  File "/auto/ospf-india/bgl/ats5.3.0/ats_easy/phongere/pyats_genie_dev/lib/python3.6/site-packages/genie/libs/parser/iosxe/show_ospf.py", line 10236, in cli
    return super().cli(db_type='opaque', out=output)
  File "/auto/ospf-india/bgl/ats5.3.0/ats_easy/phongere/pyats_genie_dev/lib/python3.6/site-packages/genie/libs/parser/iosxe/show_ospf.py", line 6251, in cli
    sub_tlv_types_dict['local_interface_id'] = local_interface_id
UnboundLocalError: local variable 'sub_tlv_types_dict' referenced before assignment
>>>

**Comment by GerriorL** [comment]
A fix has been written and it will be available in the next release. Thank you for bringing this to our attention.
