### ISSUE TITLE
IOS-XE Parser for "Show ip sla statistics *" CLI - does not exists

### ISSUE THREAD

**Issue by kpriyas** [CiscoTestAutomation/genieparser#551]
Could not find parser for "show ip sla statistics" related CLI in IOSXE platform

**Comment by GerriorL** [comment]
Hi kpriyas,

Thank you for bringing this to our attention. It looks like this parser doesn't exist yet, but we're always adding new ones. If you're able to provide a device output we can add it to our development queue. We also welcome contributions if you'd like to write it.

**Comment by kpriyas** [comment]
Hi Liam Gerrior,

Yes we are working on the parsers to cover "show ip sla statistics *" related CLI. Will commit it once local verification done.
