### ISSUE TITLE
'show mpls forwarding-table labels <labels>' parser is broken in 21.9 version

### ISSUE THREAD

**Issue by phongere** [CiscoTestAutomation/genieparser#561]
Our script is using 'show mpls forwarding-table labels <labels>' parser and its broken in 21.9.  Below is the comparison for 21.6 and 21.9. Please note that 'local_label', 'outgoing_label_or_vc' and 'prefix_or_tunnel_id' show as None in 21.9. The issue is seen only in the case where the output is split in 2 lines using '\'

With 21.6

>>> rtr5.parse('show mpls forwarding-table labels 16123')

2021-10-19 13:31:46,128: %UNICON-INFO: +++ XE_OSPF_R5 with alias 'a': executing command 'show mpls forwarding-table labels 16123' +++
show mpls forwarding-table labels 16123
Local      Outgoing   Prefix           Bytes Label   Outgoing   Next Hop    
Label      Label      or Tunnel Id     Switched      interface              
16123      16123      123.123.123.123/32   \
                                       0             Gi0/0/4    4.5.0.5     
XE_OSPF_R5#
{'vrf': {'default': {'local_label': {16123: {'outgoing_label_or_vc': {'16123': {'prefix_or_tunnel_id': {'123.123.123.123/32': {'outgoing_interface': {'GigabitEthernet0/0/4': {'next_hop': '4.5.0.5', 'bytes_label_switched': 0}}}}}}}}}}}
>>> 
[pyats_latest] bgl-ads-778:175> pip list | grep genie                                                                        genie                        21.6.1
genie.libs.clean             21.6
genie.libs.conf              21.6
genie.libs.filetransferutils 21.6
genie.libs.health            21.6
genie.libs.ops               21.6
genie.libs.parser            21.6
genie.libs.robot             21.6
genie.libs.sdk               21.6
genie.telemetry              21.6
genie.trafficgen             21.6
[pyats_latest] bgl-ads-778:176> 

With 21.9

>>> rtr5.parse('show mpls forwarding-table labels 16123')

2021-10-19 13:43:01,132: %UNICON-INFO: +++ XE_OSPF_R5 with alias 'a': executing command 'show mpls forwarding-table labels 16123' +++
show mpls forwarding-table labels 16123
Local      Outgoing   Prefix           Bytes Label   Outgoing   Next Hop    
Label      Label      or Tunnel Id     Switched      interface              
16123      16123      123.123.123.123/32   \
                                       0             Gi0/0/4    4.5.0.5     
XE_OSPF_R5#
{'vrf': {'default': {'local_label': {'No Label': {'outgoing_label_or_vc': {'No Label': {'prefix_or_tunnel_id': {'None': {'outgoing_interface': {'GigabitEthernet0/0/4': {'next_hop': '4.5.0.5', 'bytes_label_switched': 0}}}}}}}}}}}

[pyats_21_9] bgl-ads-778:212> pip list | grep genie
genie                        21.9
genie.libs.cisco             21.9
genie.libs.clean             21.9.3
genie.libs.conf              21.9
genie.libs.filetransferutils 21.9
genie.libs.health            21.9.1
genie.libs.ops               21.9
genie.libs.parser            21.9
genie.libs.robot             21.9
genie.libs.sdk               21.9
genie.telemetry              21.9
genie.trafficgen             21.9
[pyats_21_9] bgl-ads-778:213>

**Comment by phongere** [comment]
Is this released in latest? We are still seeing failure in latest.

**Comment by omehrabi** [comment]
did you update to 21.10?

**Comment by phongere** [comment]
I still see there is a problem with flex algo labels. The prefix key is '0-1.1.1.1/32-4'. Should we not extract just the prefix from it.  Its difficult to verify if we keep as it is.

502:  +------------------------------------------------------------------------------+
503:  |                 Starting PostProcessor-4 'verify_mpls_fwdg'                  |
504:  +------------------------------------------------------------------------------+
505:  Checking for MPLS local label  16201 on rtr Device R4, type IOL
506:  +++ R4 with via 'a': executing command 'show mpls forwarding-table labels 16201' +++
show mpls forwarding-table labels 16201
Local      Outgoing   Prefix           Bytes Label   Outgoing   Next Hop
Label      Label      or Tunnel Id     Switched      interface
16201      16201      0-1.1.1.1/32-4 (3:20:128:0)   \
                                       0             Et0/0      3.4.0.3
R4#
508:  MPLS FWDG- {'vrf': {'default': {'local_label': {16201: {'outgoing_label_or_vc': {'16201': {'prefix_or_tunnel_id': {'0-1.1.1.1/32-4': {'outgoing_interface': {'Ethernet0/0': {'next_hop': '3.4.0.3', 'bytes_label_switched': 0, 'flexalgo_info': {'pdb_index': 3, 'metric': 20, 'algo': 128, 'via_srms': 0}}}}}}}}}}}}
