### ISSUE TITLE
Incorrect parsing of NXOS show interface status

### ISSUE THREAD

**Issue by dgoodenberger** [CiscoTestAutomation/genieparser#565]
show run interface command output for correctly and incorrectly parsed interfaces:

interface Ethernet116/1/2
  description fubarwts02
  switchport access vlan 1764
  spanning-tree port type edge

interface Ethernet116/1/14
  description fubar10 10.1.72.111
  switchport mode trunk
  switchport trunk allowed vlan 1772
  spanning-tree port type edge trunk
  channel-group 613

show interface status command output for above interfaces:

--------------------------------------------------------------------------------
Port          Name               Status    Vlan      Duplex  Speed   Type
--------------------------------------------------------------------------------
...
Eth116/1/2    fubarwts02        connected 1764      full    a-1000
...
Eth116/1/14   fubar10 10.1.72.1 connected trunk     full    a-1000

Correctly parsed show interface status output:

'Ethernet116/1/2': {'duplex_code': 'full',
                    'name': 'fubarwts02',
                    'port_speed': 'a-1000',
                    'status': 'connected',
                    'vlan': '1764'},

Incorrectly parsed show interface status output:

'Ethernet116/1/14': {'duplex_code': 'trunk',
                     'name': 'fubar10',
                     'port_speed': 'full',
                     'status': '10.1.72.1',
                     'type': 'a-1000',
                     'vlan': 'connected'},

**Comment by ThomasJRyan** [comment]
This is a regex issue in the parser. For errors like these we like to encourage the community to assist in fixing them. I can look into it, though I can't give an exact timeline as to when it'll be resolved

**Comment by ThomasJRyan** [comment]
No response from user. Closing
