### ISSUE TITLE
Data loss when parsing ASA `show route` output

### ISSUE THREAD

**Issue by thismatters** [CiscoTestAutomation/genieparser#569]
Hello,

I'm parsing some `show route` output out in the wild, and I stumbled across what seems like a limitation of the schema.

This is an excerpt from `show route` on "device-a":

```
S*       0.0.0.0 0.0.0.0 [1/0] via 192.2.0.1, Outside-Port-Channel
...
S    0.0.0.0 0.0.0.0 [255/0] via 10.98.126.1, Inside-Port-Channel tunneled 
```

The parsed output from this config omits the top row because the CIDR coincides with the bottom row:

```
...
"routes": {
    "0.0.0.0/0": {
        "candidate_default": false,
        "active": true,
        "route": "0.0.0.0/0",
        "source_protocol_codes": "S",
        "source_protocol": "static",
        "metric": 0,
        "route_preference": 255,
        "next_hop": {
            "next_hop_list": {
                1: {
                    "index": 1,
                    "next_hop": "10.98.126.1",
                    "outgoing_interface_name": "Inside-Port-Channel"
                }
            }
        }
    },
...
}
...
```

I propose that the [schema for ASA's show route](https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/asa/show_route.py#L18) (and possibly [others](https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/iosxe/show_routing.py#L113)) be updated to support plural routes:

```
...
"routes": {
    "0.0.0.0/0": {
        1: {
            "candidate_default": true,
            "active": true,
            "route": "0.0.0.0/0",
            "source_protocol_codes": "S",
            "source_protocol": "static",
            "metric": 0,
            "route_preference": 1,
            "next_hop": {
                "next_hop_list": {
                    "1": {
                        "index": 1,
                        "next_hop": "192.2.0.1",
                        "outgoing_interface_name": "Outside-Port-Channel"
                    }
                }
            }
            }
        },
        2: {
            "candidate_default": false,
            "active": true,
            "route": "0.0.0.0/0",
            "source_protocol_codes": "S",
            "source_protocol": "static",
            "metric": 0,
            "route_preference": 255,
            "next_hop": {
                "next_hop_list": {
                    1: {
                        "index": 1,
                        "next_hop": "10.98.126.1",
                        "outgoing_interface_name": "Inside-Port-Channel"
                    }
                }
            }
        }
    }
}
...
```

**Comment by thismatters** [comment]
So my first idea introduces a breaking schema change, which is not allowed. (As a sidenote to that point, is there really no deprecation/removal schedule? That seems like a recipe for endless cruft.)

My next idea doesn't change the schema, but it very well could break any user test cases which involve this particular edge case, and it might break the semantic meaning of certain keys. I want to see if it is acceptable before writing the change. 

Given an input like:
```
S*       0.0.0.0 0.0.0.0 [1/0] via 104.225.199.193, Outside-Port-Channel
...
S    0.0.0.0 0.0.0.0 [255/0] via 10.98.126.1, Inside-Port-Channel tunneled
```

The proposed change to the parser would produce output like:

```
{
    "routes": {
        "0.0.0.0/0": {
            "candidate_default": True,
            "active": True,
            "route": "0.0.0.0/0",
            "source_protocol_codes": "S",
            "source_protocol": "static",
            "metric": 0,
            "route_preference": 1,
            "next_hop": {
                "next_hop_list": {
                    1: {
                        "index": 1,
                        "next_hop": "104.225.199.193",
                        "outgoing_interface_name": "Outside-Port-Channel"
                    }
                }
            }
        },
        "0.0.0.0/0-1": {
            "candidate_default": False,
            "active": True,
            "route": "0.0.0.0/0",
            "source_protocol_codes": "S",
            "source_protocol": "static",
            "metric": 0,
            "route_preference": 255,
            "next_hop": {
                "next_hop_list": {
                    1: {
                        "index": 1,
                        "next_hop": "10.98.126.1",
                        "outgoing_interface_name": "Inside-Port-Channel"
                    }
                }
            }
        }
    }
}
```

Note that instead of overwriting the `0.0.0.0/0` key with the second row a new key with an index appended is generated. In effect, this would behave exactly as before for any input which doesn't have a plural route (preserving the sanctity of existing tests). The information in the key itself is duplicated in the data structure so the mangling of the key shouldn't cause any irreparable damage. Moreover, the key itself isn't a robust means of lookup (an ip address within the subnet represented in a key will not match) which leads me to the belief that the key is acting purely as an index to hold a place for the data (i.e. emulating a `list` within a `dict`). So, in my mind, the diminished semantic meaning of the key is an acceptable loss in service of making the parsed output true.

**Comment by 0x1bi** [comment]
@thismatters thank you for your input.

Do you think that an array of routes would be better than dictionary? This way we can have an arbitrary amount of routes per every IP.

```
{
    "routes": {
        "0.0.0.0": [
            {
                ...
            },
            {
                ...
            }
        ]
    }
}
```

**Comment by thismatters** [comment]
@0x1bi I _do_ think a list of routes would be better and that was my first instinct, however it seems that the `MetaParser` only works with nested dicts and does not support lists (this is an inference drawn from minimal research; please correct me if I've misunderstood something). The first PR I made for this does simulate a list by using a numeric index as the key (as is done in the `next_hop_list`), however it breaks backward compatibility of the schema.

**Comment by LukasMcClelland** [comment]
Try leveraging `ListOf()` in the schema

https://github.com/CiscoTestAutomation/genieparser/blob/1046ad770ec6632ace2f266c9c5bc8a21cd5348e/src/genie/libs/parser/iosxr/show_lpts.py#L18

**Comment by thismatters** [comment]
`ListOf` is a good thing to know about, but introducing it to the schema still represents a breaking change; which I'm told is impossible.

**Comment by tahigash** [comment]
@thismatters I would like to go back to the output.
```
S*       0.0.0.0 0.0.0.0 [1/0] via 104.225.199.193, Outside-Port-Channel
...
S    0.0.0.0 0.0.0.0 [255/0] via 10.98.126.1, Inside-Port-Channel tunneled 
```
I'm a bit surprised. routing table basically has only best route based on metric/administrative distance. but this has 2... maybe because of Outside/Inside thing?
can we have exact configuration command to get this output?

And as you mentioned, we need to be careful for schema change since we need to minimize the impact to other users.

**Comment by thismatters** [comment]
@tahigash I'm not a network engineer myself, so I'm not directly involved with configuring appliances; I cannot speak to the configuration commands used to configure this device. I'm concerned with parsing the existing data provided by my client to facilitate analysis of their network. My colleague @willmo221 might be able to address your question, but they are also in an observer/auditor role for this particular appliance and were not responsible for the config we found.

Moreover, it should not be the role of genieparser to dictate which configs are correct by silently omitting records from consideration. Even if the config is poorly considered (or even objectively _wrong_) genieparser ought to faithfully report what is present in the config, should it not?

>And as you mentioned, we need to be careful for schema change since we need to minimize the impact to other users.

I'm understanding of the need for continuity of the schema, but critical of the fact that there is _no deprecation schedule_ which would allow for bugs to be corrected without obscure contrivances and ever-increasing complexity of schema. The genieparser ecosystem is _versioned software_ and should be able to reap the benefits of being such. Legacy users of the package should not be in a position to hamstring ongoing development because they cannot be bothered to pin their library version. Alas, this issue is not the appropriate place to rehash or second guess decisions made by the initiators and primary maintainers of this software from which I benefit.

**Comment by tahigash** [comment]
Hi @thismatters 

After investigating the output, I figureed out it's due to `tunneled` default route. (That's why I asked configuration. configuration will not help for schema directly. but might be hint to find out something useful to understand why this output is.)

You can find the `tunneled` default route from here.
https://www.cisco.com/c/en/us/td/docs/security/asa/asa72/configuration/guide/conf_gd/ip.html#wp1102439

As I mentioned, `0.0.0.0/0` should be only one in routing table. but this is kind of exception. based on the characteristic, I would like to suggest below schema to have `tunneled_routes` as key at same level with `routes`. 

```
S*       0.0.0.0 0.0.0.0 [1/0] via 104.225.199.193, Outside-Port-Channel
...
S    0.0.0.0 0.0.0.0 [255/0] via 10.98.126.1, Inside-Port-Channel tunneled 
```

suggested schema(expected output):
```
...
"routes": {
    "0.0.0.0/0": {
        "candidate_default": false,
        "active": true,
        "route": "0.0.0.0/0",
        "source_protocol_codes": "S",
        "source_protocol": "static",
        "metric": 0,
        "route_preference": 1,
        "next_hop": {
            "next_hop_list": {
                1: {
                    "index": 1,
                    "next_hop": "104.225.199.193",
                    "outgoing_interface_name": "Outside-Port-Channel"
                }
            }
        }
    },
},
"tunneled_routes": { # <<< new key for another `tunneled` default route
    "0.0.0.0/0": {
        "candidate_default": false,
        "active": true,
        "route": "0.0.0.0/0",
        "source_protocol_codes": "S",
        "source_protocol": "static",
        "metric": 0,
        "route_preference": 255,
        "next_hop": {
            "next_hop_list": {
                1: {
                    "index": 1,
                    "next_hop": "10.98.126.1",
                    "outgoing_interface_name": "Inside-Port-Channel"
                }
            }
        }
    },

...
}
```
I believe this still makes sense from the purpose of tunneled default route and its characteristic. also this will have backward compatibility.

**Comment by thismatters** [comment]
Hi @tahigash 

Thank you for those insights! I agree completely about the approach of adding a key for `tunneled_routes`.

**Comment by tahigash** [comment]
@thismatters as you suggested on https://github.com/CiscoTestAutomation/genieparser/pull/582, please open new PR with above schema. thanks for your contribution again! closing this issue since discussaion was closed.
