### ISSUE TITLE
genie.abstract is missing as a requirement

### ISSUE THREAD

**Issue by dgarros** [CiscoTestAutomation/genieparser#57]
Hi

I believe the library `genie.abstract` should be listed as a requirement since it's used in the file `src/genie/libs/parser/__init__.py` 
```python 
from .base import tcl_invoke_ats_cmd,\
                  tcl_package_require_caas,\
                  tcl_package_require_caas_parsers,\
                  tcl_invoke_caas_abstract_parser,\
                  CaasMetaParser

from genie import abstract
abstract.declare_package(__name__)
```
I wasn't able to import a parser without installing this library first

**Comment by jeaubin** [comment]
@dgarros  - Thanks

Good point, we will add it in Metaparser, the genie.libs.parser infrastructure package.

**Comment by jeaubin** [comment]
Closed as it will be part of the next release. Code has been added  Thanks!
