### ISSUE TITLE
When doing bgp parsing a `'Device' object has no attribute 'execute'` error shows up

### ISSUE THREAD

**Issue by balmasea** [CiscoTestAutomation/genieparser#597]
I'm parsing some bgp commands and for every command that has a non conditional instruction:

`self.device.execute(cmd)`

it answers 
`'Device' object has no attribute 'execute'`

That ends with not parsing of commands like 
`show ip bgp neighbor {neighbor} advertised-routes`
or 
`show bgp all cluster-ids`

**Comment by ThomasJRyan** [comment]
9 times out of 10 this is caused due to having not first connected to your device. Run `self.device.connect()` first

**Comment by balmasea** [comment]
Hi Thomas. Thanks for your answer. 
That's exactly my point. For most of commands there is no need to have a device connected to run them. Why is this command different? We would need to pass just the output and parse it, without executing anything else in the device.

**Comment by ThomasJRyan** [comment]
Ah. Well if that's what you're doing then all you should need to do is run `self.device.parse('<your_command_here>', output='<your_command_output_here>')` which will parse it for you.

If there's more to it than that, I'm going to need more information. What parser are you using? What command? Are there any other error logs you can provide?

**Comment by balmasea** [comment]
Sorry for my late answer, we have worked around the problem with a custom parser but for sure I'd love to help.
We are mainly trying to get the parsed yml from the device output that we get with our own module, so we do not connect to the devices using this library.

We are calling `ShowBgpAllNeighborsAdvertisedRoutes::cli` with output being, i.e.:
```Total number of prefixes 0```

Then, it ends up calling the `cli` method from the parent, `ShowBgpNeighborsAdvertisedRoutesSuperParser::cli` and it fails when executing line:
```        out_vrf = self.device.execute('show bgp all neighbors | i BGP neighbor')```
because there is no device connected.

This is what I meant with the "non conditional instruction" sentence above. Hope it is clearer now and let me know if I can continue helping. Thanks.
