### ISSUE TITLE
Key error happens on ShowVrfAllDetail parser when VRF name has an "*" character on it

### ISSUE THREAD

**Issue by salazardaniels** [CiscoTestAutomation/genieparser#603]
VRF **nVSatellite; RD not set; VPN ID not set
VRF mode: Regular
Description not set
Interfaces:
  nV-Loopback0
Address family IPV4 Unicast
  No import VPN route-target communities
  No export VPN route-target communities
  No import route policy
  No export route policy
Address family IPV6 Unicast
  No import VPN route-target communities
  No export VPN route-target communities
  No import route policy
  No export route policy

VRF INET_MASIVO_GPON; RD 11664:125000182; VPN ID not set
VRF mode: Regular
Description not set
Address family IPV4 Unicast
  Import VPN route-target communities:
    RT:11664:180
    RT:11664:181
    RT:11664:182
  Export VPN route-target communities:
    RT:11664:182
  Import route policy: INET_GPON_IN_OLLEROS
  Export route policy: INET_GPON_OUT_OLLEROS
Address family IPV6 Unicast
  No import VPN route-target communities
  No export VPN route-target communities
  No import route policy
  No export route policy

VRF INET_MASIVO_HFC; RD 11664:125000154; VPN ID not set
VRF mode: Regular
Description -- Conexion a ngry01rt33--
Interfaces:
  Bundle-Ether100.600
Address family IPV4 Unicast
  Import VPN route-target communities:
    RT:11664:154
  Export VPN route-target communities:
    RT:11664:154
  No import route policy
  No export route policy
Address family IPV6 Unicast
  No import VPN route-target communities
  No export VPN route-target communities
  No import route policy
  No export route policy

VRF UPLINK_MASIVO_GPON; RD 11664:125000180; VPN ID not set
VRF mode: Regular
Description not set
Interfaces:
  Bundle-Ether100.500
Address family IPV4 Unicast
  Import VPN route-target communities:
    RT:11664:182
  Export VPN route-target communities:
    RT:11664:180
  No import route policy
  No export route policy
Address family IPV6 Unicast
  No import VPN route-target communities
  No export VPN route-target communities
  No import route policy
  No export route policy
RP/0/RSP0/CPU0:ngry01rt33#
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "src/genie/conf/base/device.py", line 527, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 554, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 279, in genie.metaparser._metaparser.MetaParser.parse
  File "/mnt/d/app/PycharmProjects/genie_parse_sdk/genieparser/src/genie/libs/parser/iosxr/show_vrf.py", line 93, in cli
    vrf_dict[vrf]['vrf_mode'] = m.groupdict()['mode'].lower()
KeyError: ''

**Comment by salazardaniels** [comment]
already solved in PR: Added parser ShowControllers_WORD_WORD_Phy, Modified parser ShowPlatform, Modified parse ShowVrfAllDetail #**600**

**Comment by LukasMcClelland** [comment]
> already solved in PR: Added parser ShowControllers_WORD_WORD_Phy, Modified parser ShowPlatform, Modified parse ShowVrfAllDetail #**600**

Excellent 👍
