### ISSUE TITLE
VLANs with names exceeding 32 characters are not parsed

### ISSUE THREAD

**Issue by riborg** [CiscoTestAutomation/genieparser#612]
In this output VLANs 1830 and 1832 are not parsed at all.

```
+++ switch with via 'vty': executing command 'show vlan' +++
show vlan

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Te1/0/3, Te1/0/6, Te1/0/7, Te1/0/9
649  blablablablablabla               active    
1002 fddi-default                     act/unsup 
1003 trcrf-default                    act/unsup 
1004 fddinet-default                  act/unsup 
1005 trbrf-default                    act/unsup 
1822 blablablablablabla               active    
1828 blablablablablablablablabla      active    
1830 blablablablablablablablablablablabla
                                      active    
1832 blablablablablablablablablablablablablabla
                                      active    
```

The RegEx seems to work though - https://regex101.com/r/OiDGZ4/1

According to Cisco IOS XE release notes VLAN name can now be up to 128 characters..
https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst4500/release/note/ol-37xe-4500e.html

New Software Features (Wired) in Release IOS XE 3.7.0E
VLAN Name Extension | Increases the maximum characters supported in a VLAN name from 32 to 128.

https://www.reddit.com/r/networking/comments/4ujp9u/long_vlan_names/

**Comment by riborg** [comment]
Thanks for the feedback. I think it's best for everyone if you take care of this. ;)

**Comment by LukasMcClelland** [comment]
Sounds good, I'll look after the fix and will let you know when it's merged

**Comment by LukasMcClelland** [comment]
Fix has been merged and will be included in the next release of Genie (near end of the month)
