### ISSUE TITLE
NXOS show interface parser not working

### ISSUE THREAD

**Issue by somebody78** [CiscoTestAutomation/genieparser#617]
Hello, 

when using Genie with NXOS switches we noticed that the parser for show interface is not correctly working.
2 of the example strings are not correctly matched by the regular expression.
The regular expression to match the headlines in the output of show interface does not match the example lines:
Ethernet1/12 is down (Transceiver validation failed)
Ethernet1/13 is down (Channel admin down)

The regular expression definition starts on line 243

`p1 = re.compile(r'^(?P<interface>\S+)\s*is\s*(?P<link_state>(down|up|'`

in file

`https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/nxos/show_interface.py`

Our scripts fail because of this problem.
Your help is greatly appreciated.

Dirk

**Comment by somebody78** [comment]
Hi, I just noticed there is already a Pull request with a fix for this issue.
https://github.com/CiscoTestAutomation/genieparser/pull/578/files#
Thanks to 2008may21

**Comment by danielgraziano** [comment]
Fixed and released a beta package. Please install the latest version of pyats using `pip install --upgrade pyats[full]` then upgrade to the beta package using `pip install --upgrade --pre genie.libs.parser`. The version should be `22.1.1b0`

**Comment by danielgraziano** [comment]
Closing due to no response. Please open a new issue and link this one if you still see a bug.

**Comment by somebody78** [comment]
Thank you for your quick help. We installed the prerelease and it is working fine.
I appreciate it.
