### ISSUE TITLE
Support for Cisco ASA devices.

### ISSUE THREAD

**Issue by marcosgeorgopoulos** [CiscoTestAutomation/genieparser#62]
When trying to use your role with Cisco ASA's I get the following error

FAILED! => {"msg": "The network OS provided (ASA) to the parse_genie filter is not a supported OS in Genie."}

AND

FAILED! => {"msg": "The network OS provided (asa) to the parse_genie filter is not a supported OS in Genie."}

Adding 'asa' to your 

supported_oses = ["ios", "iosxe", "iosxr", "junos", "nxos"]

seems to fix the issue.

You also need to update your error message to link to the correct parser list

https://pubhub.devnetcloud.com/media/pyats-packages/docs/genie/genie_libs/#/parsers 

is not valid.

thanks!

**Comment by thaixuann** [comment]
Hello @marcosgeorgopoulos ,
Thanks for reporting the issue. We will look into and get back to you once the issue is fixed.

--Thai.

**Comment by jeaubin** [comment]
Hi, I think you are refering to Clay's Ansible role for pyATS | Genie right ?

You are refering to this line,  can you please raise an issue on that Github repository.

https://github.com/clay584/parse_genie/blob/master/filter_plugins/genie.py#L85

https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/parsers

Thanks,
