### ISSUE TITLE
show wireless profile policy detailed {policy_name} uses literal {policy_name}

### ISSUE THREAD

**Issue by automateyournetwork** [CiscoTestAutomation/genieparser#628]
Hello - this parser device.parse("show wireless profile policy detailed default-policy") actually sends the literal command

show wireless profile policy detailed {policy_name}

at the CLI 

Please see my comment
https://github.com/CiscoTestAutomation/genieparser/pull/286#issuecomment-1052347249

**Comment by tahigash** [comment]
I quickly tested. and not seeing the issue.
```python
In [12]: for policy in show_wireless_profile_policy_summary['policy_name']:
    ...:     print(f'show wireless profile policy detailed { policy}')
    ...:
show wireless profile policy detailed wip-b60
show wireless profile policy detailed wip-b70
show wireless profile policy detailed wip-b80
(snip)
```
I assume you put an output to `show_wireless_profile_policy_summary` like below.
```
show_wireless_profile_policy_summary = device.parse('show wireless profile policy summary')
```
could you please send the console output of show command to pyats-support-ext@cisco.com?

**Comment by automateyournetwork** [comment]
Yes I am doing the same thing in Python

device.parse(f"show wireless profile policy detailed { policy })

I do not believe {policy_name} isn't being format() - even if I hard code

device.parse("show wireless profile policy detailed wip-b60") it tries

show wireless profile policy detailed {policy_name}

Thanks

John

**Comment by tahigash** [comment]
Please send what I asked. I will look into it. at this point, I don't see any issue with genie parser.

**Comment by automateyournetwork** [comment]
Here is the code and the output as requested

You can see the f string prints the policy but the actual detailed parser
does not substitute {policy_name} with the actual policy

for device in new_testbed:
            device.connect()

        # Show Wireless Profile Policy Summary to JSON

            try:
                show_wireless_profile_policy_summary = device.parse("show
wireless profile policy summary")
            except:
                show_wireless_profile_policy_summary = f"{ hostname } Can't
Parse"

        # Pass to template

            for policy in show_wireless_profile_policy_summary['policy_name'
].keys():
                # Show WLAN all to JSON
                try:
                    print(f"{policy}")
                    show_wireless_profile_policy_detail = device.parse(f"show
wireless profile policy detailed { policy }")
                except:
                    show_wireless_profile_policy_detail = f"{ hostname }
Can't Parse"



Policy Profile Name               Description
Status

-----------------------------------------------------------------------------------------

PP_Guest_DMZ                      Guest Anchor DMZ Policy Porfile
ENABLED

default-policy-profile            default policy profile
DISABLED

BankGuestA_Global_GA_a9095393     BankGuestA_Global_GA_a9095393
ENABLED



wlc02#

*default-policy-profile*



2022-02-27 10:15:52,458: %UNICON-INFO: +++ wlc02 with via 'cli': executing
command 'show wireless profile policy detailed {policy_name}' +++

*show wireless profile policy detailed {policy_name}*

wlc02#

*BankGuestA_Global_GA_a9095393*



2022-02-27 10:15:53,045: %UNICON-INFO: +++ wlc02 with via 'cli': executing
command 'show wireless profile policy detailed {policy_name}' +++

*show wireless profile policy detailed {policy_name}*

wlc02#

*"wlc02 Can't Parse"*


Thanks


John

**Comment by tahigash** [comment]
the parser expects to see below line.
https://wwwin-github.cisco.com/pyATS/genieparser/blob/6193d46936d81f6d3532844e066c7fe534ddcdf9/src/genie/libs/parser/iosxe/show_wireless.py#L2052
```
Number of Policy Profiles: 31
```
but your output doesn't have. that's why parser crashed. We encourage user to fix parsers as much as possible. if the output is true and come from device, maybe output is vary depending on os version. can I ask you update/fix the parser with your output?

**Comment by automateyournetwork** [comment]
Hi - sorry this is not my parser I just found it. The platform is a WLC
9800 if that helps. I just wanted to report this as a bug after trying it
on an 9800 WLC. The parent show .. summary works just fine.

Thanks

John

**Comment by robschn** [comment]
@tahigash I believe @automateyournetwork is literally seeing `{policy_name}` when supplying the `policy_name` arg for `ShowWirelessProfilePolicyDetailed`. I checked the code and saw we were missing the formatting of `policy_name` so I created #629 to fix! Please let me know what you think

**Comment by tahigash** [comment]
@robschn thanks for the PR. I reviewed and fixed a small thing. then approved!
