### ISSUE TITLE
show running-config | section ^interface for IOS

### ISSUE THREAD

**Issue by jmarenco02** [CiscoTestAutomation/genieparser#643]
Unable to parse "show running-config | section ^interface" output when "cdp enable" if defined on an interface.

This is the error I am presented with.:

msg: 'parse_genie: interfaces.GigabitEthernet0/0/4: Unsupported keys: [''cdp''] - Failed to parse command output.'

**Comment by LukasMcClelland** [comment]
Hello and thank you bringing this to our attention. Since genieparser is a community driven repo, we encourage users to make fixes for errors themselves. Would you be willing to fix this and then open up a PR to commit the changes? If not, that's alright, we can handle it if you choose not to
