### ISSUE TITLE
"show logging" for IOSXE c3850 switch not working!

### ISSUE THREAD

**Issue by micyew** [CiscoTestAutomation/genieparser#645]
Hi,

Is there a different in the "show logging" parser between IOS c3750 and IOSXE c3850? It works on c3750 (15.0(2)SE12) but the same command can't work on c3850 IOSXE (16.12.4). It gave the following exception:

Issue with the parser show logging

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 524, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 303, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 404, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['logging', 'persistent']]

I update to the latest genie/pyats 22.2 version but still fail..

genie                        22.2
genie.libs.clean             22.2
genie.libs.conf              22.2
genie.libs.filetransferutils 22.2
genie.libs.health            22.2
genie.libs.ops               22.2
genie.libs.parser            22.2
genie.libs.robot             21.6
genie.libs.sdk               22.2.1
genie.telemetry              21.6
genie.trafficgen             21.6
pyats                        22.2
pyats.aereport               22.2
pyats.aetest                 22.2
pyats.async                  22.2
pyats.connections            22.2
pyats.contrib                21.6
pyats.datastructures         22.2
pyats.easypy                 22.2
pyats.kleenex                22.2
pyats.log                    22.2
pyats.reporter               22.2
pyats.results                22.2
pyats.robot                  21.6
pyats.tcl                    22.2
pyats.topology               22.2
pyats.utils                  22.2

I have the following logging command in the c3850.

c3850_SW#sh run | in logg
logging buffered 16384 informational
logging persistent url flash:/syslog.txt size 2097152 filesize 16384 immediate
logging console critical
logging trap debugging
logging origin-id ip
logging source-interface Loopback0
logging host 1.1.1.1
logging host 2.2.2.2

**Comment by LukasMcClelland** [comment]
Hello, I've replied to the email you sent to pyats-support-ext@cisco.com. We can track it there, so I'll close this issue. Please reopen if needed :)
