### ISSUE TITLE
IOS-XE - "show flow exporter statistics" does not parse if exporter contains special characters

### ISSUE THREAD

**Issue by ChristopherJHart** [CiscoTestAutomation/genieparser#648]
Consider the following IOS-XE configuration:
```
Router#show running-config | section flow.exporter
flow exporter NF-EXPORTER
 description Used for exporting basic IPv4 traffic
 destination 192.0.2.10 vrf Mgmt-intf
```
Consider the following output of `show flow exporter statistics`:
```
Router#show flow exporter statistics 
Flow Exporter NF-EXPORTER:
  Packet send statistics (last cleared 00:51:32 ago):
    Successfully sent:         0                     (0 bytes)

  Client send statistics:
    Client: Flow Monitor NF-MONITOR
      Records added:           0
      Bytes added:             0

```
The Genie parser for `show flow exporter statistics` is not able to parse this output because the name of the NetFlow exporter has a special character (specifically, `-`). The root cause of this is the [following regular expression pattern](https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/iosxe/show_flow.py#L461):
```python
        p1 = re.compile(r"^Flow +Exporter +(?P<exporter>\w+):$")
```
The use of `\w+` here doesn't accommodate for the possibility of special characters in the NetFlow exporter name. `\S+` should probably be used instead.

I will submit a PR shortly correcting this regular expression and adding tests for this scenario.

**Comment by domachad** [comment]
Hi @ChristopherJHart,

Thank you for reporting the issue and for working on a fix for it as well.
Once you raise a PR, our team will review it

**Comment by ChristopherJHart** [comment]
Closing as the PR fixing this issue has been merged.
