### ISSUE TITLE
/genie/libs/parser/iosxr/show_mpls.py - regex issues

### ISSUE THREAD

**Issue by vnstech** [CiscoTestAutomation/genieparser#649]
**regex issues ( IOSXR 7.1.2):**

 
class ShowMplsLdpIgpSync(ShowMplsLdpIgpSyncSchema):

        p1 = re.compile(r'^(?P<interface>[\w]+[\/\d]+):$')
        p3 = re.compile(r'^Sync +delay:\s+(?P<delay>\S+)$'

I think these should be   --->
class ShowMplsLdpIgpSync(ShowMplsLdpIgpSyncSchema):

        p1 = re.compile(r'^(?P<interface>[-\w]+[\/\d]+):$')
        p3 = re.compile(r'^Sync +delay:\s+(?P<delay>\S.+)$'

Also p5 does not work, i am not sure about the problem
 p5 = re.compile(r'^(?P<peers>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d{1,3})\s+?(?P<gr_flag>\(GR\))?$')

**show mpls ldp igp sync cmd output:**

Bundle-Ether40051:
  VRF: 'default' (0x60000000)
  Sync delay: 5 sec
  Sync status: Not ready (No peer session)

Bundle-Ether40055:
  VRF: 'default' (0x60000000)
  Sync delay: 5 sec
  Sync status: Ready
    Peers:
      10.120.0.10:0

**Comment by vnstech** [comment]
this worked for me --> 
p5 =(?P<peers>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d{1,3})\+?(?P<gr_flag>\(GR\))?$

**Comment by LukasMcClelland** [comment]
Hi @vnstech, 

I'll fix the parser. Thanks for letting us know about the issue

**Comment by vnstech** [comment]
thanks
 sure next time I will try to raise a pull request.

**Comment by LukasMcClelland** [comment]
Fix has been merged and will be included in our next release (less than 2 weeks from today)

**Comment by LukasMcClelland** [comment]
Thanks again for letting us know about the issue!
