### ISSUE TITLE
existing genie parser of "show hardware led" has different output structure as compare to what we see on cat9200. 

### ISSUE THREAD

**Issue by sshekha3** [CiscoTestAutomation/genieparser#655]
Hello Team,

I have written a genie parser for "show  hardware led" which has different output structure as compared to what is there in already written parser.

output on my switch(cat9200):
enf_26#sh hardware led

Current Mode: STATUS

**SWITCH**: 1
**SYSTEM**: GREEN
**MASTER**: GREEN
**STATUS**: (28) Gi1/0/1:BLACK Gi1/0/2:BLACK Gi1/0/3:BLACK Gi1/0/4:BLACK Gi1/0/5:BLACK Gi1/0/6:BLACK Gi1/0/7:BLACK Gi1/0/8:BLACK Gi1/0/9:BLACK Gi1/0/10:BLACK Gi1/0/11:BLACK Gi1/0/12:BLACK Gi1/0/13:BLACK Gi1/0/14:BLACK Gi1/0/15:BLACK Gi1/0/16:BLACK Te1/0/17:BLACK Te1/0/18:BLACK Te1/0/19:BLACK Te1/0/20:BLACK Te1/0/21:BLACK Te1/0/22:BLACK Te1/0/23:BLACK Te1/0/24:BLACK Te1/1/1:FLASH_GREEN Te1/1/2:BLACK Te1/1/3:FLASH_GREEN Te1/1/4:FLASH_AMBER
**DUPLEX**: (28) Gi1/0/1:BLACK Gi1/0/2:BLACK Gi1/0/3:BLACK Gi1/0/4:BLACK Gi1/0/5:BLACK Gi1/0/6:BLACK Gi1/0/7:BLACK Gi1/0/8:BLACK Gi1/0/9:BLACK Gi1/0/10:BLACK Gi1/0/11:BLACK Gi1/0/12:BLACK Gi1/0/13:BLACK Gi1/0/14:BLACK Gi1/0/15:BLACK Gi1/0/16:BLACK Te1/0/17:BLACK Te1/0/18:BLACK Te1/0/19:BLACK Te1/0/20:BLACK Te1/0/21:BLACK Te1/0/22:BLACK Te1/0/23:BLACK Te1/0/24:BLACK Te1/1/1:GREEN Te1/1/2:BLACK Te1/1/3:GREEN Te1/1/4:GREEN
**SPEED**: (28) Gi1/0/1:BLACK Gi1/0/2:BLACK Gi1/0/3:BLACK Gi1/0/4:BLACK Gi1/0/5:BLACK Gi1/0/6:BLACK Gi1/0/7:BLACK Gi1/0/8:BLACK Gi1/0/9:BLACK Gi1/0/10:BLACK Gi1/0/11:BLACK Gi1/0/12:BLACK Gi1/0/13:BLACK Gi1/0/14:BLACK Gi1/0/15:BLACK Gi1/0/16:BLACK Te1/0/17:BLACK Te1/0/18:BLACK Te1/0/19:BLACK Te1/0/20:BLACK Te1/0/21:BLACK Te1/0/22:BLACK Te1/0/23:BLACK Te1/0/24:BLACK Te1/1/1:BLINK_GREEN_PATTERN_4 Te1/1/2:BLACK Te1/1/3:BLINK_GREEN Te1/1/4:BLINK_GREEN_PATTERN_4
**STACK**: (28) Gi1/0/1:FLASH_GREEN Gi1/0/2:BLACK Gi1/0/3:BLACK Gi1/0/4:BLACK Gi1/0/5:BLACK Gi1/0/6:BLACK Gi1/0/7:BLACK Gi1/0/8:BLACK Gi1/0/9:BLACK Gi1/0/10:BLACK Gi1/0/11:BLACK Gi1/0/12:BLACK Gi1/0/13:BLACK Gi1/0/14:BLACK Gi1/0/15:BLACK Gi1/0/16:BLACK Te1/0/17:BLACK Te1/0/18:BLACK Te1/0/19:BLACK Te1/0/20:BLACK Te1/0/21:BLACK Te1/0/22:BLACK Te1/0/23:BLACK Te1/0/24:BLACK Te1/1/1:BLACK Te1/1/2:BLACK Te1/1/3:BLACK Te1/1/4:BLACK
**POE:** (28) Gi1/0/1:BLACK Gi1/0/2:BLACK Gi1/0/3:BLACK Gi1/0/4:BLACK Gi1/0/5:BLACK Gi1/0/6:BLACK Gi1/0/7:BLACK Gi1/0/8:BLACK Gi1/0/9:BLACK Gi1/0/10:BLACK Gi1/0/11:BLACK Gi1/0/12:BLACK Gi1/0/13:BLACK Gi1/0/14:BLACK Gi1/0/15:BLACK Gi1/0/16:BLACK Te1/0/17:BLACK Te1/0/18:BLACK Te1/0/19:BLACK Te1/0/20:BLACK Te1/0/21:BLACK Te1/0/22:BLACK Te1/0/23:BLACK Te1/0/24:BLACK Te1/1/1:BLACK Te1/1/2:BLACK Te1/1/3:BLACK Te1/1/4:BLACK

**RJ45 CONSOLE**: BLACK
**USB CONSOLE**: GREEN
**BEACON**: BLACK

output structure which parser is already available:
show hardware led
**SWITCH**: 1
**SYSTEM**: GREEN
**BEACON**: OFF
**PORT STATUS**: (124) Hu1/0/1:GREEN Hu1/0/2:OFF Hu1/0/3:GREEN Hu1/0/4:OFF Hu1/0/5:OFF Hu1/0/6:GREEN Hu1/0/7:OFF Hu1/0/8:OFF Hu1/0/9:OFF Hu1/0/10:GREEN Hu1/0/11:GREEN Hu1/0/12:GREEN Hu1/0/13:GREEN Hu1/0/14:GREEN Fou1/0/15:GREEN Fou1/0/16:GREEN Fou1/0/17:GREEN Fou1/0/18:GREEN Fou1/0/19:GREEN Fou1/0/20:GREEN Fou1/0/21:GREEN Fou1/0/22:GREEN Hu1/0/23:GREEN Hu1/0/24:GREEN Hu1/0/25:OFF Hu1/0/26:GREEN Hu1/0/27:GREEN Hu1/0/28:GREEN Hu1/0/29:GREEN Hu1/0/30:GREEN Hu1/0/31:OFF Hu1/0/32:GREEN Hu1/0/33:GREEN Hu1/0/34:GREEN Hu1/0/35:GREEN Hu1/0/36:GREEN

**RJ45 CONSOLE**: GREEN
**FANTRAY 1 STATUS**: GREEN
FANTRAY 2 STATUS: GREEN
FANTRAY 3 STATUS: GREEN
FANTRAY 4 STATUS: GREEN
FANTRAY 5 STATUS: GREEN
FANTRAY 6 STATUS: GREEN
**POWER-SUPPLY 1 BEACON**: OFF
POWER-SUPPLY 2 BEACON: OFF
**SYSTEM PSU**: AMBER
SYSTEM FAN: GREEN

Can anyone please guide me like how to proceed in this scenario?

Thanks
Shashi Shekhar

**Comment by stevedhn** [comment]
Hi, do you have any updates on this? are you able to solve this issue?

**Comment by stevedhn** [comment]
no response from the user, closing this issue.
