### ISSUE TITLE
Partial syntax matches are scored the same as variables, resulting in ambiguous or incorrect matches

### ISSUE THREAD

**Issue by joewesch** [CiscoTestAutomation/genieparser#663]
While evaluating using Genie with Netmiko I discovered that I was able to use abbreviated syntax such as `sh ip int` instead of `show ip interface`. However, if I did `sh ip int br` it would not work. After doing some digging it looks like the [_fuzzy_search_command](https://github.com/CiscoTestAutomation/genieparser/blob/44cf21fa146171a6788bb7db598f63ba3491d421/src/genie/libs/parser/utils/common.py#L191) function was raising an exception and Netmiko was [just swallowing it](https://github.com/ktbyers/netmiko/blob/978ffbec0d5691d4b38ba6b0d455893d357591b7/netmiko/utilities.py#L534-L540):

```
Search for 'sh ip int br' is ambiguous. Please be more specific in your keywords.

Results matched:
> show ip interface brief
> show ip interface {interface}
```

It looks like this happens because the score weight for a [partial match](https://github.com/CiscoTestAutomation/genieparser/blob/44cf21fa146171a6788bb7db598f63ba3491d421/src/genie/libs/parser/utils/common.py#L462) (100) is the same as for[ a variable](https://github.com/CiscoTestAutomation/genieparser/blob/44cf21fa146171a6788bb7db598f63ba3491d421/src/genie/libs/parser/utils/common.py#L400) (100).

This also causes some interesting anomalies any time the position of a token in the command could be either syntax or a variable.

For example:

```python
>>> from genie.libs.parser.utils import common
>>> common._fuzzy_search_command('show interfaces transceiver detail', False)[0][0]
'show interfaces transceiver detail'
>>> common._fuzzy_search_command('show interfaces transceive detail', False)[0][0]
'show interfaces {interface} detail'
>>>
```

Even though `transceive` is over 90% of `transceiver` the function instead returns the parser with a variable instead of a partial syntax match.

My initial thought was maybe weighing partial syntax as slightly higher (101) than variables, but that broke down when doing commands like `show ip prefix-list` as `ip` is short for `ipv6` even though it was meant to match on `show {af} prefix-list` instead. This can probably be overcome by changing the [show {af} prefix-list](https://github.com/CiscoTestAutomation/genieparser/blob/d7b46ae7bf935079a96d9c5208ce500d9163af7c/src/genie/libs/parser/nxos/show_prefix_list.py#L48) (and all similar `show {af}` commands) to instead use exact syntax of `show ip`/`show ipv6` instead of the `{af}` variable, but there may be other similar issues by changing the weight of partial matches that aren't apparent. I only was able to easily identify that discrepancy due to a unit test written for it.

**Comment by joewesch** [comment]
After reviewing further it seems that I should be using `fuzzy=True`. As this flag is not exposed in Netmiko, maybe this is better handled as an issue in that repo to expose the option.

I'll leave this issue open for now if anyone else has any input on how to better handle partial syntax matches without explicitly enabling fuzzy.

**Comment by stevedhn** [comment]
Hi @joewesch do you have any updates on this?

**Comment by joewesch** [comment]
No, I think the solution for now will be to enable fuzzy in Netmiko. I will go ahead and close this issue for now. Thanks.
