### ISSUE TITLE
genie ping parser (ios-xe) wrong variable with the raw data

### ISSUE THREAD

**Issue by derevk0** [CiscoTestAutomation/genieparser#664]
Hi team,

The genie ping parser (v22.4)  for ios-xe shows wrong variable between average ping and max ping.
It is swapped.

See below:
**_Raw input:_**

> Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 208.67.220.220, timeout is 2 seconds:
Packet sent with a source address of 10.1.1.1 
!!!!!
Success rate is 100 percent (5/5), round-trip min/**avg/max** = 8/**8/9** ms

**_Parser:_**

> {'ping': {'address': '208.67.220.220',
          'data_bytes': 100,
          'repeat': 5,
          'result_per_line': ['!208.67.220.220_START', '!!!!!'],
          'source': '10.1.1.1',
          'statistics': {'received': 5,
                         'round_trip': {**'avg_ms': 9, 'max_ms': 8**, 'min_ms': 8},
                         'send': 5,
                         'success_rate_percent': 100.0},
          'timeout_secs': 2}}

**Comment by stevedhn** [comment]
Hi @derevk0 can you provide the steps to replicate this issue?

**Comment by derevk0** [comment]
We can use genie parser and it also shows same wrong variable.

genie parse "ping 72.163.4.185 source lo0 repeat 5" --testbed-file testbednew.yaml -vvv

> Host>
  0%|                                                                                                                                                         | 0/1 [00:00<?, ?it/s]
2022-06-07 09:46:07,596: %UNICON-INFO: +++ Host with via 'cli': executing command 'ping 72.163.4.185 source lo0 repeat 5' +++
ping 72.163.4.185 source lo0 repeat 5
Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 72.163.4.185, timeout is 2 seconds:
Packet sent with a source address of 10.10.18.245 
!!!!!
Success rate is 100 percent (5/5), round-trip min/avg/max = 215/217/221 ms
Host>
{
  "ping": {
    "repeat": 5,
    "data_bytes": 100,
    "address": "72.163.4.185",
    "timeout_secs": 2,
    "source": "10.10.18.245",
    "result_per_line": [
      "!!!!!"
    ],
    "statistics": {
      "success_rate_percent": 100.0,
      "received": 5,
      "send": 5,
      "round_trip": {
        "min_ms": 215,
        "max_ms": 217,
        "avg_ms": 221
      }
    }
  }
}
{
  "ping": {
    "address": "72.163.4.185",
    "data_bytes": 100,
    "repeat": 5,
    "result_per_line": [
      "!!!!!"
    ],
    "source": "10.10.18.245",
    "statistics": {
      "received": 5,
      "round_trip": {
        "avg_ms": 221,
        "max_ms": 217,
        "min_ms": 215
      },
      "send": 5,
      "success_rate_percent": 100.0
    },
    "timeout_secs": 2
  }

**Comment by stevedhn** [comment]
Hi @derevk0 I fixed the issue, it'll be ready in the next release.
