### ISSUE TITLE
nxos | show_vpc parser not supporting vpc+ outputs

### ISSUE THREAD

**Issue by psolarcz** [CiscoTestAutomation/genieparser#68]
Traceback (most recent call last):
  File "/Users/XX/PycharmProjects/test_folder/vpc_parser_test.py", line 102, in <module>
    after = device.parse('show vpc', output=vpc_plus)
  File "src/genie/conf/base/device.py", line 536, in genie.conf.base.device.Device.parse
  File "/Users/XX/miniconda3/envs/pyats/lib/python3.6/site-packages/genie/libs/parser/nxos/show_vpc.py", line 499, in cli
    vpc_dict.update({'up_vlan_bitset': up_vlan_bitset})
UnboundLocalError: local variable 'vpc_dict' referenced before assignment

Example output for show vpc is:
Switch1# show vpc
Legend:
                (*) - local vPC is down, forwarding via vPC peer-link

vPC domain id                     : 312
vPC+ switch id                    : 312
Peer status                       : peer adjacency formed ok
vPC keep-alive status             : peer is alive
vPC fabricpath status             : peer is reachable through fabricpath
Configuration consistency status  : success
Per-vlan consistency status       : success
Type-2 consistency status         : success
vPC role                          : primary
Number of vPCs configured         : 8
Peer Gateway                      : Disabled
Dual-active excluded VLANs        : -
Graceful Consistency Check        : Enabled
Auto-recovery status              : Enabled (timeout = 300 seconds)

vPC Peer-link status
---------------------------------------------------------------------
id   Port   Status Active vlans
--   ----   ------ --------------------------------------------------
1    Po1    up     1,10-28,30-54,56-82,138,530,2587

vPC status
---------------------------------------------------------------------------
id     Port        Status Consistency Reason       Active vlans vPC+ Attrib
--     ----------  ------ ----------- ------       ------------ -----------
11     Po11        up     success     success      1,10-28,30-5 DF: Partial,
                                                   4,56-82,138, FP MAC:
                                                   530,2587     312.0.0

It's not matching p19 regex.

**Comment by thaixuann** [comment]
Hello,
Thanks for inform us. We’ll fix and let you know once it fixed.

Thanks,

Thai Nguyen
Core Software Group (CSG)  - SSR | Genie
DevX Engineering Community http://devx.cisco.com<http://devx.cisco.com/>

2018 Pioneer Award Winner -
Devx Pervasive Quality Platform with pyATS & Genie

**Comment by thaixuann** [comment]
Hello @psolarcz ,

We fixed the issue and genie package v20.1 has been released with the fix.
Could you please run the following command and try again to see if it works?

pip install genie.libs.parser --upgrade --pre

Thanks,
--Thai.

**Comment by psolarcz** [comment]
Looks fine:

'vpc': {11: {'up_vlan_bitset': '1,10-28,30-54,56-82,138,530,2587',
              'vpc_consistency': 'success',
              'vpc_consistency_status': 'success',
              'vpc_id': 11,
              'vpc_ifindex': 'Port-channel11',
              'vpc_plus_attrib': 'DF: Partial,FP MAC:312.0.0',
              'vpc_port_state': 'up'},
