### ISSUE TITLE
Genie Parser Error Handling Request

### ISSUE THREAD

**Issue by Alexpf20210007** [CiscoTestAutomation/genieparser#682]
The issue is that genieparser does not handle basic parser empty and returns exception. This seems pretty trivial. However it would save me a ton of time and anybody else that uses this.
I think that the Genie parser should be able to handle an empty parser error exception without crashing. This could be done by returning to the python script and allowing the end user to handle it, or by having the command provide a baseline output. that could be used instead of erroring out.
Here is an example of an exception:
genie.metaparser.util.exceptions.SchemaEmptyParserError: Parser Output is empty

**Comment by sjpatel21** [comment]
Can you please let me know specifically which parser throws this exception when returning empty.

**Comment by Alexpf20210007** [comment]
Does this help
  File "src/genie/conf/base/device.py", line 528, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 567, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/conf/base/device.py", line 565, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 329, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 322, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 233, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaEmptyParserError: Parser Output is empty

----------------------------------------------------------------------
American Family Mutual Insurance Company, S.I. |  American Family Insurance Company |  American Family Life Insurance Company | American Standard Insurance Company of Ohio | American Standard Insurance Company of Wisconsin |  Midvale Indemnity Company |  Home Office - 6000 American Parkway  Madison, WI 53783Permanent General Assurance Corporation | Permanent General Assurance Corporation of Ohio | The General Automobile Insurance Company, Inc. DBA The General®  Home Office - 2636 Elm Hill Pike  Nashville, TN 37214 wholly owned subsidiaries of American Family Mutual Insurance Company, S.I.*If you are not the intended recipient, please contact the sender and delete this e-mail, any attachments and all copies..

**Comment by sjpatel21** [comment]
Sorry, what I meant was to know which parser raised this error. Can you please let me know which command parser triggers this error.

**Comment by Alexpf20210007** [comment]
An example would be that if I have a device in my device list that the Unicon Plugin signs into and runs a command, but the command does not exist on that device for some reason.

**Comment by Alexpf20210007** [comment]
It could be any command.

**Comment by sjpatel21** [comment]
Hi Alex.
The normal exception for a parser missing for a device is `ParserNotFound`. 
I also confirm that most of the parsers do indeed support empty parser output,a nd will just return an empty python dictionary in that case.
While the exception `SchemaEmptyParserError ` that you are getting seems due to the device not correctly responding to the command sent to it.

Hope this helps and clarifies your doubts.

**Comment by Alexpf20210007** [comment]
I thought I had responded to this thread. I was going to suggest that if the command does not exist, can you skip to the next device?
