### ISSUE TITLE
Problem with installing version 22.6

### ISSUE THREAD

**Issue by dirkf98** [CiscoTestAutomation/genieparser#685]
Hello,

I'm trying to install the newest version of Genie (22.6). A simple `pip install genie` apparently gives me version 22.4.
`> pip freeze | grep genie
genie==22.4
genie.libs.clean==22.4.1
genie.libs.conf==22.4
genie.libs.filetransferutils==22.4
genie.libs.health==22.4
genie.libs.ops==22.4
genie.libs.parser==22.4
genie.libs.sdk==22.4.1`

Trying to install the specific version does not work, too.
`> pip install genie==22.6
ERROR: Could not find a version that satisfies the requirement genie==22.6 (from versions: 1.0.0, 3.0.0, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 19.0, 19.0.1, 19.4.0, 19.4.1b0, 19.5.0, 19.5.1b0, 19.5.1, 19.5.2b0, 19.5.2b1, 19.5.2b2, 19.6.0, 19.7, 19.7.1, 19.8, 19.9, 19.10, 19.11, 19.12, 20.1, 20.2, 20.4, 20.4.1, 20.5, 20.6, 20.6.1, 20.7, 20.8, 20.8.1b0, 20.8.1b1, 20.9, 20.10, 20.10.1b0, 20.12, 20.12.2, 21.1, 21.1.1, 21.1.2, 21.1.3, 21.2, 21.2.1, 21.2.2, 21.2.3, 21.3, 21.3.1, 21.3.2b1, 21.4, 21.5, 21.5.1, 21.5.2, 21.6, 21.7, 21.8, 21.8.1, 21.8.2, 21.9, 21.10, 21.12, 22.1, 22.2, 22.3, 22.4)
ERROR: No matching distribution found for genie==22.6`

The Pypi website shows 22.6 as the recent version as well. [https://pypi.org/project/genie/#history](url)

Can you help me to install version 22.6?
Thanks a lot
Dirk

**Comment by Taarini** [comment]
The issue could be due to you existing pyats version is 22.4.
Create a new virtual environment and try installing the pyats.

**Comment by dirkf98** [comment]
Hello,

thanks for the quick reply.
I initially tried in a new virtual environment and using "pip install pyats[library]" installed the 22.4 version.
When trying "pip install pyats[library]==22.6" I get this error message.
ERROR: Could not find a version that satisfies the requirement pyats[library]==22.6 (from versions: 4.1.0, 5.0.0, 5.0.1, 5.1.0, 19.0, 19.4.0, 19.5.0, 19.6, 19.7, 19.8, 19.9, 19.9.1, 19.9.2, 19.10, 19.11, 19.12, 20.1, 20.2, 20.2.1, 20.4, 20.5, 20.6, 20.7, 20.8, 20.9, 20.10, 20.12, 21.1, 21.2, 21.3, 21.4, 21.5, 21.5.1, 21.6, 21.7, 21.8, 21.8.1, 21.9, 21.10, 21.12, 22.1, 22.2, 22.3, 22.4)
ERROR: No matching distribution found for pyats[library]==22.6

Can this be caused by the Python version. Currently the version 3.6.15 is installed.
I found different requirements.
The website https://pypi.org/project/pyats/22.6/ shows "pyATS currently supports Python 3.4+ on Linux & Mac systems".
On https://pubhub.devnetcloud.com/media/pyats-getting-started/docs/install/installpyATS.html Python version >=3.7 are recommended.

Dirk

Von: Taarini ***@***.***>
Gesendet: Donnerstag, 21. Juli 2022 15:31
An: CiscoTestAutomation/genieparser ***@***.***>
Cc: Feldhaus, Dirk, NMD-I1.5 ***@***.***>; Author ***@***.***>
Betreff: Re: [CiscoTestAutomation/genieparser] Problem with installing version 22.6 (Issue #685)


The issue could be due to you existing pyats version is 22.4.
Create a new virtual environment and try installing the pyats.

-

**Comment by Taarini** [comment]
FYI, pyats+python3.6 support ended as of April 2022. Please install python 3.8+.
Please follow the steps below 

- Create a virtual env specific to version 3.8
- pip install "pyats[full]" 

Let me know if your issue resolves

**Comment by Taarini** [comment]
Try giving pip install "pyats[full]" == 22.6

**Comment by dirkf98** [comment]
Hello,

with Python 3.9 everything is working, and I was able to install pyats and genie in version 22.6.

Thank you for your quick help

Dirk

Von: Taarini ***@***.***>
Gesendet: Donnerstag, 21. Juli 2022 16:33
An: CiscoTestAutomation/genieparser ***@***.***>
Cc: Feldhaus, Dirk, NMD-I1.5 ***@***.***>; Author ***@***.***>
Betreff: Re: [CiscoTestAutomation/genieparser] Problem with installing version 22.6 (Issue #685)


Try giving pip install "pyats[full]" == 22.6

-

**Comment by Taarini** [comment]
Thanks for your update. Hence closing this issue.
