### ISSUE TITLE
parsing takes too long when initial config commands are disabled in device.connect() method

### ISSUE THREAD

**Issue by Ehsan-Ghazizadeh** [CiscoTestAutomation/genieparser#688]
Hi 

when I disable initial config commands like this:
device.connect(init_exec_commands=[], init_config_commands=[], log_stdout=False)
then parse command like below takes like 3 times more time to return result:
interface_stats = device.parse("show interfaces")
platform is ASR9901 with ios xr, version 7.1.3.
but when I remove that init_exec_commands and init_config_commands from connect method it runs normally!

**Comment by ademz** [comment]
Hello @Ehsan-Ghazizadeh 

Thank you for bringing this case. 

I'm just wondering about your use case why do you need to  pass `init_exec_commands` and `init_config_commands` as an empty list.  These parameters are also default `None`. 

Do you have any log files and `testbed.yaml` for sharing with us? 

Thanks,
Adem Oztas
