### ISSUE TITLE
show isis adjacency vrf all return an error

### ISSUE THREAD

**Issue by fmabille09** [CiscoTestAutomation/genieparser#693]
Hello, 

When launching command : "show isis adjacency vrf all" it returns "UnboundLocalError: local variable 'vrf_dict' referenced before assignment".

When looking at the code, I've the impression that the following regex doen't work "p1 = re.compile(r'^IS-IS +[Pp]rocess: +(?P<process_id>\S+) +VRF: +(?P<vrf>\S+)$')".

**Comment by fmabille09** [comment]
I found the issue there is a space that is not needed in the regex. After 'VRF:', there is no space
p1 = re.compile(r'^IS-IS +[Pp]rocess: +(?P<process_id>\S+) +VRF:+(?P\S+)$')"

**Comment by Taarini** [comment]
Hi 

Thanks for reporting the issue.

pyATS parser is community driven.

Please consider contributing to pyATS genie parser library.

Below is a link with instructions on how to write a parser:
https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/writeparser/writeparser.html

If you need any help, please let me know by creating a pull request for the above issue

**Comment by fmabille09** [comment]
Hello, 

I've open PR696 for this.

**Comment by Taarini** [comment]
Thanks for your contribution to the genie parser library. 

Can you please add changelog for your changes, meaning why this change is needed.

**Comment by Taarini** [comment]
I guess your change broke the existing test case implementation. Can you update your regex with or without space so the existing cases won't break

**Comment by fmabille09** [comment]
Hello, I've updated to accept a whitespace or not. I'll update changelog to explain

**Comment by Taarini** [comment]
Hi I could see you have updated the description. The changelog is a file added under the below path,
https://github.com/CiscoTestAutomation/genieparser/tree/master/changelog/undistributed

So in you case you should create a filename with changelog_nxos_show_isis_adjacency_fix_20220829084830.rst

**Comment by Taarini** [comment]
You will also find a template in the above path for your reference.

**Comment by Taarini** [comment]
I'm closing this issue as PR is already created. I request you to have merge the latest code and fix the jenkins failure. The failure is due to pyats version mismatch
