### ISSUE TITLE
Breaking out genie.utils into its own package

### ISSUE THREAD

**Issue by dannywade** [CiscoTestAutomation/genieparser#714]
This is a question related to Genie, but not necessarily the parsers. Are there any plans to break out genie.utils into its own package? The reason I'm asking is because I like using some the libraries (i.e. Dq), but I hesitate to use them due to the burden of installing both pyATS and Genie. Installing both packages is excessive and adds many dependencies that I won't use/implement.

**Comment by ademz** [comment]
Hello,

We don't have any plans to separate this package yet.

Thanks,
Adem Oztas
