### ISSUE TITLE
Could not parse show interfaces transceiver on cat 9600 

### ISSUE THREAD

**Issue by g-arjuna** [CiscoTestAutomation/genieparser#733]
When using genie parser to parse show interfaces transceiver command , the parsing fails for cat 9600 switches with multiple line cards but works for pizza box switches like 9500 s.

**Comment by ParimiNeeraja** [comment]
Hi g-arjuna, can you please send me the output of the parser which fails for 9600 switch.

**Comment by ParimiNeeraja** [comment]
Hi g-arjuna,
Please let me know you are looking for the support for this issue?

Please make sure to add output of the parser which fails for 9600 switch.

**Comment by ParimiNeeraja** [comment]
Hi g-arjuna,
Please let me know you are looking for the support for this issue ?

**Comment by ParimiNeeraja** [comment]
Hi g-arjuna,
Could you please let me know if you are looking for the support for this case or not ?
Please make sure to add output of the parser which fails for 9600 switch.

**Comment by g-arjuna** [comment]
Hi thanks for the response. Unfortunately we are not in a position to share you the output.

**Comment by ParimiNeeraja** [comment]
Hi g-arjuna,

I understand that, we need the output/schema-output of the both switches to differentiate the issue. If you fell uncomfortable or it was confidential matter like username/password you can  ' * '  them and share us to this mail id : pyats-support-ext@cisco.com . If not we can close the ticket we cant do anything without proper information .

**Comment by ParimiNeeraja** [comment]
Hi @g-arjuna ,

Please share the needed information to internal mail-id mention in above. Without those information we cant find the issue.

**Comment by ParimiNeeraja** [comment]
We need some additional information to resolve the issue. Without proper information, we won't be able to identify the exact problem. Since we haven't received a response, we will close the ticket. However, if you require further assistance, please let me know, and I'll do my best to provide additional guidance.
