### ISSUE TITLE
Parsing of "show l2vpn xconnect" fails on ios-xr.

### ISSUE THREAD

**Issue by spencer8338** [CiscoTestAutomation/genieparser#735]
I'm using genie 23.2 and pyats 23.1. My import statement is: "from genie.libs.parser.iosxr.show_xconnect import ShowL2vpnXconnect"
**The error I receive is:** UnboundLocalError: local variable 'name_dict' referenced before assignment.

I've tried to remove $ from regex as suggested in a previous issue but I just receive another variable ref before assignment err.

**Comment by sudheergovindu** [comment]
Hi , I am looking at your ticket and reviewing it, Please let me know are you facing the issue still or not ?

**Comment by sudheergovindu** [comment]
UnboundLocalError is a type of error that occurs in Python when a local variable is referenced before it has been assigned a value within a function or method.
please assign first and try it,if resloved let me know

**Comment by sudheergovindu** [comment]
is your UnboundLocalError got resolved or not? let me know .

**Comment by sudheergovindu** [comment]
we have not received sufficient information from you to proceed with addressing the issue you reported. We have made multiple attempts to reach out to you , but unfortunately, we have not received any response.If you have any further concerns or would like to provide additional information, please do not hesitate to open a new ticket or contact us
