### ISSUE TITLE
Unable to parse output for command 'show ip route' (local variable 'path_dict' referenced before assignment)"

### ISSUE THREAD

**Issue by vsvetlov** [CiscoTestAutomation/genieparser#74]
Hello,

It looks like a bug for pyats_parser Ansible filter for directly conneced routes
OS is IOSXE
Here is output for sh ip route 10.20.100.10

TASK [debug] *************************************************************************************************************************************************
ok:[firewall] => {
    "device_output": "Routing entry for 10.20.100.0/24\n  Known via \"connected\", distance 0, metric 0 (connected, via interface)\n  Redistributing via eigrp 100, ospf 4\n  Routing Descriptor Blocks:\n  * directly connected, via Port-channel2.60\n      Route metric is 0, traffic share count is 1"
}

TASK [Parsing device output] *********************************************************************************************************************************
fatal: [firewall]: FAILED! => {
    "msg": "Unable to parse output for command 'show ip route' (local variable 'path_dict' referenced before assignment)"
}

**Comment by thaixuann** [comment]
Hi @vsvetlov ,
Thanks for reporting the issue. We will take a look and let you know once it fixed.

--Thai.

**Comment by xiaoxinz-cisco** [comment]
Hello @vsvetlov ,

From the error message you showed above: 

_"msg": "Unable to parse output for command 'show ip route' (local variable 'path_dict' referenced before assignment)"_

the command is 'show ip route'.

Can you please try 'show ip route10.20.100.10' and see if it works?

Let us know if you have further questions.

**Comment by vsvetlov** [comment]
Hello,

Do you mean replace the parser's argument 'show ip route' with 'show ip route 10.20.100.10'.
If so it works. Is it by design?

**Comment by xiaoxinz-cisco** [comment]
Hello @vsvetlov ,

I'm glad to hear it works. Yes, it is designed.

The 'show ip route' parser supports various input forms:
 - 'show ip route vrf {vrf}',
 - 'show ip route vrf {vrf} {route}',
 - 'show ip route vrf {vrf} {protocol}',
 - 'show ip route',
 - 'show ip route {route}',
 - 'show ip route {protocol}'

Details can be found in [here].(https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/iosxe/show_routing.py#L14)

There is [a sample test](https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/iosxe/tests/test_show_routing.py#L1213) which is similar to your input.

Thanks,
Irene

**Comment by vsvetlov** [comment]
You are right! I missed that output for different modes is different. Sorry for disturbing and thank you for the detailed explanation.
