### ISSUE TITLE
'show ip ospf neighbors detail' really slow on switch with many ospf neigbors

### ISSUE THREAD

**Issue by frdaigle** [CiscoTestAutomation/genieparser#747]
Parsing the command will last about 14 minutes on a switch with about 230 ospf neigbors.

I had a look parser's code and a 'show run | section router ospf {instance}' is run for each neighbor to gather vrf data. I would be more efficient to run a 'show run | section router ospf' once and refer to the returned dictionary for all neighbors.

**Comment by sumitsehgal123** [comment]
Thanks for reaching out piestack support team, I will be looking at your ticket and reviewing it . Please make sure to  add the logs / pyats version / package list .

**Comment by sumitsehgal123** [comment]
Hi frdaigle,
Please  can you  share the cli sample output for the  "show run | section router ospf {instance}".

**Comment by sumitsehgal123** [comment]
Hi,
Ticket heading and problem statement both are different. Could you please clarify whether you are looking for the API for show run | section router ospf {instance?, and for Which OS / Device model ?

And , also would be good if you can share the reference logs (manual) to analyze further data to cross check. Are the system CPU/memory status only peaks when executing these cli`s ?

**Comment by sumitsehgal123** [comment]
closing the issue as no response was received.

**Comment by virrsa** [comment]
Opened PR #780 to address this issue. Testing showed that the time it took to parse the command went from 14 minutes down to ~1 minute with the optimized parser.
