### ISSUE TITLE
NXOS: 'show ip igmp snooping' wrong parsing

### ISSUE THREAD

**Issue by VladKh** [CiscoTestAutomation/genieparser#748]
Hi genie team,
There is a mistake in `show ip igmp snooping` parser for NXOS. It always returns `switch-querier=disabled` even if the cmd response string looks `Switch-querier enabled, address XXX.XXX.XXX.XXX, currently running`.

Example:
```
# show ip igmp snooping

Global IGMP Snooping Information:
  IGMP Snooping enabled
  Optimised Multicast Flood (OMF) enabled
  IGMPv1/v2 Report Suppression enabled
  IGMPv3 Report Suppression disabled
  Link Local Groups Suppression enabled

IGMP Snooping information for vlan 1
  IGMP snooping enabled
  Lookup mode: IP
  Optimised Multicast Flood (OMF) enabled
  IGMP querier none
  Switch-querier disabled
  IGMPv3 Explicit tracking enabled
  IGMPv2 Fast leave disabled
  IGMPv1/v2 Report suppression enabled
  IGMPv3 Report suppression disabled
  Link Local Groups suppression enabled
  Router port detection using PIM Hellos, IGMP Queries
  Number of router-ports: 1
  Number of groups: 0
  VLAN vPC function enabled
  Active ports:
    Po700       Po858   
  Report Flooding: Disabled
  Interfaces for Report Flooding: n/a 
  Use Group Address for Proxy Leaves: no

IGMP Snooping information for vlan 2141
  IGMP snooping enabled
  Lookup mode: IP
  Optimised Multicast Flood (OMF) enabled
  IGMP querier present, address: XXX.XXX.XXX.XXX, version: 3
  Querier interval: 125 secs
  Querier last member query interval: 1 secs
  Querier robustness: 2
  Switch-querier enabled, address XXX.XXX.XXX.XXX, currently running
  IGMPv3 Explicit tracking enabled
  IGMPv2 Fast leave disabled
  IGMPv1/v2 Report suppression enabled
  IGMPv3 Report suppression disabled
  Link Local Groups suppression enabled
  Router port detection using PIM Hellos, IGMP Queries
  Number of router-ports: 1
  Number of groups: 0
  VLAN vPC function enabled
  Active ports:
    Po700       Po702   Po858   
  Report Flooding: Disabled
  Interfaces for Report Flooding: n/a 
  Use Group Address for Proxy Leaves: no
```
Result:
```
{
  "global_configuration": {
    "enabled": "enabled",
    "v1v2_report_suppression": "enabled",
    "v3_report_suppression": "disabled",
    "link_local_groups_suppression": "enabled"
  },
  "vlans": {
    "1": {
      "v1v2_report_suppression": "enabled",
      "link_local_groups_suppression": "enabled",
      "v3_report_suppression": "disabled",
      "ip_igmp_snooping": "enabled",
      "lookup_mode": "ip",
      "switch_querier": "disabled",
      "v2_fast_leave": "disabled",
      "router_ports_count": 1,
      "groups_count": 0,
      "vlan_vpc_function": "enabled",
      "active_ports": [
        "Po700",
        "Po858"
      ],
      "report_flooding": "disabled",
      "report_flooding_interfaces": "n/a",
      "group_address_for_proxy_leaves": "no"
    },
    "2141": {
      "ip_igmp_snooping": "enabled",
      "v1v2_report_suppression": "enabled",
      "link_local_groups_suppression": "enabled",
      "v3_report_suppression": "disabled",
      "lookup_mode": "ip",
      **"switch_querier": "disabled",**
      "v2_fast_leave": "disabled",
      "router_ports_count": 1,
      "groups_count": 0,
      "vlan_vpc_function": "enabled",
      "active_ports": [
        "Po700",
        "Po702",
        "Po858"
      ],
      "report_flooding": "disabled",
      "report_flooding_interfaces": "n/a",
      "group_address_for_proxy_leaves": "no",
      "igmp_querier": {
        "address": "XXX.XXX.XXX.XXX",
        "version": 3,
        "interval": 125,
        "last_member_query_interval": 1,
        "robustness": 2
      }
    }
  }
}
```

Software:
- BIOS: version 05.45
- NXOS: version 9.3(9)

Hardware
  cisco Nexus9000 C9336C-FX2 Chassis

```
Package                      Version
---------------------------- ---------
genie                        23.2
genie.libs.clean             23.2
genie.libs.conf              23.2
genie.libs.filetransferutils 23.2
genie.libs.health            23.2
genie.libs.ops               23.2
genie.libs.parser            23.2
genie.libs.sdk               23.2
pyats                        23.2
pyats.aereport               23.2
pyats.aetest                 23.2
pyats.async                  23.2
pyats.connections            23.2
pyats.datastructures         23.2
pyats.easypy                 23.2
pyats-genie-command-parse    1.3.5
pyats.kleenex                23.2
pyats.log                    23.2
pyats.reporter               23.2
pyats.results                23.2
pyats.tcl                    23.2
pyats.topology               23.2
pyats.utils                  23.2
```

**Comment by ParimiNeeraja** [comment]
Hi VladKh,

Thanks for reaching out support team, I will be looking at your ticket and reviewing it.

**Comment by ParimiNeeraja** [comment]
Hi ,

I saw that in parser they didn't write the regular expression for ## Switch-querier when enabled, only written for   #  Switch-querier disabled . Please check with the team.
### 

  #  Switch-querier disabled
            p10 = re.compile(r'^\s*Switch\-querier +(?P<switch_querier>\S+)$')
            m = p10.match(line)
            if m:
                switch_querier = m.groupdict()['switch_querier']
###

**Comment by ParimiNeeraja** [comment]
Hi VladKh,

Have you raised the request to genieparser team about this update (## Switch-querier when enabled).

**Comment by VladKh** [comment]
> Hi VladKh,
> 
> Have you raised the request to genieparser team about this update (## Switch-querier when enabled).

Hi [ParimiNeeraja](https://github.com/ParimiNeeraja), 
No.
Is the issue ticket not enough to start fixing that bug?

**Comment by ParimiNeeraja** [comment]
Hi @VladKh,

Thanks for reporting the issue. We will add this to our backlog and keep you posted on when it will be released.

**Comment by ParimiNeeraja** [comment]
Hi @VladKh ,

I Resolved this issue with your output, can you please check and confirm.

**Comment by VladKh** [comment]
> Hi @VladKh ,
> 
> I Resolved this issue with your output, can you please check and confirm.

Hello @ParimiNeeraja,
Could you please share the commit or branch? 
Couldn't find your changes in the **master** branch.

**Comment by ParimiNeeraja** [comment]
Hi @VladKh 
Can you please see this link , I was change the pattern which matches the your output. It was reflected in master branch.
[https://github.com/CiscoTestAutomation/genieparser/blame/master/src/genie/libs/parser/nxos/show_igmp.py#LL197-L199C147](https://github.com/CiscoTestAutomation/genieparser/blame/master/src/genie/libs/parser/nxos/show_igmp.py#LL197-L199C147)
[https://github.com/CiscoTestAutomation/genieparser/blame/master/src/genie/libs/parser/nxos/show_igmp.py#LL203-L205C51](https://github.com/CiscoTestAutomation/genieparser/blame/master/src/genie/libs/parser/nxos/show_igmp.py#LL203-L205C51)
[https://github.com/CiscoTestAutomation/genieparser/blame/master/src/genie/libs/parser/nxos/show_igmp.py#LL348-L350C79](https://github.com/CiscoTestAutomation/genieparser/blame/master/src/genie/libs/parser/nxos/show_igmp.py#LL348-L350C79)

**Comment by VladKh** [comment]
Hello @ParimiNeeraja,
Thanks for fix.
