### ISSUE TITLE
IOSXR: ShowL2VPNBridgeDomainDetail parser bug

### ISSUE THREAD

**Issue by agandl046** [CiscoTestAutomation/genieparser#760]
For IOSXR, this expected output is wrong: https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/iosxr/tests/ShowL2vpnBridgeDomainDetail/cli/equal/golden7_expected.py

It is hiding a bug in the ShowL2VPNBridgeDomainDetail parser: https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/iosxr/show_l2vpn.py#L1258

In `golden7_expected.py` starting with Bridge group `B2C`, the `vfi` section is incorrect. For domain `SEG180`, it includes the Access PW for domain `SEG242`. For domain `SEG242`, it includes the Access PW for domain `SEG244`. This pattern continues for the other groups and domains.

**Comment by sumitsehgal123** [comment]
Hi .
Thanks for reaching out piestack support team, I will be looking at your ticket and reviewing it . Please make sure add the logs / pyats version / package list .

**Comment by sumitsehgal123** [comment]
Hi ,
I will be working on your ticket. I'll get back to you once I have any update on it.

**Comment by iamsatyanarayan** [comment]
Hi @agandl046 as you mentioned in the issue in expected output_7.py:-  "10.11.44.12": SHOULD ACCESS PW BE UNDER SEG242 that I got it but secondly you mentioned "num_vfi": 1, <<< SAYS 1, BUT THERE ARE 2 [that](https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/iosxr/tests/ShowL2vpnBridgeDomainDetail/cli/equal/golden7_output.txt#L249) i didn't get it properly can you please explain ?

**Comment by agandl046** [comment]
@iamsatyanarayan For context, I am not a network engineer so I may use some terms incorrectly or misunderstand the reasoning behind the schema structure.
 
I agree that the CLI output confirms that there should be 1 VFI. My comment was meant to point out that `10.11.44.12` was under the `vfi` section instead of under the `pw` section. Which is where I assume the Access PWs should go. This part of the [schema](https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/iosxr/show_l2vpn.py#L404), for reference.

**Comment by iamsatyanarayan** [comment]
Hi @agandl046 
I am looking into this. I will inform you once I have any update regarding this issue.

**Comment by kameswararaot** [comment]
Hi @agandl046
I am looking into this. I will inform you once I have any update regarding this issue.

**Comment by kameswararaot** [comment]
Hi @agandl046,

I am checking this issue with my team. I will get back to you.

**Comment by kameswararaot** [comment]
Hi @agandl046,

Still I am working on this issue with my team. I will get back to you.

**Comment by SohanTirpude** [comment]
Hello @agandl046,

For this issue we merged the PR, so the fix will be available in upcoming pyATS version. Hence, I am closing this issue. If you are still seeing this issue with newer pyATS version, then kindly let me know. If you have any other issues, kindly open a new ticket.

Thank you.
