### ISSUE TITLE
show Processes cpu sorted" parse failure for IOSXE on Cisco WS-C4507R+E

### ISSUE THREAD

**Issue by rrahimm** [CiscoTestAutomation/genieparser#782]
I am trying to parse "show Processes cpu sorted" for IOSXE on Cisco WS-C4507R+E and getting an empty dictionary as below

{}

Attached is the CLI output and Parsed output for reference.

[2023-08-21T14_37_53.530412__HC_CPU__parsed.txt](https://github.com/CiscoTestAutomation/genieparser/files/12429032/2023-08-21T14_37_53.530412__HC_CPU__parsed.txt)
[2023-08-21T14_37_53.530412__HC_CPU__rawoutput.txt](https://github.com/CiscoTestAutomation/genieparser/files/12429033/2023-08-21T14_37_53.530412__HC_CPU__rawoutput.txt)

Device details

Hardware: Catalyst 4500 L3 Switch
Version: 03.08.07.E
image: bootflash:cat4500es8-universalk9.SPA.03.08.07.E.152-4.E7.bin

**Comment by sumitsehgal123** [comment]
Hi ,
Thanks for reaching out piestack support team,. And also recommend you to use the latest pyats version(23.9) / package list .

**Comment by sumitsehgal123** [comment]
Hi , 
Please could share the pip list .we will recommend you  to use always latest version of pyats version i.e 23.8

**Comment by sumitsehgal123** [comment]
Hi , 
I am looking into this and get back to you .

**Comment by sowmyadn010501** [comment]
Hello rrahimm,
can you please re-run the checks in your upgraded environment.

**Comment by sowmyadn010501** [comment]
PR has been merged. It will reflect in next release. Hence I am closing this ticket
