### ISSUE TITLE
parser.nxos.show_bgp.py does not support ASN dot format

### ISSUE THREAD

**Issue by ghoppers-yfzh** [CiscoTestAutomation/genieparser#784]
Noticed the parser returns error when dealing with ASN in dot format on nxos (Nexus9500).
Got the following error, the ASN is '65510.111' for the BGP neighbor isn't an integer. But in show_bgp.py it is always expected to be an int for ASN. It would be great the dot format ASN can be supported.
Thank you!
```
Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 531, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 570, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/conf/base/device.py", line 568, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 308, in genie.metaparser._metaparser.MetaParser.parse
  File "./venv/lib/python3.8/site-packages/genie/libs/parser/nxos/show_bgp.py", line 3800, in cli
    nbr_af_dict['as'] = int(m.groupdict()['as'])
ValueError: invalid literal for int() with base 10: '65510.111'
```

**Comment by ghoppers-yfzh** [comment]
Hi kameswararaot,

Checked [#771](url) it is about show bgp vrf all neighbors. My issue is mainly about class ShowBgpVrfAllAllSummary.
The command output is like following:
```
router-a# show bgp vrf all all summary
Neighbor        V    AS    MsgRcvd    MsgSent   TblVer  InQ OutQ Up/Down  State/PfxRcd
2.2.2.2    4 1.57920      29146      29136      152    0    0 04:52:49 12       
```
Managed tweaking the package file a bit and it seems working now.
Changed couple places including the variable type and regex to match the ASDot format. 
Is that something I can contribute?

**Comment by kameswararaot** [comment]
Hi ghoppers,

Could you please share me the full output for parser testing.

**Comment by ghoppers-yfzh** [comment]
The output from device of command "show bgp vrf all all summary" is like the follwing, changed some numbers for privacy reason:
```
router-a# show bgp vrf all all summary
BGP summary information for VRF 100, address family IPv4 Unicast
BGP router identifier 1.1.1.1, local AS number 65100
BGP table version is 159, IPv4 Unicast config peers 5, capable peers 5
28 network entries and 44 paths using 9264 bytes of memory
BGP attribute entries [28/9856], BGP AS path entries [13/158]
BGP community entries [20/940], BGP clusterlist entries [0/0]
14 received paths for inbound soft reconfiguration
0 identical, 14 modified, 0 filtered received paths using 224 bytes
Neighbor        V    AS    MsgRcvd    MsgSent   TblVer  InQ OutQ Up/Down  State/PfxRcd
2.2.2.2    4 1.57920      29146      29136      152    0    0 04:52:49 12        
```
In the current release of show_bgp.py, it set the 'as' as int which doesn't match the dot format.
https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/nxos/show_bgp.py#L3477

**Comment by kameswararaot** [comment]
Hi ghoppers,

Thanks for providing the details. Please give us some time to fix the issue.

**Comment by ghoppers-yfzh** [comment]
Thank you. 
BTW, it is from Nexus9000 version 10.2(5).

**Comment by kameswararaot** [comment]
ok, Please give us some time to fix the issue.

**Comment by kameswararaot** [comment]
Hi ghoppers,

Raised draft PR
PR link:- https://wwwin-github.cisco.com/pyATS/genieparser/pull/2884/files

**Comment by ghoppers-yfzh** [comment]
Thank you. Althrough that url is not reachible. lol

**Comment by kameswararaot** [comment]
Hi ghoppers,

This is only a draft PR to check the changes; it will take some more time to fix this issue.

**Comment by ghoppers-yfzh** [comment]
Thank you.
Just a side question, NXOS supports  json and xml format output, why not using those as it is much easier to parse?
For example "show bgp vrf all all summary | json"

**Comment by tom0010** [comment]
In my experience it's because of how long it takes to execute show commands with big outputs in json formats on nxos. 
It's way quicker to parse them through the native CLI.

**Comment by ghoppers-yfzh** [comment]
That is true. It takes longer for getting output in those special formats.

**Comment by kameswararaot** [comment]
Hi ghoppers,

PR has been merged. It will reflect in next release.

**Comment by kameswararaot** [comment]
Hi ghoppers,

PR has been merged. It will reflect in next release. Hence I am closing this ticket. If you are still experiencing the same problem in next release also, please let me know, and I will reopen the ticket.
