### ISSUE TITLE
genie.libs.cisco added as requirement for genie 23.8 on pypi

### ISSUE THREAD

**Issue by jasonking3** [CiscoTestAutomation/genieparser#785]
Not sure if this is the right place for this issue.  Let me know if I should post it somewhere else.

`pip install genie` is failing on older versions of pip with the following error:

```
ERROR: Could not find a version that satisfies the requirement genie.libs.cisco<23.9.0,>=23.8.0 (from genie) (from versions: none)
ERROR: No matching distribution found for genie.libs.cisco<23.9.0,>=23.8.0 (from genie)
```

Looking at the JSON file for 23.8 (https://pypi.org/pypi/genie/23.8.1/json) I can see that `genie.libs.cisco <23.9.0,>=23.8.0` was added to `requires_dist`, yet no package named genie.libs.cisco actually exists on pypi as far as I can tell.  My observations are that new versions of pip seem to happily ignore this, while older versions (e.g. 20.0.2) error out.

**Comment by ParimiNeeraja** [comment]
I will be working on your ticket. So, kindly give me some time to analyze the issue.

**Comment by ParimiNeeraja** [comment]
Can you please share the below details :

- Python version
- Type of OS and OS version
- pip list for both older(20.0.2) and new versions.

**Comment by ParimiNeeraja** [comment]
Hello @jasonking3 ,

Is there any update, kindly let us know.

**Comment by ParimiNeeraja** [comment]
Hello @jasonking3 ,

Please try with latest pyATS 23.9 version as this issue has been fixed in latest pyATS version.

**Comment by jasonking3** [comment]
@ParimiNeeraja - looks good to me.  Thanks!
