### ISSUE TITLE
Genie IOS-XE parser "show policy-map {name}" not parsing "priority" key/value

### ISSUE THREAD

**Issue by mc4leaf** [CiscoTestAutomation/genieparser#793]
IOS-XE

The show command contains "priority 8 (%)" under a class but this is not being parsed with Genie and is showing an empty dict, the classes that are configured with bandwidth seem to be working as expected.

Config extract:

policy-map BRANCH_TO_WAN
 class Branch_to_WAN_RealTime
  priority 8
 class Branch_to_Evolve_NearRealTime
  bandwidth percent 9 

data pre parser:
  Policy Map BRANCH_TO_WAN
    Class Branch_to_WAN_RealTime
      priority 8 (%)
    Class Branch_to_Evolve_NearRealTime
      bandwidth 9 (%)

data post parser:
{'policy_map': {'BRANCH_TO_WAN': {'class': {'Branch_to_WAN_RealTime': {}, 'Branch_to_Evolve_NearRealTime': {'random_detect': {'bandwidth_percent': 9}}

**Comment by SohanTirpude** [comment]
Hello @mc4leaf,

I will be working on this issue. Can you please let me know the exact output that you used? Is it the one under `data pre parser` or `Config extract`? Kindly let me know.

Thank you.

**Comment by mc4leaf** [comment]
Hi Sohan, 

Thanks for picking this one up, the data used was the "Pre parser" I have actually come up with a fix for the issue locally but have not been able to submit the code as yet (still learning).  Please feel free to use the code below or build from it. 

file - /genie/libs/parser/iosxe

## Line 2536
        p10_2 = re.compile(r'^priority +(?P<priority_percent>(\d+)) .*$')
        
## Line 2856
            m = p10_2.match(line)
            if m:
                class_map_dict['priority'] = True
                priority_percent = int(m.groupdict()['priority_percent'])
                class_map_dict['priority_percent'] = priority_percent

                continue

**Comment by SohanTirpude** [comment]
Hello @mc4leaf,

If you have found the solution by yourself, then I will encourage you to submit the fix. All contribution are welcomed and encouraged. So, kindly do that and let me know if you need any help in raising the PR.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @mc4leaf,

Will you be interested to contribute to the repo? Kindly let me know if you need any help.

Thank you.

**Comment by mc4leaf** [comment]
Hey @SohanTirpude,
apologies for the delay, yes I am definitely interested in contributing,  I will look to get something in on Friday.  If i have any issues I will reach out, thank you for the offer..

Cheers,

**Comment by SohanTirpude** [comment]
Hello @mc4leaf,

No worries, you may take your time. I just wanted to check and confirm whether you will be contributing or not. Thanks for input. Kindly let me know if you need any help.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @mc4leaf,

Did you try to submit your solution? Kindly let me know.

Thank you.

**Comment by mc4leaf** [comment]
Hey @SohanTirpude,

I have just submitted the pull request,
https://github.com/CiscoTestAutomation/genieparser/pull/799

Hopefully I have done it correctly.

Cheers.

**Comment by SohanTirpude** [comment]
Hello @mc4leaf,

Great job! Your PR looks good, only few minor modifications are required. I have left few comments regarding those on your PR, kindly check those and let me know if you have any questions.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @mc4leaf,

Did you get a chance to look at the reviews on your PR? Kindly let me know.

Thank you.

**Comment by mc4leaf** [comment]
Hey @SohanTirpude,

Yes, I have added the files, I thought I had already pushed the updated, but it turned out not.  I have just done the push so the files are now on the PR.

Thank you, for the help and advise you have been providing for this one, it is really appreciated.

**Comment by SohanTirpude** [comment]
Hello @mc4leaf,

Thank for adding the files, but it seems that you failed to address my comments on you PR. Kindly address those as well.

Thank you.

**Comment by 4Leaf83** [comment]
Hi @SohanTirpude,

Thanks for your inputs but i am unable to find the comments, I have checked the files but there doesn't seem to be any comments.  Grateful if you could point me in the right direction..

**Comment by mc4leaf** [comment]
Hi @SohanTirpude,

Thanks for your inputs but I am unable to find the comments, I have checked the files but there doesn't seem to be any comments. Grateful if you could point me in the right direction..

**Comment by SohanTirpude** [comment]
Hello @mc4leaf,

Sorry, my mistake. I forgot to submit my reviews. But you may check now and let me know if you have any questions.

Thank you.

**Comment by mc4leaf** [comment]
Awesome thanks for adding those.

I have checked over them and updated as necessary,

**Comment by SohanTirpude** [comment]
Hello @mc4leaf,

Thanks, I have requested a couple of more changes, kindly address those as well.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @mc4leaf,

I have added more review comments, kindly address those as well.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @mc4leaf,

Kindly check the latest comments on your PR and address those.

Thank you.

**Comment by mc4leaf** [comment]
Thanks again for your inputs @SohanTirpude I have updated the necessary,

**Comment by SohanTirpude** [comment]
Hello @mc4leaf,

The expected output does not match with the output you shared in txt file. Kindly re-work on it. 

Also once done, run below commands:
```
make clean
make develop
make json
```
And, then go to the `tests` folder and run the command `python folder_parsing_job.py -o iosxe -c ShowPolicyMap` which will test all golden output UTs.

Kindly let me know if you have any questions.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @mc4leaf,

Kindly address the review comments shared on your PR so we can take it further for approval.

Thank you.

**Comment by mc4leaf** [comment]
> Hello @mc4leaf,
> 
> Kindly address the review comments shared on your PR so we can take it further for approval.
> 
> Thank you.

Hi @SohanTirpude, 
apologies, I have been away and offline, I will look to correct the issues and complete the review in the next day or so.

MC

**Comment by mc4leaf** [comment]
Apologies again, Golden output files updated, and now working as intended.

**Comment by SohanTirpude** [comment]
Hello @mc4leaf,

Everything looks good, we can procced to approve but before that there are couple of minor changes required. Kindly make those changes soon.

Thank you.

**Comment by mc4leaf** [comment]
Thanks again @SohanTirpude for your guidance, 
I have updated the code as requested. 

Cheers.

**Comment by SohanTirpude** [comment]
Hello @mc4leaf,

Great! Now, only one thing is pending and that is you will have to update your branch with the master and push again. Kindly do that and once pipeline checks are passed then you may merge it.

Kindly do so and let me know if you have any questions.

Thank you.

**Comment by mc4leaf** [comment]
@SohanTirpude.

This is now done, everything is up to date form what I can see. 

Cheers,

**Comment by SohanTirpude** [comment]
Hello @mc4leaf,

Thank you for your contribution. The PR got merged and the fix will be available to use in the upcoming pyATS 24.2 version. Hence, I am closing this issue. 

Thank you.
