### ISSUE TITLE
"show bgp process vrf <vrf>" parser dosen't parse the evpn import/export route target 

### ISSUE THREAD

**Issue by PouriyaGD** [CiscoTestAutomation/genieparser#795]
hello all 
i'm trying to parse the command "show bgp process vrf <vrf>" on nexus switches which is running vxlan evpn,
to get vxlan bgp evpn but it dosent return RT,RD part of ipv4

**Comment by kameswararaot** [comment]
Hi PouriyaGD,

I am working on this issue. Could you please share me the device output to find out the issue?

**Comment by PouriyaGD** [comment]
Hi...yeah for sure
but to clarify the problem, it dosen't show the RT and RD in Ipv4 section in output at all 
and in device CLI is like :
Auto RT is configured
    EVPN Auto RT is configured
    Export RT list:
        ASnumber:100 ASnumebr:91100



the parser output is like:
{
  "vrf": {
    "vrf1": {
      "address_family": {
        "ipv4 unicast": {
          "label_mode": "per-vrf",
          "mvpn_export_rt_list": "ASnumber:91100",
          "mvpn_import_rt_list": "ASnumer:91100",
          "next_hop_trigger_delay": {
            "critical": 3000,
            "non_critical": 10000
          },
          "peers": {
            "0": {
              "active_peers": 0,
              "aggregates": 0,
              "networks": 3,
              "paths": 199,
              "routes": 97
            }
          },
          "table_id": "0x3",
          "table_state": "up"
        },
        "ipv6 unicast": {
          "evpn_export_rt_list": "ASnumber:91100",
          "evpn_import_rt_list": "ASnumber:91100",
          "export_rt_list": "ASnumber:91100",
          "import_rt_list": "ASnumber:91100",
          "label_mode": "per-vrf",
          "mvpn_export_rt_list": "ASnumber:91100",
          "mvpn_import_rt_list": "ASnumber:91100",
          "next_hop_trigger_delay": {
            "critical": 3000,
            "non_critical": 10000
          },
          "peers": {
            "0": {
              "active_peers": 0,
              "aggregates": 0,
              "networks": 0,
              "paths": 0,
              "routes": 0
            }
          },
          "table_id": "0x80000003",
          "table_state": "up"
        }
      },
      "cluster_id": "0.0.0.0",
      "conf_router_id": "0.0.0.0",
      "confed_id": 0,
      "encap_type": "VXLAN",
      "num_conf_peers": 0,
      "num_established_peers": 0,
      "num_pending_conf_peers": 0,
      "router_id": "1.1.1.1",
      "router_mac": "648f.3e27.eb67",
      "topo_id": "1100",
      "vip_derived_mac": "648f.3e27.eb67",
      "vnid": "91100",
      "vrf_id": "3",
      "vrf_rd": "2.2.2.2:3",
      "vrf_state": "up",
      "vtep_ip": "2.2.2.2",
      "vtep_vip_r": "0.0.0.0",
      "vtep_virtual_ip": "2.2.2.2"
    }
  }
}

**Comment by kameswararaot** [comment]
Hi PouriyaGD,

With out the full device out put I am not able to find the issue. Could you please share me the Full device output? I will try to parse and check it from my end.

**Comment by PouriyaGD** [comment]
Information regarding configured VRFs:

BGP Information for VRF 1
VRF Id                         : 3
VRF state                      : UP
VNID                           : 91100 (valid)
Topo Id                        : 1100
Encap type                     : VXLAN
VTEP IP                        : 1.1.1.1
VTEP Virtual IP                : 1.1.1.1
VTEP VIP-R                     : 0.0.0.0
Router-MAC                     : 648f.3e27.eb89
VIP Derived MAC                : 648f.3e27.e789
VIP-R Derived MAC              : 0000.0000.0000
Router-ID                      : 1.1.1.1
Configured Router-ID           : 0.0.0.0
Confed-ID                      : 0
Cluster-ID                     : 0.0.0.0
No. of configured peers        : 0
No. of pending config peers    : 0
No. of established peers       : 0
VRF RD                         : 1.1.1.1:3
VRF Secondary RD               : Not configured

    Information for address family IPv4 Unicast in VRF 1
    Table Id                   : 0x3
    Table state                : UP
    Peers      Active-peers    Routes     Paths      Networks   Aggregates
    0          0               97         199        3          0         

    Redistribution                
        None

    Auto RT is configured
    EVPN Auto RT is configured
    Export RT list:
        ASnumber:100 ASnumber:91100 
    Import RT list:
        ASnumber:100 ASnumber:91100 
    EVPN Export RT list:
        ASnumber:100 ASnumber:91100 
    EVPN Import RT list:
        ASnumber:100 ASnumber:91100 
    MVPN Export RT list:
        ASnumber:91100 
    MVPN Import RT list:
        ASnumber:91100 
    Label mode: per-vrf


    Nexthop trigger-delay
        critical 3000 ms
        non-critical 10000 ms

    Information for address family IPv6 Unicast in VRF 1
    Table Id                   : 0x80000003
    Table state                : UP
    Peers      Active-peers    Routes     Paths      Networks   Aggregates
    0          0               0          0          0          0         

    Redistribution                
        None

    Export RT list:
        ASnumber:91100 
    Import RT list:
        ASnumber:91100 
    EVPN Export RT list:
        ASnumber:91100 
    EVPN Import RT list:
        ASnumber:91100 
    MVPN Export RT list:
        ASnumber:91100 
    MVPN Import RT list:
        ASnumber:91100 
    Label mode: per-vrf


    Nexthop trigger-delay
        critical 3000 ms
        non-critical 10000 ms

**Comment by kameswararaot** [comment]
Hi PouriyaGD,

Thanks for sharing the device output. I will check and let you know the status.

**Comment by PouriyaGD** [comment]
Thanks alot

**Comment by kameswararaot** [comment]
Hi PouriyaGD,

Found the issue and PR has been raised.

**Comment by kameswararaot** [comment]
Hi PouriyaGD,

PR has been merged. It will reflect in next release. Hence I am closing this ticket. If you are still experiencing the same problem in next release also, please let me know, and I will reopen the ticket.
