### ISSUE TITLE
"Show ip nhrp nhs Tunnel1 detail" fails to parse

### ISSUE THREAD

**Issue by alurmtr** [CiscoTestAutomation/genieparser#798]
Unable to parse output for command 'show ip nhrp nhs Tunnel1 detail' (Missing keys: [['Tunnel1', 'nhs_ip']])

mydevice#sh ip nhrp nhs Tunnel 1 detail 
Legend:	E=Expecting replies, R=Responding, W=Waiting, D=Dynamic
Tunnel1:
10.0.0.1  RE  priority = 0 cluster = 0  req-sent 34560  req-failed 0  repl-recv 26580 (00:03:14 ago)

**Comment by sumsehga** [comment]
Hi ,
Kindly give sometime analyze your issue and get back to you.

**Comment by sowmyadn010501** [comment]
Hello alurmtr],
[PR](https://wwwin-github.cisco.com/pyATS/genieparser/pull/2989) has been merged. It will reflect in next release. Hence I am closing this ticket
