### ISSUE TITLE
[NX-OS] - "show running-configuration interface" - Missing fabric forwarding mode

### ISSUE THREAD

**Issue by jp2195** [CiscoTestAutomation/genieparser#809]
The show running-configuration interface parser is missing the `fabric forwarding mode` section. 

Example Configuration:
```
interface vlan 200
  vrf member TEST
  ip address 10.1.1.1/30
  fabric forwarding mode anycast-gateway
```

Example output:

```
'interface': {
        'Vlan200': {
            'switchport': False,
            'mtu': 9216,
            'vrf_member': 'TEST',
            'ip_address': '10.1.1.1/30'
        },
```

**Comment by sowmyadn010501** [comment]
I will be looking in to your ticket. Kindly give me some time

**Comment by sowmyadn010501** [comment]
[PR](https://wwwin-github.cisco.com/pyATS/genieparser/pull/3036) raised. I will update you once it got merged

**Comment by sowmyadn010501** [comment]
PR has been merged. It will reflect in next release. Hence I am closing this ticket
