### ISSUE TITLE
[NXOS] - "show running-config interface"  - IP address being overwritten when there are more than one

### ISSUE THREAD

**Issue by jp2195** [CiscoTestAutomation/genieparser#810]
When doing show running-config interface it looks like any secondary IP address is overwriting the primary IP address. 

Example output:

```
interface Ethernet1/1
  description genie test
  no switchport
  mtu 9216
  vrf member TEST
  ip address 10.1.1.1/30
  ip address 10.2.1.1/30 secondary

```
Example:
```
        'Ethernet1/1': {
            'description': 'genie test',
            'switchport': False,
            'mtu': 9216,
            'vrf_member': 'TEST',
            'ip_address': '10.2.1.1/30 secondary'
        }
```

**Comment by SohanTirpude** [comment]
Hello @jp2195,

Ok, I understood the issue. I will try to make the changes and have a list of ip addresses to `ip_address` key. Kindly let me know if that's how you wanted.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @jp2195,

I have raised the PR for this and now this is how the output looks like:

```
{
    "interface": {
        "Ethernet1/1": {
            "description": "genie test",
            "switchport": False,
            "mtu": 9216,
            "vrf_member": "TEST",
            "ip_address": [
                "10.1.1.1/30",
                "10.2.1.1/30 secondary"
            ]
        }
    }
}
```

Kindly check and confirm whether it meets your expectation or not.

Thank you.

**Comment by jp2195** [comment]
Looks good to me. Thanks!

**Comment by SohanTirpude** [comment]
Hello @jp2195,

The PR got merged and the fix will be available in the upcoming pyATS version.

Also, there is a slight change in the final output, it will be like this:

```
{
    "interface": {
        "Ethernet1/1": {
            "description": "genie test",
            "switchport": False,
            "mtu": 9216,
            "vrf_member": "TEST",
            "ip_address": "10.1.1.1/30",
            "ip_address_secondary": "10.2.1.1/30"
        }
    }
}
```

I hope it is on the same lines of your expectations. Meanwhile, I will be closing this issue. If with newer pyATS version as well if you are seeing the same, then kindly re-open the ticket.

Thank you.
