### ISSUE TITLE
issue with show running-config bgp

### ISSUE THREAD

**Issue by nimadaneshvar** [CiscoTestAutomation/genieparser#811]
I am facing an issue with show running-config bgp on both nxos and ios-xe.

I am using pyATS to parse the result with python.
`Python: 3.8.10 [64bit]

  Package                      Version
  ---------------------------- -------
  genie                        23.11  
  genie.libs.clean             23.11  
  genie.libs.conf              23.11  
  genie.libs.filetransferutils 23.11  
  genie.libs.health            23.11  
  genie.libs.ops               23.11  
  genie.libs.parser            23.11  
  genie.libs.robot             23.11  
  genie.libs.sdk               23.11  
  genie.telemetry              23.11  
  genie.trafficgen             23.11  
  pyats                        23.11  
  pyats.aereport               23.11  
  pyats.aetest                 23.11  
  pyats.async                  23.11  
  pyats.connections            23.11  
  pyats.contrib                23.11  
  pyats.datastructures         23.11  
  pyats.easypy                 23.11  
  pyats.kleenex                23.11  
  pyats.log                    23.11  
  pyats.reporter               23.11  
  pyats.results                23.11  
  pyats.robot                  23.11  
  pyats.tcl                    23.11  
  pyats.topology               23.11  
  pyats.utils                  23.11  
  rest.connector               23.11  
  unicon                       23.11  
  unicon.plugins               23.11  
  yang.connector               23.11`
  
  the code that I use to run and parse the code is:
  
 from genie.testbed import load
   tb = load("test_testbed.yml") 
  dev =  tb.devices['AC2004-SR1'] 
  dev.connect() 
  bgp_config = dev.parse("show running-config bgp") 
  with open("./bgp_config") as f: 
       f.write(json.dumps(bgp_config, indent=4)) 
       

the result that I get is 

{
        "name": "AC2004-SR1",
        "type": "nxos",
        "bgp_config": {
            "bgp": {
                "instance": {
                    "default": {
                        "bgp_id": 65301,
                        "protocol_shutdown": true,
                        "vrf": {
                            "default": {
                                "graceful_restart": true,
                                "log_neighbor_changes": true,
                                "router_id": "10.0.221.255",
                                "enforce_first_as": true,
                                "fast_external_fallover": true,
                                "flush_routes": false,
                                "isolate": false,
                                "af_name": {
                                    "ipv4 unicast": {
                                        "af_client_to_client_reflection": true,
                                        "af_network_number": "192.168.0.0",
                                        "af_network_mask": 16,
                                        "af_redist_connected": true,
                                        "af_redist_connected_route_policy": "RM-BGP-REDIST-CONNECTED-BGP",
                                        "af_aggregate_address_ipv4_address": "10.2.0.0",
                                        "af_aggregate_address_ipv4_mask": 16,
                                        "af_maximum_paths_ebgp": 4,
                                        "af_maximum_paths_ibgp": 4,
                                        "af_nexthop_trigger_enable": true,
                                        "af_nexthop_trigger_delay_critical": 200,
                                        "af_nexthop_trigger_delay_non_critical": 300
                                    }
                                    ...
 as you can see it is onley one network detected for **af_network_number**
 
 while there are number of networks being advertised on the box only the last one is captured by pyATS:
 
 router bgp 65301
  router-id 10.0.221.255
  log-neighbor-changes
  address-family ipv4 unicast
    network 10.0.0.0/8
    network 10.121.126.0/30
    network 10.121.126.64/30
    network 10.121.126.80/30
    network 172.16.0.0/12
    network 192.168.0.0/16
    redistribute direct route-map RM-BGP-REDIST-CONNECTED-BGP
    aggregate-address 10.2.0.0/16
    maximum-paths 4
    maximum-paths ibgp 4
    nexthop trigger-delay critical 200 non-critical 300
    additional-paths install backup
  template peer CMD-Domain-FW
  
  I would appreciate if you guys can advise.

**Comment by SohanTirpude** [comment]
Hello @nimadaneshvar,

For nxos, we recently added support for multiple `af_network_number` and `af_network_mask`, and using that fix I am able to get the below output using your raw output:

```
{
    "bgp": {
        "instance": {
            "default": {
                "bgp_id": 65301,
                "protocol_shutdown": False,
                "vrf": {
                    "default": {
                        "graceful_restart": True,
                        "log_neighbor_changes": True,
                        "router_id": "10.0.221.255",
                        "enforce_first_as": True,
                        "fast_external_fallover": True,
                        "flush_routes": False,
                        "isolate": False,
                        "af_name": {
                            "ipv4 unicast": {
                                "af_client_to_client_reflection": True,
                                "af_network_number": [
                                    "10.0.0.0",
                                    "10.121.126.0",
                                    "10.121.126.64",
                                    "10.121.126.80",
                                    "172.16.0.0",
                                    "192.168.0.0"
                                ],
                                "af_network_mask": [
                                    8,
                                    30,
                                    30,
                                    30,
                                    12,
                                    16
                                ],
                                "af_redist_connected": True,
                                "af_redist_connected_route_policy": "RM-BGP-REDIST-CONNECTED-BGP",
                                "af_aggregate_address_ipv4_address": "10.2.0.0",
                                "af_aggregate_address_ipv4_mask": 16,
                                "af_maximum_paths_ebgp": 4,
                                "af_maximum_paths_ibgp": 4,
                                "af_nexthop_trigger_enable": True,
                                "af_nexthop_trigger_delay_critical": 200,
                                "af_nexthop_trigger_delay_non_critical": 300
                            }
                        }
                    }
                },
                "peer_name": {
                    "CMD-Domain-FW": {}
                }
            }
        }
    }
}
```
This fix will be available to use in the upcoming pyATS 24.1 version. So, kindly try that and let me know.

For IOSXE, I could not find the parser for command: `show running-config bgp`. So, kindly let me know which command you are using for IOSXE and what is the output you are getting.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @nimadaneshvar,

Kindly provide an update soon on this.

Thank you.

**Comment by nimadaneshvar** [comment]
Hey Sohan,

thank you for your reply.  you are right I was mistaken all of my devices are NXOS. can I upgrade my pyATS version now?

thanks 
Nima

**Comment by SohanTirpude** [comment]
Hello @nimadaneshvar,

Soon pyATS 24.1 version will be released, then you may update it. Kindly do so and let me know the update on this.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @nimadaneshvar,

pyATS 24.1 version is released, can you please check and confirm regarding this issue?

Thank you.

**Comment by SohanTirpude** [comment]
Hello @nimadaneshvar,

Have you got a chance to update your pyATS and try it again? Kindly let me know.

Thank you.

**Comment by nimadaneshvar** [comment]
Hey Sohan,

it is fixed. Thanks for the quick response.

cheers
Nima

**Comment by SohanTirpude** [comment]
Hello @nimadaneshvar,

Thank you for the confirmation, hence I am closing this issue. If you face any other issues, kindly open a new ticket.

Thank you.
