### ISSUE TITLE
Request for enhancement: Be able to enter JUNOS shell and run commands

### ISSUE THREAD

**Issue by assadniang** [CiscoTestAutomation/genieparser#816]
Hello,

I am not sure if this is the right place for request?

I would like to request to be able to enter JUNOS linux shell and run commands
https://community.cisco.com/t5/tools/how-to-send-junos-shell-command-with-pyats/m-p/5006933#M3455

Currently, we we try to enter the linux shell in junos, the code crashes
We are not parsing any output in the linux shell, but mostly run execute()

**Comment by SohanTirpude** [comment]
Hello @assadniang,

Well as per this document: https://pubhub.devnetcloud.com/media/unicon/docs/user_guide/services/junos.html we have support for JUNOS but only for `configure` service, it seems. And hence, it might be not working when `execute` service used.

Still, I will advise to close this ticket and open a new ticket in `unicon.plugin` repo here: https://github.com/CiscoTestAutomation/unicon.plugins/issues with all the logs, code and error you are seeing.

Kindly let me know if you have any questions.

**Comment by assadniang** [comment]
OK, thank you!

**Comment by assadniang** [comment]
OK, thank you!
