### ISSUE TITLE
Regex Logic Incomplete

### ISSUE THREAD

**Issue by pawgoel** [CiscoTestAutomation/genieparser#817]
https://github.com/CiscoTestAutomation/genieparser/blame/df9ca29ba5fac0ba6880486381bc8e1e6ce3a81e/src/genie/libs/parser/iosxe/show_arp.py#L1410

r'(?P<acl_logging>[a-zA-Z]+) this has to be ---> r'(?P<acl_logging>[a-zA-Z-]+)

else :
giving issue like : 4308:  Failed reason: Missing keys: [['acl_logging'], ['dhcp_logging'], ['probe_logging']]

as "acl_logging", "dhcp_logging" and "probe_logging" are not optional in schema and output is not containing these.

**Comment by SohanTirpude** [comment]
Hello @pawgoel,

Thank you for letting us know this issue. Can you please share your raw output for which you got this error?

Thank you.

**Comment by SohanTirpude** [comment]
Hello @pawgoel,

Is there any update on this?

Thank you.

**Comment by pawgoel** [comment]
import re
output = '''Source Mac Validation      : Disabled
Destination Mac Validation : Disabled
IP Address Validation      : Disabled

 Vlan     Configuration    Operation   ACL Match          Static ACL
 ----     -------------    ---------   ---------          ----------
   10     Enabled          Active

 Vlan     ACL Logging      DHCP Logging      Probe Logging
 ----     -----------      ------------      -------------
   10     Acl-Match        All               Off'''
   
ret_dict = {}

#Source Mac Validation : Disabled
p1 = re.compile(r'^Source\s+Mac\s+Validation\s+:\s+(?P<src_mac_validation>\S+)')

#Destination Mac Validation : Disabled
p2 = re.compile(r'^Destination\s+Mac\s+Validation\s+:\s+(?P<dst_mac_validation>\S+)')

#IP Address Validation : Disabled
p3 = re.compile(r'^IP\s+Address\s+Validation\s+:\s+(?P<ip_address_validation>\S+)')

#Vlan Configuration Operation ACL Match Static ACL
#10 Enabled Active
p4 = re.compile(r'^(?P<vlan_num>\d+) +'
        r'(?P<configuration>[a-zA-Z]+) +'
        r'(?P<operation>[a-zA-Z]+$)')

#Vlan ACL Logging DHCP Logging Probe Logging
#10 Deny Deny Off        
p5 = re.compile(r'^(?P<vlan>\d+) +'
        r'(?P<acl_logging>[a-zA-Z]+) +'
        r'(?P<dhcp_logging>[a-zA-Z]+) +'
        r'(?P<probe_logging>[a-zA-Z]+$)')

for line in output.splitlines():
    line = line.strip()

    #Source Mac Validation : Disabled
    m1 = p1.match(line)
    if m1:
        group = m1.groupdict()
        ret_dict["source_mac_validation"] = group["src_mac_validation"]
    
    #Destination Mac Validation : Disabled
    m2 = p2.match(line)
    if m2:
        group = m2.groupdict()
        ret_dict["destination_mac_validation"] = group["dst_mac_validation"]

    #IP Address Validation : Disabled 
    m3 = p3.match(line)
    if m3:
        group = m3.groupdict()
        ret_dict["ip_address_validation"] = group["ip_address_validation"]

    #Vlan Configuration Operation ACL Match Static ACL
    #10 Enabled Active
    m4 = p4.match(line)
    if m4:
        group = m4.groupdict()
        ret_dict["vlan"] = int(group["vlan_num"])
        ret_dict["configuration"] = group["configuration"]
        ret_dict["operation"] = group["operation"]
    
    #Vlan ACL Logging DHCP Logging Probe Logging
    #10 Deny Deny Off
    m5 = p5.match(line)
    if m5:
        group = m5.groupdict()
        ret_dict["acl_logging"] = group["acl_logging"]
        ret_dict["dhcp_logging"] = group["dhcp_logging"]
        ret_dict["probe_logging"] = group["probe_logging"]

print(ret_dict)

## Output : 

{'source_mac_validation': 'Disabled', 'destination_mac_validation': 'Disabled', 'ip_address_validation': 'Disabled', 'vlan': 10, 'configuration': 'Enabled', 'operation': 'Active'}

**Comment by pawgoel** [comment]
## Right Code

import re
output = '''Source Mac Validation      : Disabled
Destination Mac Validation : Disabled
IP Address Validation      : Disabled

 Vlan     Configuration    Operation   ACL Match          Static ACL
 ----     -------------    ---------   ---------          ----------
   10     Enabled          Active

 Vlan     ACL Logging      DHCP Logging      Probe Logging
 ----     -----------      ------------      -------------
   10     Acl-Match        All               Off'''
   
ret_dict = {}

#Source Mac Validation : Disabled
p1 = re.compile(r'^Source\s+Mac\s+Validation\s+:\s+(?P<src_mac_validation>\S+)')

#Destination Mac Validation : Disabled
p2 = re.compile(r'^Destination\s+Mac\s+Validation\s+:\s+(?P<dst_mac_validation>\S+)')

#IP Address Validation : Disabled
p3 = re.compile(r'^IP\s+Address\s+Validation\s+:\s+(?P<ip_address_validation>\S+)')

#Vlan Configuration Operation ACL Match Static ACL
#10 Enabled Active
p4 = re.compile(r'^(?P<vlan_num>\d+) +'
        r'(?P<configuration>[a-zA-Z]+) +'
        r'(?P<operation>[a-zA-Z]+$)')

#Vlan ACL Logging DHCP Logging Probe Logging
#10 Deny Deny Off        
p5 = re.compile(r'^(?P<vlan>\d+) +'
        r'(?P<acl_logging>[a-zA-Z-]+) +'
        r'(?P<dhcp_logging>[a-zA-Z]+) +'
        r'(?P<probe_logging>[a-zA-Z]+$)')

for line in output.splitlines():
    line = line.strip()

    #Source Mac Validation : Disabled
    m1 = p1.match(line)
    if m1:
        group = m1.groupdict()
        ret_dict["source_mac_validation"] = group["src_mac_validation"]
    
    #Destination Mac Validation : Disabled
    m2 = p2.match(line)
    if m2:
        group = m2.groupdict()
        ret_dict["destination_mac_validation"] = group["dst_mac_validation"]

    #IP Address Validation : Disabled 
    m3 = p3.match(line)
    if m3:
        group = m3.groupdict()
        ret_dict["ip_address_validation"] = group["ip_address_validation"]

    #Vlan Configuration Operation ACL Match Static ACL
    #10 Enabled Active
    m4 = p4.match(line)
    if m4:
        group = m4.groupdict()
        ret_dict["vlan"] = int(group["vlan_num"])
        ret_dict["configuration"] = group["configuration"]
        ret_dict["operation"] = group["operation"]
    
    #Vlan ACL Logging DHCP Logging Probe Logging
    #10 Deny Deny Off
    m5 = p5.match(line)
    if m5:
        group = m5.groupdict()
        ret_dict["acl_logging"] = group["acl_logging"]
        ret_dict["dhcp_logging"] = group["dhcp_logging"]
        ret_dict["probe_logging"] = group["probe_logging"]

print(ret_dict)


## Correct Output :

{'source_mac_validation': 'Disabled', 'destination_mac_validation': 'Disabled', 'ip_address_validation': 'Disabled', 'vlan': 10, 'configuration': 'Enabled', 'operation': 'Active', 'acl_logging': 'Acl-Match', 'dhcp_logging': 'All', 'probe_logging': 'Off'}

**Comment by pawgoel** [comment]
Please have a look, and pardon me for the late reply!!

**Comment by SohanTirpude** [comment]
Hello @pawgoel,

No issue with late response. If you have found the correct fix, then you may raise the PR by yourself. Kindly go through the README of this repo and let me know if you need any help raising the PR.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @pawgoel,

Kindly update if you are interested to contribute to this repo.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @pawgoel,

Ok, I have raised the PR for this issue. Once it is merged, I will update you.

Thank you.

**Comment by pawgoel** [comment]
> Hello @pawgoel,
> 
> Ok, I have raised the PR for this issue. Once it is merged, I will update you.
> 
> Thank you.

Ooh, you did thanks @SohanTirpude, can you please provide me the link for it?

**Comment by SohanTirpude** [comment]
Hello @pawgoel,

I have raised the PR internally, so the link is not available for external users. Once, it is merged, I will update you here. Kindly let me know if this works for you.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @pawgoel,

The PR got merged and the fix will be available in the upcoming pyATS 24.2 version. Hence, I am closing this ticket for now. Kindly update the pyATS to 24.2 and try again. If you are still seeing the issues, then kindly re-open the ticket. 

Thank you.
