### ISSUE TITLE
Extend ShowBgpAddressFamily Class - Enable running "show bgp {address_family} community {community}" on iosxr

### ISSUE THREAD

**Issue by Kani999** [CiscoTestAutomation/genieparser#821]
#### Description
Currently, the `ShowBgpAddressFamily` class in [this file](https://github.com/CiscoTestAutomation/genieparser/blob/882c298551531705697c097fa054f6573fa2c2de/src/genie/libs/parser/iosxr/show_bgp.py#L9091C1-L9091C27) parses commands `show bgp` and `show bgp {address_family}`. However, it needs to be extended to parse additional commands:

- `show bgp {address_family} community {community}`
- `show bgp {address_family} community {community} {exact_match}`

The objective is to ensure that the output of these new commands is compatible with the existing logic for parsing `show bgp`.

#### Requirements
- Extend the `ShowBgpAddressFamily` class to parse the additional commands mentioned above.
- Ensure that the output format of the new commands aligns with the output format of `show bgp` for compatibility with existing parsing logic.

#### Additional Information
This enhancement aims to broaden the capabilities of the `ShowBgpAddressFamily` class to handle a wider range of BGP-related commands, facilitating more comprehensive parsing and analysis of BGP data.

---
#### Another miscellaneous bugs
- Your regex pattern did not work correctly for IPv6 addresses. The regex in the address ignored the format [a-f]. 
---
Additionally, your code does not handle IPv6 outputs from BGP correctly.
Example:
```
s>i2001:718::2:99/128 195.113.156.4            0    100      0 i
s i                   195.113.156.4            0    100      0 i
s>i2001:718::2:101/128
                      10.2.8.1                 0    100      0 i
s i                   10.2.8.1                 0    100      0 i
s>i2001:718::2:116/128
                      195.113.156.9         1000    205      0 65086 i
s i                   195.113.156.9         1000    205      0 65086 i
s i                   2001:718:0:600:0:1a:1a:11
                                            1000    110      0 65086 i
```
- [Your current regex](https://regex101.com/r/w6F0eT/1)
- [My Edit](https://regex101.com/r/18lHd3/1)

In this state, it completely ignores that the next hop and metrics are listed on the next line. My regex corrects this, **however, there is a flaw in your code**: you use a multiline regex but execute it on individual lines, which does not make sense. To make the code work correctly now, I need to modify the device output to this format:

```
s>i2001:718::2:99/128 195.113.156.4            0    100      0 i
s i                   195.113.156.4            0    100      0 i
s>i2001:718::2:101/128                      10.2.8.1                 0    100      0 i
s i                   10.2.8.1                 0    100      0 i
s>i2001:718::2:116/128                      195.113.156.9         1000    205      0 65086 i
s i                   195.113.156.9         1000    205      0 65086 i
s i                   2001:718:0:600:0:1a:1a:11                                            1000    110      0 65086 i
```
- [Your current regex](https://regex101.com/r/OUMOf9/2)
- [My Edit](https://regex101.com/r/vTCRGp/1)

This is achieved with the following code:
```python
    raw_result = device.execute(command)        
    raw_result = raw_result.replace('\r\n', '\n')    
    lines = raw_result.split('\n')
    result = [lines[0]]

    for line in lines[1:]:
        if line.startswith(' '):
            result[-1] += line
        else:
            result.append(line)

    formatted_text = '\n'.join(result)

   # Run GENIE with preprocessed formatted text
   device.parse(command, output=formatted_text)
```

This code concatenates lines that start with a space to the previous line.

With this output modification and my changes in the pull request, the "show bgp" command works for both IPv4 and IPv6 addresses. Currently, your implementation for IPv6 is not functional.

**Comment by SohanTirpude** [comment]
Hello @Kani999,

Thanks for taking care of the issue by yourself. I will check with the reviewers to get this PR reviewed soon.

**Comment by SohanTirpude** [comment]
Hello @Kani999, 

Kindly fix the failing checks in your PR. If everything is correct at your end then re-trigger the checks with [empty commit](https://stackoverflow.com/questions/20138640/pushing-empty-commits-to-remote).

**Comment by SohanTirpude** [comment]
Hello @Kani999,

Reviewer has shared their reviews on your PR so kindly address those soon.

**Comment by Kani999** [comment]
@SohanTirpude I'll take a look at it, but currently I think I will be able to do it during the second half of April. 
During a fresh installation of `genieparser` and running tests locally, I failed on **Install Dependencies**:

[Link to error](https://github.com/CiscoTestAutomation/genieparser/actions/runs/8049758739/job/21983808660?pr=822)

```
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
unknown package:
Expected sha256 65d99392fb36a816ed1bc7ef19e7a23b9ef365[481](https://github.com/CiscoTestAutomation/genieparser/actions/runs/8049758739/job/21983808660?pr=822#step:4:482)1e02326f80002c258b889c3
Got 84c08c08404cdc00040fab5a1d79c42eece135685e19fb84ae8f3042078371eb

Error: Process completed with exit code 1.
```


And I have nothing to do with those changes. So I don't really know what is wrong with the build. 
Can you take a look at it?

**Comment by SohanTirpude** [comment]
Sure @Kani999.

**Comment by SohanTirpude** [comment]
Hello @Kani999,

We have released pyats 24.3 version, so kindly update your branch with latest, execute "make json" again and push your changes again.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @Kani999,

Kindly pull the latest changes again, update your branch accordingly and try again. I hope you will not see this issue again.

Thank you.

**Comment by Kani999** [comment]
Hi @SohanTirpude,

Everything seems to be working fine now.

---

I've would like to mention again that I've noticed a potential issue in the script implementation. The current regex, although it's multiline, executes on individual lines [here](https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/iosxr/show_bgp.py#L9588), which might not be the intended behavior.

To ensure correct functionality, I had to modify the device output to the following format for IPv6:

```python
# Before: execute CLI command and get output 

for line in lines[1:]:
    if line.startswith(' '):
        result[-1] += line
    else:
        result.append(line)

formatted_text = '\n'.join(result)

# Run GENIE with preprocessed formatted text
device.parse(command, output=formatted_text)
```

This adjustment was necessary because the IPv6 output differs from IPv4, often splitting addresses into multiple lines.

**Comment by SohanTirpude** [comment]
Hello @Kani999,

As requested by reviewers, kindly add unit tests to your PR.

Thank you.

**Comment by Kani999** [comment]
@SohanTirpude 

Unit tests were added.

**Comment by SohanTirpude** [comment]
Hello @Kani999,

Thanks. Let me check with the reviewers then.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @Kani999,

Kindly resolve the conflicts in your PR. 

Thank you.

**Comment by Kani999** [comment]
> Hello @Kani999,
> 
> Kindly resolve the conflicts in your PR.
> 
> Thank you.

Could you please address the conflicts? I'm not able to identify any at the moment

**Comment by SohanTirpude** [comment]
Hello @Kani999,

The conflict is showing in this file: `sdk_generator/outputs/github_parser.json`. Kindly update your branch with latest dev branch and thre re-try again.

Thank you.

**Comment by Kani999** [comment]
Hello, @SohanTirpude 

I've solved the problem to updating genie to latest version. 
Can you look at the PR?

Thank you.

**Comment by SohanTirpude** [comment]
Hello @Kani999,

I have checked the PR but it seems you have not addressed the reviewer's comments. So, please address those and let me know once done.

Thank you.

**Comment by Kani999** [comment]
The reviewer's comments suggested adding unit tests, which I have done. Perhaps they need to be "approved"? I am unsure what else needs to be added to the code.

If I am mistaken, could you please specify what else should be included?

**Comment by Kani999** [comment]
@SohanTirpude I believe that the comments should be solved now.

**Comment by SohanTirpude** [comment]
Hello @Kani999, yeah it looks better now. Kindly give me some time to check with the reviewers on this PR.

**Comment by SohanTirpude** [comment]
Hello @Kani999, 

It looks like your PR got merged. Thank you very much for your contribution. Hence, I am closing this issue. If you are facing any other issues, kindly open a new ticket.

Thank you.
