### ISSUE TITLE
IOSXR, NCS-57C3-MODS-SYS, Version 7.9.2, failed to parse command output for "ping {addr} source {source} repeat {count}"

### ISSUE THREAD

**Issue by JL-Cisco-87** [CiscoTestAutomation/genieparser#828]
**Scenario:**
Using Nornir in Python script to run "ping {addr} source {source} repeat {count}" and parse output with Genie on IOSXR, NCS-57C3-MODS-SYS, Version 7.9.2 

**Issue:**
Parsed output results in empty list being provided. This seems to be due to the fact that IOSXR 7.9.2 for NCS-57C3-MODS-SYS provides output WITHOUT a comma after the IP where as previous versions do include the comma. Examples below:

**IOSXR, NCS-57C3-MODS-SYS, Version 7.9.2**

'Wed Mar 13 14:32:11.524 EDT\nType escape sequence to abort.\nSending 10, 100-byte ICMP Echos to 192.168.0.1 timeout is 2 seconds:\n!!!!!!!!!!\nSuccess rate is 100 percent (10/10), round-trip min/avg/max = 19/19/20 ms'

**IOSXR, NCS-55A2-MOD-SE-S, Version 7.7.21**

'Wed Mar 13 14:35:07.386 EDT\nType escape sequence to abort.\nSending 10, 100-byte ICMP Echos to 192.168.0.1, timeout is 2 seconds:\n!!!!!!!!!!\nSuccess rate is 100 percent (10/10), round-trip min/avg/max = 20/20/21 ms'

![image](https://github.com/CiscoTestAutomation/genieparser/assets/91754488/e9af3ccc-3add-46c3-a92d-3ca610f7947c)

**Comment by Harishv01** [comment]
Hi, Kindly give me some time.I will check and get back to you asap

**Comment by Harishv01** [comment]
I have raised the PR for this. Once it is merged, I will let you know.

Thank you!

**Comment by Harishv01** [comment]
The PR got merged and the fix will be available in the next version.Hence,I am closing the ticket
