### ISSUE TITLE
Problem with "show running-config vrf {vrf} | sec '^vrf'"

### ISSUE THREAD

**Issue by BingPB** [CiscoTestAutomation/genieparser#836]
When running "show running-config vrf {vrf} | sec '^vrf'" for NXOS. Route targets will not appear in parsed output.

genieparser/src/genie/libs/parser/nxos/show_vrf.py
Line 295 change 
from
        p5 = re.compile(r'^\s*route-target +(?P<rt_type>\w+) +(?P<rt>\w+)( +(?P<rt_evpn_mvpn>\w+))?$')
to
        p5 = re.compile(r'^\s*route-target +(?P<rt_type>\w+) +(?P<rt>\w+:\w+)( +(?P<rt_evpn_mvpn>\w+))?$')

Fixes the issue.
The current regex does not match the whole route target, because there is a Colon ":" in it, and \w+ does not match on colons.

I have no idea on how to implement this in this repository. So please help :)

**Comment by Harishv01** [comment]
Please let me know if you need any further assistance with this case, or may I close this ticket now?

**Comment by SohanTirpude** [comment]
Hello @BingPB,

Kindly follow the steps shared in the previous comment to raise a PR. Hence, I am closing this ticket for now. If you are facing any other issues, kindly open a new ticket.

Thank you.
