### ISSUE TITLE
[iosxe] c9400 QpolicerDrop needs to become optional for ShowPlatformHardwareFedActiveQosQueueStats

### ISSUE THREAD

**Issue by YujenS** [CiscoTestAutomation/genieparser#840]
Based on c9400 current behavior, the column QpolicerDrop is removed in the output of "show platform hardware fed active qos queue stats interface". Therefore, QpoliceDrop should become optional and the new format should be handled.

Parser is currently based on:
             DATA Port:1 Drop Counters
            -------------------------------                     
            Queue Drop-TH0    Drop-TH1    Drop-TH2    SBufDrop    QebDrop QpolicerDrop

However, the current output should be like (after iosxe 17.5.1):
            DATA Port:1 Drop Counters
            -------------------------------                     
            Queue Drop-TH0    Drop-TH1    Drop-TH2    SBufDrop    QebDrop

**Comment by Harishv01** [comment]
I will be working on your ticket. Kindly give me some time to analyse the issue.

Thank you!

**Comment by YujenS** [comment]
resolved via cisco internal github
