### ISSUE TITLE
[IOS-XE] Parser for "show lldp neighbors" does not work when no neighbors are present

### ISSUE THREAD

**Issue by ChristopherJHart** [CiscoTestAutomation/genieparser#857]
Sample output:
```
Capability codes:
    (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
    (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other

Device ID           Local Intf     Hold-time  Capability      Port ID

Total entries displayed: 0
```
Error message:
```
SchemaMissingKeyError: Missing keys: [['interfaces']]
```

**Comment by SohanTirpude** [comment]
Hello @ChristopherJHart,

I am looking into this issue. Kindly give me some time to check.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @ChristopherJHart,

The PR has been raised for this issue. Once it is merged, I will update you here. Anyway, the output now looks like this:

```
expected_output = {
    "total_entries": 0
}
```

Kindly check and confirm.

Thank you.

**Comment by ChristopherJHart** [comment]
@SohanTirpude That looks good - thank you!

**Comment by SohanTirpude** [comment]
Hello @ChristopherJHart,

The PR got merged and the fix will be available in the upcoming release. Hence, I am closing this ticket. Kindly try again with the newer release.

Thank you.
