### ISSUE TITLE
[IOS-XE] no peer-group

### ISSUE THREAD

**Issue by dmychepk** [CiscoTestAutomation/genieparser#872]
show bgp all neighbors 100.64.0.0
For address family: IPv4 Unicast
BGP neighbor is 100.64.0.0,  remote AS 1.1, external link
 Description: svs-fc-agg-t2-a-1
 **Member of peer-group T2-ASN1.1 for session parameters**
  BGP version 4, remote router ID 10.230.1.10
  BGP state = Established, up for 01:13:21
...skipped...

This is applicable for:
        * 'show bgp all neighbors'
        * 'show bgp all neighbors {neighbor}'
        * 'show bgp {address_family} all neighbors'
        * 'show bgp {address_family} all neighbors {neighbor}'

if device is configured with peer-group, it shows in show command but parser does not take it into account.
Cisco IOS XE Software, Version 17.09.04a - SMU-PATCHED
Cisco IOS Software [Cupertino], Catalyst L3 Switch Software (CAT9K_IOSXE), Version 17.9.4a, RELEASE SOFTWARE (fc3)

**Comment by SohanTirpude** [comment]
Hello @dmychepk,

Can you please provide the complete output for all these commands so that we can check and confirm this behaviour?

Thank you.

**Comment by dmychepk** [comment]
svs-fc-agg-t2-a-1#show bgp all neighbors 100.64.0.1
For address family: IPv4 Unicast
BGP neighbor is 100.64.0.1,  remote AS 1.101, external link
 Description: svs-fc-agg-t1-a-1
 Member of peer-group T1-ASN1.101 for session parameters
  BGP version 4, remote router ID 0.0.0.0
  BGP state = Idle, down for 06:06:59
  Configured hold time is 15, keepalive interval is 5 seconds
  Minimum holdtime from neighbor is 0 seconds
  Last update received: n/a
  Neighbor sessions:
    0 active, is not multisession capable (disabled)
    Stateful switchover support enabled: NO
  Do log neighbor state changes (via global configuration)
  Default minimum time between advertisement runs is 30 seconds

  Address tracking is enabled, the RIB does have a route to 100.64.0.1
  Route to peer address reachability Up: 6; Down: 0
    Last notification 04:42:49
  Connections established 1; dropped 1
  Last reset 06:06:59, due to Active open failed
  External BGP neighbor not directly connected.
  External BGP neighbor configured for connected checks (single-hop no-disable-connected-check)
  Interface associated: Port-channel1 (peering address NOT in same link)
  Transport(tcp) path-mtu-discovery is enabled
  Graceful-Restart is enabled, restart-time 120 seconds, stalepath-time 360 seconds
  SSO is disabled
  No active TCP connection

For address family: IPv6 Unicast

For address family: IPv4 Multicast

For address family: L2VPN E-VPN

For address family: MVPNv4 Unicast

For address family: MVPNv6 Unicast

For address family: IPv4 Label-Unicast

For address family: IPv6 Label-Unicast

**Comment by sowmyadn010501** [comment]
Hi, thanks for output but can you please share outputs for all the above mentioned command, 
i.e.,
* 'show bgp all neighbors'
* 'show bgp all neighbors {neighbor}'
* 'show bgp {address_family} all neighbors'
* 'show bgp {address_family} all neighbors {neighbor}'

**Comment by sowmyadn010501** [comment]
Hi, I have got this below output after the fix, Kindly check whether it's proper or not
```
{
    "list_of_neighbors": [
        "100.64.0.1"
    ],
    "vrf": {
        "default": {
            "neighbor": {
                "100.64.0.1": {
                    "remote_as": "1.101",
                    "link": "external",
                    "shutdown": False,
                    "address_family": {
                        "ipv4 unicast": {
                            "session_state": "Idle",
                            "down_time": "06:06:59"
                        },
                        "ipv6 unicast": {},
                        "ipv4 multicast": {},
                        "l2vpn evpn": {},
                        "mvpnv4 unicast": {},
                        "mvpnv6 unicast": {},
                        "ipv4 labelunicast": {},
                        "ipv6 labelunicast": {}
                    },
                    "description": "svs-fc-agg-t1-a-1",
                    "peer_group": "T1-ASN1.101",
                    "bgp_version": 4,
                    "router_id": "0.0.0.0",
                    "session_state": "Idle",
                    "bgp_negotiated_keepalive_timers": {
                        "hold_time": 15,
                        "keepalive_interval": 5,
                        "min_holdtime": 0
                    },
                    "bgp_neighbor_session": {
                        "sessions": 0,
                        "stateful_switchover": "NO"
                    },
                    "bgp_session_transport": {
                        "min_time_between_advertisement_runs": 30,
                        "address_tracking_status": "enabled",
                        "rib_route_ip": "100.64.0.1",
                        "connection": {
                            "established": 1,
                            "dropped": 1,
                            "last_reset": "06:06:59",
                            "reset_reason": "Active open failed"
                        },
                        "tcp_path_mtu_discovery": "enabled",
                        "graceful_restart": "enabled",
                        "gr_restart_time": 120,
                        "gr_stalepath_time": 360,
                        "sso": False,
                        "tcp_connection": False
                    }
                }
            }
        }
    }
} 
```
Also can you please share the raw output for below commands

- 'show bgp all neighbors'
- 'show bgp {address_family} all neighbors'
- 'show bgp {address_family} all neighbors {neighbor}'

**Comment by sowmyadn010501** [comment]
Hi, Kindly give us update on this.

**Comment by sowmyadn010501** [comment]
Hi, I have raised the PR for this command `show bgp all neighbors {neighbor}` Once you share the raw output for below commands so that i can check the issue for those commands too. Kindly share the raw outputs with me.

- 'show bgp all neighbors'
- 'show bgp {address_family} all neighbors'
- 'show bgp {address_family} all neighbors {neighbor}'

**Comment by SohanTirpude** [comment]
Hello @dmychepk,

The PR has been merged and the fix will be available in the upcoming pyats version i.e. 24.8. Hence, I am closing this ticket for now. 
Kindly try again after updating the pyats to 24.8 and let us know if you continue to see the same error. If you are facing any other issues, kindly open a new ticket.

Thank you.
