### ISSUE TITLE
[IOS-XR] Parser for 'show ethernet tags' outputs interface names that do not match those in the running configuration

### ISSUE THREAD

**Issue by ajackson79** [CiscoTestAutomation/genieparser#877]
So far in my testing it looks like the IOS-XR parsers convert interface names to match those shown in the running configuration. For example show interface description outputs:

CLI:
Te0/0/0/0.10

Parser:
TenGigE0/0/0/0.10

running config:
TenGigE0/0/0/0.10

When using the show ethernet tags parser however we get the output below:

CLI:
Te0/0/0/0.10

Parser:
TenGigabitEthernet0/0/0/0.10

running config:
TenGigE0/0/0/0.10

If this is to be expected then feel free to close this case and just let me know that is expected. It just seems like you have gone through a lot of trouble to normalize the interface names and this one might have been missed or done incorrectly. Just wanted to let you know it behaves different from others I have tested.

Edit - This seems to only be happening with TenGigE interfaces. Both GigabitEthernet and HundredGigE all show up as they do on the running configuration.

Edit 2 - It looks like the problem is in show_interface.py line 2146. When it converts the interface name it doesn't include the OS type so it defaults to the generic type which is what IOS-XE uses.

**Comment by Harishv01** [comment]
Hi, Please allow me some time to reproduce the issue. Thank you.

**Comment by Harishv01** [comment]
I have fixed this, raised a PR and will let you know once it is merged. Thank you.

**Comment by Harishv01** [comment]
Hi, kindly share the raw output for the `show ethernet tags` command to merge the PR. Thank you.

**Comment by ajackson79** [comment]
Here is a sample output from the command.

`'TenGigabitEthernet0/0/0/24.100': {'mtu': 1514,
                                    'outer_vlan': 'Default',
                                    'rewrite_num_of_tags_pop': 0,
                                    'rewrite_num_of_tags_push': 0,
                                    'status': 'ad'},
 'TenGigabitEthernet0/0/0/25.10': {'inner_vlan': '.1Q:10',
                                   'mtu': 9224,
                                   'outer_vlan': '.1Q:100',
                                   'rewrite_num_of_tags_pop': 2,
                                   'rewrite_num_of_tags_push': 0,
                                   'status': 'up',
                                   'vlan_id': '100'},
 'TenGigabitEthernet0/0/0/26.0': {'mtu': 9216,
                                  'outer_vlan': 'Untagged',
                                  'rewrite_num_of_tags_pop': 0,
                                  'rewrite_num_of_tags_push': 0,
                                  'status': 'up'},
 'TenGigabitEthernet0/0/0/26.10': {'mtu': 9220,
                                   'outer_vlan': '.1Q:10',
                                   'rewrite_num_of_tags_pop': 1,
                                   'rewrite_num_of_tags_push': 0,
                                   'status': 'up',
                                   'vlan_id': '10'},`

**Comment by ajackson79** [comment]
`Mon Aug 19 03:56:39.363 MDT
St:    AD - Administratively Down, Dn - Down, Up - Up
Ly:    L2 - Switched layer 2 service, L3 = Terminated layer 3 service,
Xtra   C - Match on Cos, E  - Match on Ethertype, M - Match on source MAC
-,+:   Ingress rewrite operation; number of tags to pop and push respectively

Interface               St  MTU  Ly Outer            Inner            Xtra -,+
Gi0/0/0/0.200           AD  1522 L2 .1Q:200          .1Q:200-300      -    0 0
Te0/0/0/18.1000         Up  9220 L2 .1Q:1000         -                -    1 0
Te0/0/0/18.1001         Up  9220 L2 .1Q:1001         -                -    1 0
Te0/0/0/18.1002         Up  9220 L2 .1Q:1002         -                -    1 0
Te0/0/0/18.1003         Up  9220 L2 .1Q:1003         -                -    1 0
Te0/0/0/18.1004         Up  9220 L2 .1Q:1004         -                -    1 0
Te0/0/0/18.1005         Up  9220 L2 .1Q:1005         -                -    1 0
Te0/0/0/18.1006         Up  9220 L2 .1Q:1006         -                -    1 0
Te0/0/0/18.1007         Up  9220 L2 .1Q:1007         -                -    1 0
Te0/0/0/18.1008         Up  9220 L2 .1Q:1008         -                -    1 0
Te0/0/0/18.1009         Up  9220 L2 .1Q:1009         -                -    1 0
Te0/0/0/18.1010         Up  9220 L2 .1Q:1010         -                -    1 0
Te0/0/0/18.1011         Up  9220 L2 .1Q:1011         -                -    1 0
Te0/0/0/18.1012         Up  9220 L2 .1Q:1012         -                -    1 `

**Comment by Harishv01** [comment]
Hi, we have merged the PR and the fix will be available in version 24.9. Hence, I am closing the issue. Thank you.
