### ISSUE TITLE
"show ip route" routepreference position in schema is incorrect

### ISSUE THREAD

**Issue by shobnaren** [CiscoTestAutomation/genieparser#88]
'*' denotes best ucast next-hop
'**' denotes best mcast next-hop
'[x/y]' denotes [preference/metric]
'%' in via output denotes VRF

show ip route static
99.0.1.1/32, ubest/mbest: 1/0
*via 11.1.10.2, [1/0], 13:35:01, static
via 10.1.10.2, [4/0], 13:35:01, static

This is on NXOS platform.

As you note 11.1.10.2 is best ucast next-hop with routepreference as 1
and 10.1.10.2 is NOT the best next-hop with routepreference as 4  # it is NON-default preference

The schema is per route - not in next-hop [INCORRECT]
https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/parsers/show%20ip%20route%20%7Bprotocol%7D

so the output is also coming up with incorrect as schema is INCORRECT.

**Comment by xiaoxinz-cisco** [comment]
Hello @shobnaren ,

Thank you for reporting. We will look into the issue and get back to you.

Thanks,
Irene

**Comment by xiaoxinz-cisco** [comment]
Hello @shobnaren 

We fixed the issue and genie package **v20.2.1b0** has been released with the fix.
Could you please run the following command and try again to see if it works?

**pip install genie.libs.parser --upgrade --pre**

Please try and let's know if there is an issue.

Thanks,
Irene
