### ISSUE TITLE
[NX-OS] show nve vni <vni> - "The pyats library return an error for 'show nve vni all' for 'nxos'. Error:   Could not find parser for 'show nve vni 3003960' under {'os': ['nxos'],   'revision': ['1']}."

### ISSUE THREAD

**Issue by Ernestas-S** [CiscoTestAutomation/genieparser#886]
Command 'show nve vni <vni>' returns error instead of correct output, https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/nxos/show_vxlan.py

error message: "The pyats library return an error for 'show nve vni all' for 'nxos'. Error:
  Could not find parser for 'show nve vni 3003960' under {'os': ['nxos'],
  'revision': ['1']}."
  
 Same error message if I try to print "all": "The pyats library return an error for 'show nve vni all' for 'nxos'. Error: Could not find parser for 'show nve vni all' under {'os': ['nxos'], 'revision': ['1']}."

Example output when I use cli command on the NX-OS device can be seen in picture:
![Screenshot 2024-09-08 141518](https://github.com/user-attachments/assets/c9fd7ce8-38a5-408f-b96f-d9579d9a3e87)

```
Codes: CP - Control Plane        DP - Data Plane
       UC - Unconfigured         SA - Suppress ARP
       SU - Suppress Unknown Unicast
       Xconn - Crossconnect
       MS-IR - Multisite Ingress Replication
       HYB - Hybrid IRB mode

Interface VNI      Multicast-group   State Mode Type [BD/VRF]      Flags
--------- -------- ----------------- ----- ---- ------------------ -----
nve1      3003960  n/a               Down  CP   L3 [KVTC_TEST_SU_KLAIDA]
```

I'm using https://quay.io/ansible/awx-ee:24.6.1 as base image for my custom EE, where I utilize "pip install pyats genie" to install required modules . pyats works, as was able to successfully run other parse commands in other tasks.

**Comment by SohanTirpude** [comment]
Hello @Ernestas-S,

Can you please share the device raw output in text format instead of sharing the screenshot? 

Thank you.

**Comment by Ernestas-S** [comment]
Codes: CP - Control Plane        DP - Data Plane
       UC - Unconfigured         SA - Suppress ARP
       SU - Suppress Unknown Unicast
       Xconn - Crossconnect
       MS-IR - Multisite Ingress Replication
       HYB - Hybrid IRB mode

Interface VNI      Multicast-group   State Mode Type [BD/VRF]      Flags
--------- -------- ----------------- ----- ---- ------------------ -----
nve1      3003960  n/a               Down  CP   L3 [KVTC_TEST_SU_KLAIDA]

**Comment by SohanTirpude** [comment]
Hello @Ernestas-S,

I have added support for `show nve vni <vni>` command and now the output looks like this:
```
{
    "nve1": {
        "vni": {
            3003960: {
                "vni": 3003960,
                "mcast": "n/a",
                "vni_state": "down",
                "mode": "CP",
                "type": "L3 [KVTC_TEST_SU_KLAIDA]",
                "flags": ""
            }
        }
    }
}
```
Kindly check and confirm if everything is correct or not.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @Ernestas-S,

The PR is merged now and the fix will be available in the upcoming pyats version i.e. 24.9. Hence, I am closing this ticket for now. If you are facing any other issues, kindly open a new ticket.

Thank you.
