### ISSUE TITLE
show lisp instance-id {instance-id

### ISSUE THREAD

**Issue by desiredrive** [CiscoTestAutomation/genieparser#898]
When trying to use show lisp instance-id 8192 ethernet server with a MAC adderss I get an exception; here is the raw output of my command that cannot be parsed:

```
Border1#show lisp instance-id 8192 ethernet server 1880.90d8.5976
LISP Site Registration Information

Site name: site_uci
Description: map-server configured from Catalyst Center
Allowed configured locators: any
Requested EID-prefix:

  EID-prefix: 1880.90d8.5976/48 instance-id 8192 
    First registered:     1d12h
    Last registered:      1d12h
    Routing table tag:    0
    Origin:               Dynamic, more specific of any-mac
    Merge active:         No
    Proxy reply:          Yes
    Skip Publication:     No
    Force Withdraw:       No
    TTL:                  1d00h
    State:                complete
    Extranet IID:         Unspecified
    Registration errors:  
      Authentication failures:   0
      Allowed locators mismatch: 0
    ETR 172.19.1.68:51370, last registered 1d12h, proxy-reply, map-notify
                           TTL 1d00h, no merge, hash-function sha1
                           state complete, no security-capability
                           nonce 0xC70B988B-0x51A970EA
                           xTR-ID 0xC2C3D55E-0x6EDFC3D0-0x984A6AF8-0xD2CBB963
                           site-ID unspecified
                           Domain-ID 2391152098
                           Multihoming-ID unspecified
                           sourced by reliable transport
      Locator      Local  State      Pri/Wgt  Scope
      172.19.1.68  yes    up          10/10   IPv4 none
```
Additionally, "show lisp instance-id (iid) ethernet server detail" is also broken; basically any iteration that displays the registration in detailed format fails.

**Comment by Harishv01** [comment]
Hi, Kindly let me know the OS to debug the issue. Thank you.

**Comment by desiredrive** [comment]
IOS-XE (Catalyst 9500) 17.12.2

**Comment by Harishv01** [comment]
Hi, For this command "show lisp instance-id (instance-id) ethernet server detail", please share the raw output and the error you are getting to debug this issue.

**Comment by Harishv01** [comment]
Hi, Please provide an update on this ticket.

**Comment by Harishv01** [comment]
Hi,

I have fixed the issue related to the command show lisp instance-id 8192 ethernet server 1880.90d8.5976, and the fix will be available in the next version i.e , 24.10. Hence, I am closing this issue.

For the command show lisp instance-id (instance-id) ethernet server detail, please share the raw output and the error message you are encountering. I will reopen it and address it.

Thank you.
