### ISSUE TITLE
"show ip multicast" cannot parse different S-G hash methods

### ISSUE THREAD

**Issue by desiredrive** [CiscoTestAutomation/genieparser#900]
When parsing "show ip multicast" and multipath is disabled (or enabled with the default settings), genie can parse it with no problems:

Tested on: Catalyst 9300 IOS-XE 17.12.3 

Parseable Outputs:

Multipath Disabled 

```
show ip multicast
  Multicast Routing: enabled
  Multicast Multipath: disabled !!!!!!!!!!!!!!!!!!!!!!!!
  Multicast Route limit: No limit
  Multicast Fallback group mode: Dense
  Number of multicast boundaries configured with filter-autorp option: 0
  MoFRR: Disabled
  Multicast Service-Reflect Capabilities:
```

Multipath Enabled:
```
show ip multicast
  Multicast Routing: enabled
  Multicast Multipath: enabled !!!!!!!!!!!!!!!!!!!!!!!!
  Multicast Route limit: No limit
  Multicast Fallback group mode: Dense
  Number of multicast boundaries configured with filter-autorp option: 0
  MoFRR: Disabled
  Multicast Service-Reflect Capabilities:
```
But when multicast sg hash is enabled, genie throws an exception:

```
Edge-1#show ip multicast 
  Multicast Routing: enabled
  Multicast Multipath: enabled (algorithm: basic)
```

or
```

Edge-1#show ip multicast 
  Multicast Routing: enabled
  Multicast Multipath: enabled (algorithm: next-hop-based)
```
commands used to enable this feature:

ip multicast multipath s-g-hash basic|next-hop-based

**Comment by SohanTirpude** [comment]
Hello @desiredrive,

Thank you for notifying this issue. Can you please provide the complete output for both command to debug this issue further?

Thank you.

**Comment by SohanTirpude** [comment]
Hello @desiredrive,

Thank you for the output, I will try to find the solution for these.

Meanwhile, I have one doubt is that are you sure that the parser is working for such output which has `!`? Like this:
```
  Multicast Multipath: enabled !!!!!!!!!!!!!!!!!!!!!!!!
```
Because when I tried, it is not working. But in the ticket description you mentioned that it is working. Can you please confirm?

Thank you.

**Comment by SohanTirpude** [comment]
Hello @desiredrive,

For the other outputs, I have found the issue and possible solution as well. With the solution now output looks like this:
```python
{
    "vrf": {
        "default": {
            "enable": True,
            "multipath": True,
            "algorithm": "basic",
            "route_limit": "no limit",
            "fallback_group_mode": "dense",
            "multicast_bound_with_filter_autorp": 0,
            "mo_frr": False
        }
    }
}
```
and
```python
{
    "vrf": {
        "default": {
            "enable": True,
            "multipath": True,
            "algorithm": "next-hop-based",
            "route_limit": "no limit",
            "fallback_group_mode": "dense",
            "multicast_bound_with_filter_autorp": 0,
            "mo_frr": False
        }
    }
}
```
Kindly check and confirm if everything is correct or not.

Thank you.

**Comment by desiredrive** [comment]
HI @SohanTirpude that works perfect, just to clarify, the previous output I paste does not really have a (!) sign, these were just for highlighting.

Thanks!

**Comment by SohanTirpude** [comment]
Hello @desiredrive,

The PR got merged and the fix will be availalbe in the upcoming pyats 24.10 release. Hence, I am closing this ticket for now. If you are facing any other issues, kindly open a new ticket.

Thank you.
