### ISSUE TITLE
[IOS-XE]parser for 'show interface {} switchport' issue

### ISSUE THREAD

**Issue by hsang88** [CiscoTestAutomation/genieparser#904]
1.  a interface is flex, it can be L2 or L3, change interface to L3 firstly

> router(config)#interface GigabitEthernet0/1/7
> router(config-if)#no switchport
> router(config-if)#end

> router#show interface GigabitEthernet0/1/7 switchport
> % Gi0/1/7 is not a switchable port
> router#

2.  parse it using cmd parse('show interface GigabitEthernet01/7 switchport '),  it will report error msg:

>  File "/nobackup/yuhe3/workspace/hsang/workspace/polaris/binos/linkfarm/sdks-host/iosxe-pyats/nativesdk/sdk/sysroots/x86_64-xesdk-linux/usr/lib/python3.10/site-packages/genie/conf/base/device.py", line 535, in parse
>  return self._get_parser_output(kwargs, parsers[0], parsers[1],
>   File "/nobackup/yuhe3/workspace/hsang/workspace/polaris/binos/linkfarm/sdks-host/iosxe-pyats/nativesdk/sdk/sysroots/x86_64-xesdk-linux/usr/lib/python3.10/site-packages/genie/conf/base/device.py", line 572, in _get_parser_output
> out = parser_instance.parse(**copy)
>  File "/nobackup/yuhe3/workspace/hsang/workspace/polaris/binos/linkfarm/sdks-host/iosxe-pyats/nativesdk/sdk/sysroots/x86_64-xesdk-linux/usr/lib/python3.10/site-packages/genie/metaparser/_metaparser.py", line 322, in parse
>   output = Schema(self.schema).validate(
>  File "/nobackup/yuhe3/workspace/hsang/workspace/polaris/binos/linkfarm/sdks-host/iosxe-pyats/nativesdk/sdk/sysroots/x86_64-xesdk-linux/usr/lib/python3.10/site-packages/genie/metaparser/util/schemaengine.py", line 233, in validate
> raise SchemaEmptyParserError(data, command)
> **genie.metaparser.util.exceptions.SchemaEmptyParserError: Parser Output is empty**

**Comment by SohanTirpude** [comment]
Hello @hsang88,

Yes, the error you are seeing is a valid error. It is showing that after parsing the parsed output is empty. It's because for `show interface GigabitEthernet01/7 switchport` command we are not getting any valid output and hence the parsed output is empty. 

For such issues, you may add exception handling in your code, like this:

```python
command = "show interface GigabitEthernet01/7 switchport"
try:
    output = dev.parse(command)
except SchemaEmptyParserError as e:
    print(f"No output found for command: {command}")
else:
    print(f"{output = }")
```
Kindly let me know if you have any questions.

Thank you.

**Comment by hsang88** [comment]
Get it , thanks.
I will close it.
