### ISSUE TITLE
Parser Output Empty - ShowIssuRollbackTimer [IOSXE]

### ISSUE THREAD

**Issue by jobower-at-cisco** [CiscoTestAutomation/genieparser#913]
Having this issue with a parser in the Platform Profile Model.
```
Could not learn <class 'genie.libs.parser.iosxe.show_issu.ShowIssuRollbackTimer'>
Parser Output is empty
```

Seems like there is an issue with the parser when a 'show issu rollback-timer' command is issued and there is an ISSU operation in progress.  The following is the output from the command.

```
2024-11-14 22:09:56,838: %UNICON-INFO: +++ svs-fc-dis-r-1-1 with via 'ssh': executing command 'show issu rollback-timer' +++
show issu rollback-timer
--- Starting local lock acquisition on chassis 2/R0 ---
Finished local lock acquisition on chassis 2/R0

INFO: Install ISSU operation in progress. This CLI is not supported.
Please use 'show issu state detail' for auto-abort timer information.
```

In addition to this issue, is there any supported functionality to exclude certain commands from a command list for a given profile?

Thanks for the help.

**Comment by sowmyadn010501** [comment]
Hi, Kindly install the below patch and test the fix
`pip install --upgrade /ws/sodn-bgl/whl_pcgs/genie.libs.parser-24.10.1b0.dev14-py3-none-any.whl`
Kindly let us know that is the output is match your needs and expectation

**Comment by sowmyadn010501** [comment]
Hi, Please let us know is above fix is satisfying your needs or not.

**Comment by jobower-at-cisco** [comment]
Hi @sowmyadn010501 that should work, thanks!

John

**Comment by dmychepk** [comment]
I think this can be ignored, more an issue with the device. Thanks

**Comment by sowmyadn010501** [comment]
PR has been merged. It will reflect in next release. Hence I am closing this ticket
else you can get the fix by updating the pyats with below command
`pyats version update --pre`
