### ISSUE TITLE
[IOS-XE] show ip bgp {route} - no multipath

### ISSUE THREAD

**Issue by dmychepk** [CiscoTestAutomation/genieparser#915]
show ip bgp 1.1.1.1/32
BGP routing table entry for 1.1.1.1/32, version 162
Paths: (4 available, best #4, table default)
Multipath: eBGP
  Not advertised to any peer
  Refresh Epoch 2
  65000 65001, (received & used)
    10.10.10.1 from 10.10.10.1 (192.168.1.1)
      Origin IGP, localpref 100, valid, external, **multipath**
      Community: 1:1
      rx pathid: 0, tx pathid: 0
      Updated on Nov 15 2024 16:52:30 EST
  Refresh Epoch 2
  65000 65001, (received & used)
    10.10.20.1 from 10.10.20.1 (192.168.1.2)
      Origin IGP, localpref 100, valid, external, **multipath**
      Community: 1:1
      rx pathid: 0, tx pathid: 0
      Updated on Nov 15 2024 16:52:28 EST
  Refresh Epoch 2
  65000 65001, (received & used)
    10.10.30.1 from 10.10.30.1 (192.168.1.3)
      Origin IGP, localpref 100, valid, external, **multipath**(oldest)
      Community: 1:1
      rx pathid: 0, tx pathid: 0
      Updated on Nov 15 2024 16:51:56 EST
  Refresh Epoch 2
  65000 65001, (received & used)
    10.10.40.1 from 10.10.40.1 (192.168.1.4)
      Origin IGP, localpref 100, valid, external, **multipath**, best
      Community: 1:1
      rx pathid: 0, tx pathid: 0x0
      Updated on Nov 15 2024 16:51:54 EST

{'instance': {'default': {'vrf': {'default': {'address_family': {'': {'prefixes': {'1.1.1.1/32': {'available_path': '4',
                                                                                                      'best_path': '4',
                                                                                                      'index': {1: {'community': '1:1',
                                                                                                                    'gateway': '10.10.10.1',
                                                                                                                    'next_hop': '10.10.10.1',
                                                                                                                    'originator': '192.168.1.1',
                                                                                                                    'recipient_pathid': '0',
                                                                                                                    'transfer_pathid': '0'},
                                                                                                                2: {'community': '1:1,
                                                                                                                    'gateway': '10.10.20.1',
                                                                                                                    'next_hop': '10.10.20.1',
                                                                                                                    'originator': '192.168.1.2',
                                                                                                                    'recipient_pathid': '0',
                                                                                                                    'transfer_pathid': '0'},
                                                                                                                3: {'community': '1:1',
                                                                                                                    'gateway': '10.10.30.1',
                                                                                                                    'next_hop': '10.10.30.1',
                                                                                                                    'originator': '192.168.1.3',
                                                                                                                    'recipient_pathid': '0',
                                                                                                                    'transfer_pathid': '0'},
                                                                                                                4: {'community': '1:1',
                                                                                                                    'gateway': '10.10.40.1',
                                                                                                                    'next_hop': '10.10.40.1',
                                                                                                                    'originator': '192.168.1.4',
                                                                                                                    'recipient_pathid': '0',
                                                                                                                    'transfer_pathid': '0x0'}},
                                                                                                      'paths': '4 '
                                                                                                               'available, '
                                                                                                               'best '
                                                                                                               '#4, '
                                                                                                               'table '
                                                                                                               'default',
                                                                                                      'table_version': '162'}}}}}}}}}

**Comment by sanjaydilli** [comment]
Hi @dmychepk, The issue has been fixed we will update once pr is merged.
Thank you.

**Comment by sanjaydilli** [comment]
Hi @dmychepk , The support has been added.The changes will be available in the next release
